### ISSUE TITLE
Lazotep Convert (Invasion of Amonkhet's back side) doesn't become a 4/4

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#10274]
Lazotep Convert (back half of Invasion of Amonkhet) copies original P/T of creature instead of setting itself as a 4/4. Here in this image the Lazotep Convert is copied as a Tireless Tracker. 

<img width="1280" alt="Screen Shot 2023-04-24 at 11 40 45 PM" src="https://user-images.githubusercontent.com/45299811/234176061-2c61440b-375a-48f1-aa25-54022bf3bf20.png">

**Comment by stevedavidmusic** [comment]
More clear example of Lazotep Convert copying a Monastery Mentor, but is a 1/2 instead of being a 4/4. 
<img width="1275" alt="Screen Shot 2023-04-30 at 6 17 09 PM" src="https://user-images.githubusercontent.com/45299811/235380602-71eee57a-f34f-4090-b1b5-088b032421d0.png">

**Comment by Don-Cruz** [comment]
It doesn't count as an transformed card either. I had a game with Mutagen Conoisseur and the transformed Amonkhet battle does not give it +1/+0.
<img width="469" alt="Invasion Amonkhet 1" src="https://github.com/magefree/mage/assets/78379079/2d90729d-0e05-4c13-abf7-915dcaa2eb92">
In this example the transformed Amonkhet is copying a Strobe Knight.
<img width="469" alt="Invasion Amonkhet 2" src="https://github.com/magefree/mage/assets/78379079/05287d6e-924c-4015-bd8a-3e72bd3ec1c1">
The second picture shows the other side of the transformed Amonkhet to show the Strobe Knight is the transformed battle and not a regular clone.
As in the post above it is a 2/2 instead of a 4/4. The Mutagen Conoisseur is a 0/5 instead of a 1/5.

[https://scryfall.com/card/mom/248/mutagen-connoisseur](url)
