### ISSUE TITLE
Vendilion Clique force chooses a card if your hand only has one valid choice

### ISSUE THREAD

**Issue by vernonross21** [magefree/mage#10487]
For instance if [Vendilion Clique](https://gatherer.wizards.com/pages/card/details.aspx?multiverseid=152549) your opponent and they have in hand 2 lands and one spell. The one spell will automatically be chosen

**Comment by alexander-novo** [comment]
It looks to me like this is due to the implementation for `HumanPlayer.choose()` calling `target.tryToAutoChoose()`:

https://github.com/magefree/mage/blob/9e63858db6ca64095e5ea19e5d8ef75aa37c4f3d/Mage.Server.Plugins/Mage.Player.Human/src/mage/player/human/HumanPlayer.java#L741

And neither function respects whether or not the target is required.
