### ISSUE TITLE
Storm count

### ISSUE THREAD

**Issue by IttyBittyKittyCat** [magefree/mage#1051]
I was playing a cube match just a moment ago and the storm count did not seem to work correctly.

In this one turn, I cast Mystical Tutor, Frantic Search, Demonic Tutor, Lion's Eye Diamond, Timetwister, Repeal, Demonic Tutor, Yawgmoth's Will, Demonic Tutor, Mind Twist, and then Brain Freeze. Storm count ended up saying that it was 5. 

Board state for this turn...
Dimir Signet, Gruul Signet, Mirari's Wake, Blood Crypt, Urborg, Tomb of Yawmogth, Isolated Chapel, Volcanic Island, and after the Timetwister, Taiga.

Edit: For some reason said end spell was brainstorm in stead of brain freeze.

**Comment by emerald000** [comment]
Had the bug too. Here's the log (cleaned up for readability): http://pastebin.com/8jK2T82t

 Here's the details of Turn 11:

I cast Wheel of Fortune. (#1)
I cast Mox Emerald. (#2)
I cast Turnabout. (#3)
I cast Yawgmoth's Will. (#4)
I cast Palinchron from graveyard. (#5)
I cast Mind's Desire from graveyard. Storm makes 2 copies (instead of 5). (#6)
I cast Turnabout from graveyard. (#7)
I cast Golgari Signet from exile. (#8)
I cast Empty the Warrens. Storm makes 5 copies (instead of 8). (#9)

**Comment by LevelX2** [comment]
> I guess Yawgmoth's Will the culprit somehow.

It was much simplier (as often before) a missing copy of an class attribute.
So the problem happens always if you cancel something that causes a state rollback.
