### ISSUE TITLE
XMage steals window focus whenever the screen updates

### ISSUE THREAD

**Issue by bwoods89** [magefree/mage#1054]
Whenever the screen updates (for example, it being my upkeep, and the done button appears), focus is returns to the java application over whatever other window had focus.

According to this stackoverflow post: http://stackoverflow.com/questions/18452446/how-to-prevent-a-java-graphical-program-from-stealing-focus-when-updating-the-wi

There is a simple fix by replacing calls to setVisible() in the JFrame with calls to repaint()

**Comment by Nidhoegger** [comment]
I am looking into this since a few days, trying to tangle a bit with swing. The Problem is not caused by setVisible, also it would be very much work replacing this with repaint, as you need to evaluate where you need to call setVisible and where to call repaint, as many components get shown and hidden all the time.

My guess (what i am into testing atm) is, that you need to set setAutoRequestFocus to false, this will cancel the focus stealing from other windows.

**Comment by Nidhoegger** [comment]
The Problem is the Feedback Panel: The buttons request the Focus explicitly. I am correcting this to only request focus, if the window has the focus already.

**Comment by LevelX2** [comment]
> if the window has the focus already

You mean the xmage window I guess.
A related problem may be that if you write to the xmage game chat a similar problem happens. You lose the focus and confirm unintened a" Done" button by typing a blank.

Maybe the focus should only be set, if the Feedback Panel itself has already focus.

**Comment by Nidhoegger** [comment]
That would be another possiblity. Im testing the fix atm and do not seem to have any problems so far.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

**Comment by JayDi85** [comment]
It must be fixed long ago with reworked choose dialogs.
