### ISSUE TITLE
Command Beacon doesn't put commander into hand.

### ISSUE THREAD

**Issue by AnAbstractPixel** [magefree/mage#10662]
When [[command beacon]] is activated while my commander is in the command zone nothing happens. I've attached an image of what it says in the bottom right when you activate command beacon.

![image](https://github.com/magefree/mage/assets/112192220/bb6259b7-f03c-4d46-b7cf-a502ab17274e)

**Comment by PurpleCrowbar** [comment]
In Commander, any time your commander would move zone, you are given the option to instead move it to the command zone. In the case of Command Beacon, the act of moving your commander from the command zone to your hand would trigger this rule, giving you the prompt to either have the commander successfully move to the zone in question (in this case, the hand), or to instead be moved to the command zone. Here is the prompt that comes up after Command Beacon's ability resolves:

![image](https://github.com/magefree/mage/assets/26198472/72f03822-a1d2-4ec9-b44c-fc454a3a29e6)

When you click on "yes" to the question "move <commander name\> to command zone instead of your hand?" the commander is moved to the command zone instead of your hand.
