### ISSUE TITLE
More Umezawa's Jitte bugs

### ISSUE THREAD

**Issue by billyg-da-great** [magefree/mage#10763]
Umezawa's jitte getting an extra set of counters (so 4 instead of 2) when equipped creature has trample and hits a creature and player.

scenario showing this:
1.) opponent has reality smasher equiped with umezawa's jitte and no counters
2.) swings in and is blocked by glistener elf, then pendlehaven is activated on elf making it a 2/3
3.) berserk is cast on glistener elf to make it a 4/3 (to give the smasher 4 -1/-1 counters)
4.) combat damage hits (no first strike phase because nothing has first strike or double strike)
5.) umezawa's jitte gets 4 counters ?????? should only have 2, non double strike damage (even trample on multiple creatures/players) is only 1 set of damage and should only give 2 counters

ty

**Comment by xenohedron** [comment]
Looks like we have `GameEvent.EventType.DAMAGED_PLAYER_BATCH` along with `GameEvent.EventType.DAMAGED_PERMANENT_BATCH` and the trigger checks both. The engine needs to be adjusted to fire a new event encompassing both so that abilities like this can have a single event trigger. Should be doable, but not a straightforward fix.

**Comment by ssk97** [comment]
Looking at `DealsCombatDamageTriggeredAbility`, that issue has previously been solved with a `usedInPhase` boolean. It'd probably be easier to just port that logic over to `DealsCombatDamageEquippedTriggeredAbility` as well?
