### ISSUE TITLE
Liliana, Heretical Healer doesn't create a zombie when tranforming

### ISSUE THREAD

**Issue by Lokkij** [magefree/mage#1090]
The transform trigger on Liliana, Heretical Healer does not seem to create a 2/2 zombie token.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.2v1

**Comment by fireshoes** [comment]
Did you notice someone mentioned if Liliana and another nontoken creature die at the same time, she is returning from the graveyard to the battlefield transformed? I think that is incorrect behavior because of the "then return her to the battlefield" clause, in which the zombie token should also not be created. "If you do, put a 2/2 black Zombie creature token onto the battlefield." tooltip is missing, and also missing a space between "under her".
