### ISSUE TITLE
Liliana, Heretical Healer

### ISSUE THREAD

**Issue by ee10bt** [magefree/mage#1123]
Regardless of how many exile triggers go on the stack, you should only get one Zombie when Liliana flips. Two of my opponents creatures died in combat, and they got two Zombies as a result of flipping Liliana.

**Comment by Nidhoegger** [comment]
True, see Ruling 22.06.15: "If multiple nontoken creatures you control die, then Liliana, Heretical Healer’s ability will trigger that many times. However, since Liliana can be exiled and returned to the battlefield only once, only the first ability to resolve will create a Zombie token. The other abilities will resolve but won’t do anything."
