### ISSUE TITLE
Liliana, Death's Majesty text issue

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11257]
In xmage, [[Liliana, Death's Majesty]]'s -3 ability text contains the sentence "That creature is a black Zombie in addition to its other types" twice. See below:

![image](https://github.com/magefree/mage/assets/26198472/be9d9e33-e8c8-4b29-b873-2fa5b68c3324)

It should only appear once and should be the final sentence in the ability text. Issue appears to be caused by `.setText("")` being ignored and not actually setting an effect's text to an empty string.

**Comment by xenohedron** [comment]
Alright, that's interesting. It isn't caught by the verify check because the text is correct in hand.... it's incorrect only on the battlefield. Worth a look into how that inconsistency arises.

Anyway, setting `staticText` to an empty string is not supported by the rules generation. It could probably be refactored to support it, but I don't think that's really worth it as there are only a couple dozen instances of `setText("")` in the codebase that need to be cleaned up and the refactoring would touch a lot more than that. The workaround is to split the desired text over the effects within the ability. Or if you need no text for an entire ability, then use `setRuleVisible(false)`.

I'll get this one fixed in my next batch of text improvements.

**Comment by xenohedron** [comment]
Found the problem... copy constructor for the effect was calling the internal updateText method and overwriting the staticText with the default generation.
