### ISSUE TITLE
Morophon, the Boundless does not reduce the mana cost of selected creature types.

### ISSUE THREAD

**Issue by BakerWade** [magefree/mage#11388]
Morophon, the Boundless was cast and the mana-reduction didn't work and on the next turn it was only applicable for the casting of one creature of the selected type.
Urza's Incubator on the board and possibly clashed with its effect.

**Comment by jeffwadsworth** [comment]
[[Morophon, the Boundless]] [[Urza's Incubator]]

**Comment by jeffwadsworth** [comment]
I tested this and it worked perfectly for me.  Both cards in play so they stack because you are cost reductions, not an additional cost.  So if you picked "Hydra", something like a [[Projenitus]] would cost WUBRG.  The Urza's Incubator would not affect it due to being 2 colorless.  A [[Blazing Archon]] would be 4WW with both of these cards in play if you chose "Archon" as the type.  The cost reduction worked for multiple casts in the same turn while these cards were in play.

**Comment by jeffwadsworth** [comment]
[[Progenitus]]
