### ISSUE TITLE
Regression - custom Pillar of the Paruns mode no longer works

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11404]
Reported today that the game crashes right when the conjure trigger would occur.
> Game exception occurred: 
mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.52-V6-beta6 (build: 2023-11-10 14:03)
Stack trace:
mage.game.GameImpl.playPriority(GameImpl.java:1696)
mage.game.turn.Step.priority(Step.java:66)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1122)
mage.game.GameImpl.play(GameImpl.java:1029)
mage.game.GameImpl.start(GameImpl.java:1005)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Susucre** [comment]
I'll probably rethink the entire custom mode at some point (maybe using emblem instead), as it is kinda a hack on adding delayed trigger in game initialization, and since it's a plugin, it is hard to test to avoid future regression.

For now, I've fixed the Modes' code NPE due to the delayed trigger not having a proper source in https://github.com/magefree/mage/commit/0241a788a01cf240fddb3fdfba4cfd632e9e267e
