### ISSUE TITLE
Magus Lucea Kane does not work as intended with Kessig Wolf Run. And with all X activated abilities ?

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#11440]
Hello.

When you tap Magus Lucea Kane for mana and then activate Kessig Wolf Run's ability, Magus's delayed trigger won't trigger. It's maybe only a problem with Kessig Wolf Run but I guess the issue only comes from Magus Lucea Kane because when you have Unbound Flourishing on the battlefield, you willl get a copy of Kessig's trigger thanks too Flourishing.

**Comment by Reya87** [comment]
I made a quick test against AI: you will effectively get a copy of Kessig ability if you have Unbound Flourishing but Lucea Kane won't trigger when you activate Kessig.

**Comment by xenohedron** [comment]
The checks are different so that's probably the issue:

https://github.com/magefree/mage/blob/44702779d9360608cf8eeeaf473a7fd8e13efa22/Mage.Sets/src/mage/cards/m/MagusLuceaKane.java#L86-L92

https://github.com/magefree/mage/blob/44702779d9360608cf8eeeaf473a7fd8e13efa22/Mage.Sets/src/mage/cards/u/UnboundFlourishing.java#L122-L128

**Comment by jeffwadsworth** [comment]
[[Magus Lucea Kane]]  [[Kessig Wolf Run]]  [[Unbound Flourishing]]
