### ISSUE TITLE
Volo's Journal issue (Changeling)

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#11536]
When I cast a creature with Changeling, Volo's Journal doesn't let me choose a creature type to note. It will only note Shapeshifter from the creatures type line.

**Comment by Bdett151** [comment]
I should have added in the origin post that Volo's Journal is created by Volo, Itinerant Scholar

**Comment by xenohedron** [comment]
Token attempts to handle this case correctly

https://github.com/magefree/mage/blob/f75b1c9f0aa8f17c6df4e2570c39739a9a2691b7/Mage/src/main/java/mage/game/permanent/token/VolosJournalToken.java#L113-L123

but for some reason Spell overrides the method to always return false

https://github.com/magefree/mage/blob/bea33c7493c445e37fab564d180fd3b05f564f9c/Mage/src/main/java/mage/game/stack/Spell.java#L1126-L1129

not sure if that override is needed for something, or if there's a better way to check isAllCreatureTypes in this scenario

[[Volo, Itinerant Scholar]]

**Comment by JayDi85** [comment]
Related issue from discord:

On the battlefield i have [[Nalia de'Arnise]] as Commander and [[Folk Hero]]. When i cast a creature with Changeling, in this case [[Mirror Entity]], Nalia's ability given by Folk hero doesn't trigger. Strage, since Changeling ability also works for cards in the hand and in the deck.

![IMG_9348](https://github.com/magefree/mage/assets/8344157/e4b853ec-081a-4106-8823-0f6282808004)
