### ISSUE TITLE
Miss Incubator token images from tokens database and downloads

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11535]
![IMG_9320](https://github.com/magefree/mage/assets/8344157/546d2465-19f2-4371-ac65-c261589d4023)

**Comment by PurpleCrowbar** [comment]
Adding the token images causes the front face of the Incubator token to show correctly, but transforming it causes the token to have no image assigned, seemingly because the backface of the Incubator has no set code.

Front face Incubator:
![image](https://github.com/magefree/mage/assets/26198472/7da3bcb9-f85b-42ac-a9ce-8b106b97fd65)

Back face Incubator:
![image](https://github.com/magefree/mage/assets/26198472/a5fa80f4-ad48-4529-bf39-d6563f89a80a)

**Comment by JayDi85** [comment]
@PurpleCrowbar can you add miss token images to database/download? I'll look at copy/transform code later to fix missing set/image info.

**Comment by PurpleCrowbar** [comment]
> @PurpleCrowbar can you add miss token images to database/download? I'll look at copy/transform code later to fix missing set/image info.

Done

**Comment by JayDi85** [comment]
Fixed miss images by 00a7cc645d0e7502be2e57d683ed3176255ca992, but there are more global problems with back face copies -- see #11307
