### ISSUE TITLE
Issue with Kinnan ability and Mana sources

### ISSUE THREAD

**Issue by Zangster90** [magefree/mage#11643]
Kinnan's first ability to add an extra mana from tapping non land permanents isn't working correctly with cards like Bloom Tender and Simic Signet. The client will prompt and ask if you want to add either Green or Blue mana but will only ever add Blue, even if you have selected green.

**Comment by xenohedron** [comment]
Most likely root cause of the problem:
https://github.com/magefree/mage/blob/f75b1c9f0aa8f17c6df4e2570c39739a9a2691b7/Mage/src/main/java/mage/abilities/effects/mana/AddManaOfAnyTypeProducedEffect.java#L106-L110

Looks like it just chooses the first in the list of choices instead of the actual choice. Could be a regression caused by #7679, mistake when refactoring, or maybe was never right to begin with.
