### ISSUE TITLE
Locus of Enlightenment can only be used once each turn in total

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#11735]
You're supposed to be able to use _each_ of the exiled ability once per turn, but after one use of any ability [[Locus of Enlightenment]] stops being able to be used.

Had a Narset and a Chandra exiled, and after I used one of Chandra's abilities nothing happened when clicking it.

In addition, that first turn only Chandra's abilities were able to be chosen, while Narset's showed up the turn after.

Also non-activated abilities from instants and sorceries (which could be exiled, I don't think they should be) showed up on the card when hoovering, which I think is incorrect.

**Comment by Susucre** [comment]
From the rules, you can only activate one loyalty ability of a given permanent each turn, so that part is correct and not a bug.

You can definitively exile instant and sorcery with the craft ability, provided they have activated abilities. However most of those should not work for a permanent on the battlefield.

**Comment by Susucre** [comment]
[[Lightning Storm]] for instance.
A bunch with abilities like Cycling too.
