### ISSUE TITLE
MKM | Case of the Shattered Pact does not auto solve at the beginning of the end step

### ISSUE THREAD

**Issue by Alvianosi** [magefree/mage#11858]
Case of the Shattered Pact does not auto solve at the beginning of the end step

**Comment by DominionSpy** [comment]
Do you have an example game state where you expected it to solve, but didn't?

**Comment by Alvianosi** [comment]
As the oracle of the case says, the case will go from unsolved to solved at
the beginning of my end step, however i think none of the MKM case card
does that at the moment. The card will stay unsolved if you can't solve the
solve requirement. Where it should actually be solved at the beginning of
my end step regardless of the requirement.

If you mean a specific log file, then i'm sorry, i don't think i have that.
Or if i were to be given instructions, i could help gather game logs or
something, maybe.

**Comment by xenohedron** [comment]
You are misunderstanding. The printed reminder text is perhaps a bit misleading, but the condition must be met, otherwise it remains unsolved.

719.3a. "To solve -- [Condition]" means "At the beginning of [your](https://yawgatog.com/resources/magic-rules/#you_your) [end step](https://yawgatog.com/resources/magic-rules/#end_step), if [condition] and this [Case](https://yawgatog.com/resources/magic-rules/#case) is not [solved](https://yawgatog.com/resources/magic-rules/#solved), this [Case](https://yawgatog.com/resources/magic-rules/#case) [becomes](https://yawgatog.com/resources/magic-rules/#becomes) [solved](https://yawgatog.com/resources/magic-rules/#solved)."

**Comment by Alvianosi** [comment]
Thank you for the clarification.
