### ISSUE TITLE
Commander cast error

### ISSUE THREAD

**Issue by Alvianosi** [magefree/mage#11864]
Game error occurred: 

java.lang.NullPointerException
Server version: 1.4.52-V7-beta7 (build: 2024-01-30 18:53)
Stack trace:
mage.abilities.condition.common.SacrificedArtifactThisTurnCondition.apply(SacrificedArtifactThisTurnCondition.java:27)
mage.abilities.effects.common.cost.SpellCostReductionSourceEffect.applies(SpellCostReductionSourceEffect.java:95)
mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:700)
mage.players.PlayerImpl.canPlay(PlayerImpl.java:3562)
mage.players.PlayerImpl.findActivatedAbilityFromPlayable(PlayerImpl.java:3858)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:4080)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:4238)
mage.server.game.GameSessionPlayer.prepareGameView(GameSessionPlayer.java:216)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:200)
mage.server.game.GameSessionPlayer.lambda$select$2(GameSessionPlayer.java:67)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionPlayer.select(GameSessionPlayer.java:67)
mage.server.game.GameController.lambda$select$19(GameController.java:867)
mage.server.game.GameController.perform(GameController.java:998)
mage.server.game.GameController.perform(GameController.java:991)
mage.server.game.GameController.select(GameController.java:867)
mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:197)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.PlayerQueryEventSource.select(PlayerQueryEventSource.java:46)
mage.game.GameImpl.firePriorityEvent(GameImpl.java:2941)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1314)
mage.game.GameImpl.playPriority(GameImpl.java:1650)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1117)
mage.game.GameImpl.play(GameImpl.java:1024)
mage.game.GameImpl.start(GameImpl.java:1000)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by xenohedron** [comment]
@PurpleCrowbar is c466847 for this? What's the root cause? Seems like each of the three usages adds the watcher so not sure how would be null

**Comment by PurpleCrowbar** [comment]
> PurpleCrowbar is [c466847](https://github.com/magefree/mage/commit/c4668476b1fa13596ee2020c5e0a4983a2281dbd) for this? What's the root cause? Seems like each of the three usages adds the watcher so not sure how would be null

My commit fixed [these cards](https://scryfall.com/search?q=o%3A%22sacrificed+an+artifact+this+turn%22&unique=cards&as=grid&order=name), which previously would all throw an NPE and rollback when cast. The issue was that `.getThisTurnSacrificedPermanents(source.getControllerId())` was returning null and the attempt to call `.stream()` on that was causing an NPE. None of the affected cards are valid commanders, but presumably the title of this issue is relating to the format in which the issue was discovered, so safe to say that commit closes this issue

**Comment by xenohedron** [comment]
Ah okay, I get it now, thanks for clarifying.

I do think a better style in general would be for that watcher's method to use `.getOrDefault()` and return an empty list instead of null (looks like Goblin Blast Runner and maybe others would need to be updated to check the size of the list rather than explicitly for null)
