### ISSUE TITLE
Disguise cards not working with Obscuring Aether and Assemble the Players not allowing Disguise (maybe any face down) creatures cast from the top of the deck

### ISSUE THREAD

**Issue by avaramis** [magefree/mage#11923]
Obscuring Aether didn't lower the cost of a disguise creature.
Assemble the players didn't let me cast a face down creature - I thought it was a morph but may have been disguise.

**Comment by xenohedron** [comment]
Two separate bugs here:
[[Obscuring Aether]] - `MorphSpellsCostReductionControllerEffect` is checking `instanceof MorphAbility`
[[Assemble the Players]] - needs to check spell characteristics rather than card characteristics (there are other similar custom effects that could be bugged in the same way)

**Comment by xenohedron** [comment]
Fixed by #11962 and #11946
