### ISSUE TITLE
Cavern of Souls resets incorrectly

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1219]
I cast a Primeval Titan with the second ability of Cavern of Souls. It gets bounced into my hand with Cyclonic Rift during combat. After combat, I cast it again without using Cavern of Souls at all. My opponent tries to counter it, but fails because apparently I used Cavern of Souls to make the spell uncounterable.

**Comment by Fiorden** [comment]
Im trying to solve this.

**Comment by Fiorden** [comment]
I cant repeat this bug on the developer enviroment but I managed to do it on production so I assume its been fixed earlier.

**Comment by drmDev** [comment]
As noted above - not sure if this issue is still occurring? Will try to test this today.

**Comment by drmDev** [comment]
This issue is still occurring. Once you use mana to make a creature uncounterable, all further casts of that creature that turn are still uncounterable despite not using Cavern of Souls ability for it the next time.

Not sure if I can make a unit test for this, but was able to duplicate it testing player vs player with this init file (replace player names obv):

hand:PLAYERA:Counterspell:1
hand:PLAYERA:Cyclonic Rift:1
battlefield:PLAYERA:Island:4

battlefield:PLAYERB:Forest:4
battlefield:PLAYERB:Urza's Mine:1
battlefield:PLAYERB:Urza's Power Plant:1
battlefield:PLAYERB:Urza's Tower:1
hand:PLAYERB:Cavern of Souls:1
hand:PLAYERB:Primeval Titan:1

---
PLAYERB cast Primeval Titan using Cavern + 2 Forests + Tower and it resolves. Then PLAYERA uses Cyclonic Rift to return Titan to hand. PLAYERA cast Titan again with remaining lands and PLAYERB tries to counter with Counterspell but is informed the creature cannot be countered. Titan resolves for the 2nd time.
