### ISSUE TITLE
image download issue - SLD 209/811

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12511]
from [77aba62](https://github.com/magefree/mage/commit/77aba627b01ec93878d401e96060d85950ba2b62#r143429616)

Including Norn's [811 SLD variant](https://scryfall.com/card/sld/811/elesh-norn-grand-cenobite) in the download list caused the [209 SLD variant](https://scryfall.com/card/sld/209/%7Cducgnorn-gsedzaonobt) to not be able to download correctly. Seemed to happen when NON_FULL_USE_VARIOUS was applied. Potentially due to some weirdness regarding 209's URL.

**Comment by tiera3** [comment]
With https://github.com/magefree/mage/commit/17507970364e146b73e9926084fd12ef095c9041 and https://github.com/magefree/mage/pull/12508 merged, it should be using https://api.scryfall.com/cards/sld/209?format=image&version=normal&include_variations=true as its second attempt to download the file after the first attempt fails due to this being a phyrexian language card. Was this not the attempted URL?

**Comment by JayDi85** [comment]
With new bulk data usage it works fine. But I don't test api links generating for it.

![shot_240803_193855](https://github.com/user-attachments/assets/090b0ce5-8df8-426b-b3ca-ed7cb19bd788)
