### ISSUE TITLE
GUI: add a hint / button / other to refer to a specific exile zone.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12544]
Working on [[Salvation Swan]], I would have liked to link the Delayed Trigger Ability with the exile card (or cards, if targetting a meld/one day a mutate stack) in the exile zone. As you could have multiple such delayed triggers, and the order of triggers can matter.

I think there is plenty of scenarios where we'd want to connect a trigger / stack object / permanent / card / other to a given exile zone (like Oblivion Ring and it's exile zone).

The easy but not that nice way would be to display a unique text identifier in both the hint (maybe only if the exile zone is non-empty?) and the exile zone, but I wonder if we could improve the client to help players identify a specific exile zone on such situation?

**Comment by JayDi85** [comment]
There are multiple tools to add additional info to the card/permanent:

![IMG_0577](https://github.com/magefree/mage/assets/8344157/26d5fe82-3bfb-4120-8057-2162d6f638ef)

**Comment by Susucre** [comment]
Yeah that would be the way to add a text hint. I'm not against adding a general ExileZoneHint that describes all the cards in it, which would help in most situations.

But since there is a lot of cards that care about a specific exiled card / exile zone, it would make sense to go beyond text, and have a way to highlight the referenced exile zone.

**Comment by JayDi85** [comment]
It's not about new GUI. There were multiple problems with Salvation Swan:

1 - Wrong card logic -- must use shared exile window like other cards does in same use cases. So users will see exiled cards in one window (one window per source object):
![shot_240701_183013](https://github.com/magefree/mage/assets/8344157/bc735a5d-9683-4eb0-9ce6-42b1b682714f)
Fixed by ddb7e21dc2dc874970d99bbb15a69c0a54a4d5aa:
![shot_240701_222523](https://github.com/magefree/mage/assets/8344157/d58dbbfd-fa5a-4383-94be-e9b8327ce252)

2 - Wrong "related objects" code for card hints on stack. Fixed by dc86ec10810f85ab198a94826022faacb0b0ed7e, now it show affected objects for triggers on stack (order triggers dialogue already used it):
![shot_240701_185514](https://github.com/magefree/mage/assets/8344157/9fbdb73b-862e-41b1-a613-ad401d81649d)

3 - Not related to GUI -- there are problems with melded cards -- effect move all parts as one, but related effect later must be applied to all parts. There are two workarounds for such use cases:
* custom exile zone id (search after move);
* manual collect melded parts before move;

Both methods are bad and require custom code (but better that than nothing) Alternative solutions like return moved parts by move methods are hard to implement. Also melded code looks very bad with batch of hacks/workarounds (see code comments from bccf323c0f822cdb90b7599c097817e8085b116c). Related issue #12084.
