### ISSUE TITLE
Domination Drone trigger

### ISSUE THREAD

**Issue by ironmesh** [magefree/mage#1255]
Domination Drone triggers life loss without another colorless creature on the field. 
![image](https://cloud.githubusercontent.com/assets/8585996/9777615/94daca58-5734-11e5-8d2b-3425940f01a2.png)

**Comment by jgabrielygalan** [comment]
I've debugged this problem and the culprit seems to be that the PermanentsOnTheBattleFieldCondition calls the Battlefield.count method, who in time calls FilterImpl.match is only checking the predicates Set, and not the extraPredicates set. On the other hand, the FilterControlledPermanent behaves differently with normal Predicates like Colorless than with ObjectSourcePlayerPredicate, like Another. The first one is added to the predicates Set (add method in FilterImpl), while the second is added to extraPredicates (add method in FilterPermanent). The condition that it has to be a creature is not even present.
And so, the ability is only checking that there's a colorless permanent (any land will do) and hence the Drone always deals 2 damage.

I'm not familiar enough with the code base to propose a fix, but if someone from the project can give me some guidelines I could provide a patch.

**Comment by fireshoes** [comment]
I fixed it yesterday for the next update.
