### ISSUE TITLE
Canadian Highlander points list is out of date

### ISSUE THREAD

**Issue by Basedx** [magefree/mage#12557]
The points list was said to be updated as per issue #11602 but it seems to have either not been done correctly, or only updated the list as to what was on the reddit post mentioned in the issue reply. Regardless its been updated since then anyway. Please use https://canadianhighlander.ca/points-list/ to update the points list correctly.

**Comment by Susucre** [comment]
Feel free to make a PR with the list points updated.
Format legality are made by hand when someone think to do it, so best is for the players caring about the formats to track when things change.

**Comment by Basedx** [comment]
> Feel free to make a PR with the list points updated. Format legality are made by hand when someone think to do it, so best is for the players caring about the formats to track when things change.

Okay how does one do this then? Unless you mean literally just make the list and post it in this comment.

**Comment by Susucre** [comment]
Here is the current list we have in XMage:

https://github.com/magefree/mage/blob/1d9cc2a87f093e38aa999d57365c289cc9247b8a/Mage.Server.Plugins/Mage.Deck.Constructed/src/mage/deck/CanadianHighlander.java#L20-L59

If you could either give an updated list, or details the changes made since, I could made the change directly. The alternative would be for you to clone the repository, make a change directly in that file, and open a PR for that. Here the documentation of github on that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Basedx** [comment]
```
pointMap.put("Ancestral Recall", 8); 
 pointMap.put("Ancient Tomb", 1); 
 pointMap.put("Black Lotus", 7); 
 pointMap.put("Demonic Tutor", 3); 
 pointMap.put("Dig Through Time", 1); 
 pointMap.put("Flash", 7); 
 pointMap.put("Forth Eorlingas!", 1); 
 pointMap.put("Gifts Ungiven", 1); 
 pointMap.put("Imperial Seal", 1); 
 pointMap.put("Intuition", 1); 
 pointMap.put("Mana Crypt", 5); 
 pointMap.put("Mana Drain", 1); 
 pointMap.put("Mana Vault", 1); 
 pointMap.put("Mox Emerald", 3); 
 pointMap.put("Mox Jet", 3); 
 pointMap.put("Mox Pearl", 3); 
 pointMap.put("Mox Ruby", 3); 
 pointMap.put("Mox Sapphire", 3); 
 pointMap.put("Mystical Tutor", 1); 
 pointMap.put("Natural Order", 1); 
 pointMap.put("Sol Ring", 4); 
 pointMap.put("Spellseeker", 1); 
 pointMap.put("Strip Mine", 2); 
 pointMap.put("Survival of the Fittest", 1); 
 pointMap.put("Tainted Pact", 1); 
 pointMap.put("Thassa's Oracle", 7); 
 pointMap.put("Time Vault", 7); 
 pointMap.put("Time Walk", 6); 
 pointMap.put("Tinker", 3); 
 pointMap.put("Tolarian Academy", 1); 
 pointMap.put("Treasure Cruise", 1); 
 pointMap.put("True-Name Nemesis", 1); 
 pointMap.put("Underworld Breach", 3); 
 pointMap.put("Vampiric Tutor", 2); 
 pointMap.put("Wishclaw Talisman", 1); 
```

**Comment by Susucre** [comment]
Thanks, will be updated next release.
