### ISSUE TITLE
Teferi's Ageless Insight incorrect interaction with "for each card drawn this way"

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#12616]
Because [[Teferi's Ageless Insight]] replaces the draw event with two card draws, `Player::drawCards` doesn't return the number of cards drawn. A note on this method explicitly states this:
https://github.com/magefree/mage/blob/3ec3b773e3c85856bc26a7b68ac01efccf5f2820/Mage/src/main/java/mage/players/Player.java#L409-L430

Casting [[Ancient Excavation]] with three other cards in hand and a TAI in play causes the player to draw 6 cards. They should then discard 6 cards, as per Ancient Excavation's wording ("_discard a card for each card drawn this way_"); I have confirmed this with a judge. Currently in XMage, the player discards 0 cards, as the `drawCards` call is returning 0 due to TAI replacing each of the three draw events.

All of [these](https://scryfall.com/search?q=o%3A%22each+card+drawn+this+way%22) cards should be affected by this problem.

**Comment by xenohedron** [comment]
Question - for the "each card drawn this way", what if a replacement effect causes an opponent to draw instead of you? would those count as cards drawn "this way" ?

I'm pondering this and I think I have a way to refactor that passes through the amount on replacement back to the original method call... it'll be kinda convoluted, but it needs to be as the simpler solutions I thought of are flawed.

(I thought I could fix this by storing the amount of cards to draw in the event checked by replacement effects, so that the event didn't need to be fully replaced to change the amount. But in order for this to work, the replacement effect has to be checked on the drawing of multiple cards, not the drawing of individual cards. Unfortunately, it can't work for all replacement effects to check that, because if you have multiple replacement effects, you need to be able to order them separately for each card drawn, so they need to check the drawing of individual cards.)
