### ISSUE TITLE
Karplusan Forest and Grove of the Burnwillows function differently.

### ISSUE THREAD

**Issue by Dunkoro** [magefree/mage#12661]
This is a very minor thing, but I feel like a lot of lands would benefit from the smart-tapping that the Grove provides.
Karplusan Forest is one of the examples, but cards like Cavern of Souls and Eldrazi Temple could definitely benefit as well.

**Comment by xenohedron** [comment]
I'm really not sure what you're referring to here

**Comment by Grath** [comment]
There's a meaningful difference in how the game functions between the `SimpleManaAbility` of painlands (and others) vs the `RedManaAbility` and `GreenManaAbility` of Grove of the Burnwillows, in particular that the Painlands will always prompt you whether or not to tap for colors even if there's only colorless costs left to pay. Similarly, Cavern of Souls could be done such that if you're casting a creature of the type chosen with Cavern of Souls, it will automatically use Cavern's colored mana ability rather than prompting the player for which mana ability to use.

**Comment by jeffwadsworth** [comment]
[[Grove of the Burnwillows]] [[Karplusan Forest]]

**Comment by JayDi85** [comment]
For info:
- there is special user settings from battlefield menu (right mouse click): "Use first mana ability when tapping lands" -- it's control tap for mana in lands with multiple mana abilities (possible reason for Cavern of Souls misclicks);
- there are possible replacement and other effects -- so it's hard to predict better mana choice without game simulation;
- code to hide ability picker: `HumanPlayer->suppressAbilityPicker`;

**Comment by Dunkoro** [comment]
Yeah, when it comes to Cavern of Souls, I wish it tapped for the colored mana automatically when tapping for mana when casting the appropriate spells, and tap for colorless automatically when tapping for mana otherwise.
Similarly, Eldrazi Temple could tap for 2 automatically when casting an Eldrazi spell and for 1 otherwise.

**Comment by xenohedron** [comment]
fixed in #12871
