### ISSUE TITLE
Compile error for javafx on alpine docker

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12717]
I'm compiling the project on an amaretto docker. The recent changes have broken the build.

It seems that the javafx introduced for the what's new dialog is causing issue:

![image](https://github.com/user-attachments/assets/3e90381f-6449-4ec9-9060-4d6903fbcf21)

Is there a version not strict enough in one of the pom.xml file?

**Comment by Susucre** [comment]
On second thought, is that a java 11 / java 8 discrepency?

**Comment by JayDi85** [comment]
52 - java 8
54 - java 10

Xmage uses JavaFX 11 — it’s compatible with java 8. I’m testing it with diff versions of OpenJDK (adoptium: https://adoptium.net/ ).

Maybe your system has another default java (not 8). Try check your JAVA_HOME and maven’s java version from here: https://stackoverflow.com/a/65290634

**Comment by Susucre** [comment]
I think I'm setup properly:

![image](https://github.com/user-attachments/assets/833704cc-02a0-48b6-a53a-92fec9d3f96f)

I compile and bundle with the following docker file:

```
FROM amazoncorretto:8-alpine

ENV JAVA_MIN_MEMORY=768M \
    JAVA_MAX_MEMORY=1536M \
    GLIBC_VERSION=2.27-r0 \
    GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc \
    LANG=C.UTF-8

RUN set -ex && \
    apk upgrade --update && \
    apk add --update \
        bash \
        procps \
        curl \
        tar \
        perl \
        perl-utils \
        perl-app-cpanminus \
        make \
        git \
        gcompat

ENV PERL_PATH=/perl/
ENV PERL5LIB=$PERL_PATH:$PERL_PATH/lib/perl5:$PERL5LIB
RUN cpanm --notest -l $PERL_PATH \
        Archive::Extract \
        Archive::Zip

# common for all images
ENV MAVEN_HOME /usr/share/maven

COPY --from=maven:3.9.6-eclipse-temurin-11 ${MAVEN_HOME} ${MAVEN_HOME}
COPY --from=maven:3.9.6-eclipse-temurin-11 /usr/local/bin/mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY --from=maven:3.9.6-eclipse-temurin-11 /usr/share/maven/ref/settings-docker.xml /usr/share/maven/ref/settings-docker.xml

RUN ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn

ARG MAVEN_VERSION=3.9.6
ARG USER_HOME_DIR="/root"
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

RUN git clone https://github.com/Susucre/mage.git
WORKDIR /mage
RUN git fetch
RUN git config --global user.email "not@relevant.com"
RUN git config --global user.name "noname"
RUN git checkout origin/master

WORKDIR /mage/Utils
RUN perl build-and-package.pl

```

(Then I extract the mage-bundle.jar and use it in another docker)

My current workaround is to remove everything about the what's new button. Since everything else is compiling correctly, I do suspect a mis-configuration on xmage's side, not the docker.

**Comment by xenohedron** [comment]
I don't think the "what's new" page is worth adding javafx back as a dependency. Removing javafx was a good call and it should be removed again.

**Comment by JayDi85** [comment]
Nope, it was bad. No more removes.

**Comment by xenohedron** [comment]
> Nope, it was bad. No more removes.

I don't understand your point.

**Comment by JayDi85** [comment]
Release files must be build with oracle's java 8 (xmage's default java) or another distr with javafx like zulu.

Here are fully workable docker image and script to build release files on linux systems. Warning, it's just a proof of concept and not production ready.

How-to use:
1. Prepare machine with 4GB memory and installed [docker](https://docs.docker.com/engine/install/) (it's a minimum system requirements to build project);
2. Create working folder for docker and temp files:
  * `mkdir /xmage`
  * `cd /xmage`
3. Create project builder as `Dockerfile`:
  * `nano Dockerfile`
  * insert docker file content and save

``` dockerfile

FROM odinuge/maven-javafx:3-jdk-8

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

# additional tools
RUN apt update && apt install -y \
                    build-essential

RUN echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

WORKDIR /mage
ENTRYPOINT ["/bin/sh", "-c"]
```

4. Make sure no temp files exists (on second+ running):
  * `rm -rf temp`
  * `echo temp > .dockerignore`
4. Build docker image:
  * `docker build -t mage/builder .`
5. Clone repo to temp folder:
  * `docker run --rm -it -v "$(pwd)/temp":/mage mage/builder "git clone https://github.com/magefree/mage.git ."`
6. Build project and put prepared zip-files in `temp/deploy` folder:
  * `docker run --rm -it -v "$(pwd)/temp":/mage mage/builder "make install"`
7. All done, files ready:
* ![shot_240827_230338](https://github.com/user-attachments/assets/287cf252-81a6-48ce-a493-3f3edbce4bb1)

P.S. Parent docker image already has maven and all needed tools. Also it contains perl, but without exported archive/extract and other features (it required by perl build script). That's why I used make tools instead, but it can be modified to use perl too (see old docker script above `cpanminus` install).

**Comment by Grath** [comment]
But why do we need to go back to having a dependency on JavaFX in the first place? This adds complexity to building, releasing, and developing (it broke my ability to compile within IntelliJ, because I don't have JavaFX in the SDK in IntelliJ) for a very tiny upside (opening the "what's new?" page inside the client on some systems, rather than a browser window - but it's broken on Macs so it opens in a browser window there.)

**Comment by JayDi85** [comment]
> it broke my ability to compile within IntelliJ

Use oracle’s jdk or openjdk 11+ like adoption/temurin. No needs in pom or source file changes, it’s fully compatible.

**Comment by JayDi85** [comment]
Closed due workable scripts above.

For devs: if some build tools failed on diff IDEs, OSes, JDKs or environments then report new issue about it to find a possible solution.
