### ISSUE TITLE
PLEASE FIX

### ISSUE THREAD

**Issue by evanmorici** [magefree/mage#1273]
I played a land card (Inkmoth Nexus). You're supposed to pay the cost to activate the ability. The land then becomes a 1/1 creature with flying and infect. When I pay the cost during my mainphase, It tries to tell me that in order to attack with the card, it has to have haste. The creature does not have to have haste in order to attack because it's not being summoned. Please fix this. I cant run my Infect deck because of this problem. My Infect Deck relies on that card. Please fix this issue!!!!

**Comment by hanasu** [comment]
I can't replicate this issue. You definitely can't attack with a Nexus the same turn that it was played. I think that might be what happened in this case since the error mentions haste. Did the creature have chains on the card image at the time?

Relevant Gatherer rulings:
- If Inkmoth Nexus entered the battlefield this turn and it's not a creature, it can be tapped for mana. If it becomes a creature that turn, it can't attack or be tapped for mana.
- If you've controlled Inkmoth Nexus continuously since your most recent turn began and it becomes a creature, it can attack or be tapped for mana.

**Comment by hanasu** [comment]
Do you have any more info about the game state or the permanents in play? I think it's unlikely that no one would've mentioned this bug since the card is played so often.

**Comment by LevelX2** [comment]
I close this because it's probably a rule misunderstanding.
And by the way I don't like those headers.
