### ISSUE TITLE
Single-Choice options don't auto-select

### ISSUE THREAD

**Issue by Dunkoro** [magefree/mage#12784]
There's some single-choice options that simply do the choice for you if it's mandatory and there is a single option available.
The simplest example is when you Inquisition of Kozilek your opponent and they only have a single card that has MV<4.

Another example would be Devourer of Destiny cast trigger selecting a target right away if there's only a single coloured permanent on the board.

Why don't more things work this way? For example, when Thought-Knot Seer. Why not have the trigger to target the opponent in a 2-player game be put on the stack immediately as well? This applies to both the enters and the leaves trigger.

**Comment by JayDi85** [comment]
There are different dialogs with diff implementation:
- ability choose dialog (transparent window);
- pick choice dialog (choose card name, number, color, etc — dialog with search and/or text enter);
- feedback dialog (colored panel with yes/no, done/cancel buttons);
- target choice dialog (feedback dialog + clicks on battlefield objects/cards);

Some dialogs can force to show a single option by design — so users will not misclicks on wrong condition. Example: target choice for “up to” option, cast multi-modes spell, mana in non lands, etc.

Make sure you enabled full auto-choice mode in Preferences - main tab. By default it ignore some auto-choices.

**Comment by JayDi85** [comment]
> [[Thought-Knot Seer]]
> For example, when Thought-Knot Seer. Why not have the trigger to target the opponent in a 2-player game be put on the stack immediately as well? 

I don’t test but full auto-choice mode must process it.

**Comment by JayDi85** [comment]
[[Thought-Knot Seer]]

**Comment by xenohedron** [comment]
A likely root cause of failure to auto-choose targets is an improperly implemented 'possibleTargets` method that is more permissive than `canTarget`.
