### ISSUE TITLE
Emerge off Herigast not working properly

### ISSUE THREAD

**Issue by TamJams** [magefree/mage#12841]
I was trying to cast Artisan of Kozilek by sacrificing Herigast, Erupting Nullkite to the emerge cost, so Artisan would be free.  Artisan was highlighted in my hand as if I could cast it, but when clicking it nothing would happen, no prompts to pay cost or anything.  Once you begin casting something for emerge, losing Herigast shouldn't be a problem so I believe it should work.

I also had a scenario where I was attempting to flash in Liberator, Urza's Battlethopter by using the emerge cost from Herigast, I would click Liberator, it would go to the stack and when I'd click on which creature I wanted to sacrifice, if it was more Mana Value than Liberator, Liberator would go back to hand and the casting would stop.

**Comment by TamJams** [comment]
I think the issue is only happening when I would pay 0 (or "less") for the emerge cost

**Comment by TamJams** [comment]
label:bug

**Comment by JayDi85** [comment]
[[Artisan of Kozilek]] [[Herigast, Erupting Nullkite]]  [[Liberator, Urza's Battlethopter]]

**Comment by Grath** [comment]
The problem here was that it was triggering the check in https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/AbilityImpl.java#L321 because the manaCostsToPay() was empty as was getCosts() - so if the Emerge cost reduction reduces the manaCostsToPay() to be empty, I set 'noMana' to true to bypass that check,.

**Comment by JayDi85** [comment]
Yes, it's fine fix for Emergy ability. I just checked it for other abilities with same code usage -- only emergy reduces cost by itself.
