### ISSUE TITLE
Unable to connect, server is likely offline

### ISSUE THREAD

**Issue by dedebr6** [magefree/mage#1291]
I get this error everytime i try to connect to any xmage server. Someone, please, help me
![xmage error](https://cloud.githubusercontent.com/assets/14840336/10106485/fc72caf6-63ac-11e5-9cc9-f1e03ce72003.png)

**Comment by LevelX2** [comment]
No server is online, currently 338 people.
Seems to be a problem on your system.

Firewall, Anti-Virus?

**Comment by hanasu** [comment]
Can you ping xmage.de or any of the other servers? Try posting a traceroute to one of those domains.

**Comment by nino32bis** [comment]
i get this every time i try to conect to server, since i get v1.4.5. please help me.
![1](https://cloud.githubusercontent.com/assets/14889376/10163740/4dbe81da-668b-11e5-9199-0198957a2d2e.jpg)
![2](https://cloud.githubusercontent.com/assets/14889376/10163745/55497fa4-668b-11e5-9d76-3a7fa56d7d25.jpg)

**Comment by LevelX2** [comment]
1.4.5v0 was reverted so no 1.4.5 version is running on the public servers.
You have to update again (push update button in launcher) to go back to 1.4.4v7 now.
