### ISSUE TITLE
Sunken Hollow is misnumbered, gets replaced with Spawning Beds

### ISSUE THREAD

**Issue by elrondurpg** [magefree/mage#1319]
If you put a Sunken Hollow in your deck, it ends up misnumbered in the .dck files and when you load into a game, it gets replaced with Spawning Beds.

**Comment by fireshoes** [comment]
LevelX: Delete all files in your client DB file [mage-client]/db/. Restart the client, connect to a server to get the db and load and resave your deck after. Probably you have a wrong collectors number in your client DB for Sunken Hollow because Sunken Hollow had a wrong collectors number as it was added to XMage but it's corrected meanwhile.

**Comment by LevelX2** [comment]
Fixed now with raised CardRepository CARD_DB_VERSION number.
