### ISSUE TITLE
Issue with flip planeswalkers and clever impersonator

### ISSUE THREAD

**Issue by rasmuskolding** [magefree/mage#1331]
So I copied Jace, Vryns Prodigy with Clever Impersonator (it was tapped and I needed a blocker for a token...), and Jace got to survive until the next turn. When I looted, he flipped, and I got an error message I couldn't get rid of, forcing me to concede. I'm not sure what the correct outcome is rules-wise.

**Comment by emerald000** [comment]
Correct outcome:

Jace, Vryn's Prodigy copy enters the battlefield and you choose one to keep. Let's say you keep the copy. Then once you activate it, you will loot and the copy gets exiled. Clever Impersonator will then come back on the battlefield untransformed (since it is not double-faced) and will be able to copy something else.

**Comment by LevelX2** [comment]
Fixed.
