### ISSUE TITLE
Historical Standard needs update

### ISSUE THREAD

**Issue by StephenMilone** [magefree/mage#1370]
https://github.com/magefree/mage/blob/e9dbfba7466f4c00bfe231dec99cb5f1f575ca71/Mage.Server.Plugins/Mage.Deck.Constructed/src/mage/deck/HistoricalStandard.java

Is missing the latest standard sets, 22nd-28th standard as per the website referenced at the top comment.

And is also missing Chronicles in the standards it was legal (Standard 2 & 3)  The comment says chronicles is included, yet the set isn't in the array.  And also when using the deck editor, chronicles editions don't seem to be an option for cards

Just learned of this format and am eager to play it, but this is a hold up as i want to play 2nd standard, thanks

**Comment by PalladiaMors** [comment]
Also, if at all possible, please change the format's name to "Historical Type 2" or anything else that prevents people from confusing it with normal Standard and joining games by accident. People who play the format regularly know that this has been an issue since it was implemented and it's actually getting in the way a lot. Thank you very much!

**Comment by LevelX2** [comment]
Added Chronicles. 22nd-28th sets are added generic and were not missing.
Renamed format to "Historical Type 2".
