### ISSUE TITLE
Persist doesn't work with Dromoka's Command "counter + fight"

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#1386]
I had a kitchen finks with a -1/-1 counter on it from a previous persist. I played Dromoka's command, putting a +1/+1 counter on the finks (so it cancels out the other one) and fought a creature. Kitchen finks did not persist, even though it died without a -1/-1 counter on it

**Comment by fireshoes** [comment]
The canceling out of +1/+1 & -1/-1 counters is done when state-based actions are checked, which is after the all of Dromoka's Command has resolved, not as each mode resolves. Since the Kitchen Finks died in the fight, it uses it's last known information to see if it persists. At the time it died, it had both a +1/+1 & a 1/-1 counter on it, so it does not persist in this case.

**Comment by Zorkony** [comment]
Kitchen Finks doesn't die in the fight, it dies because of state based actions because he has more damage marked on him than his remaining toughness? When that state is cheched, why aren't the counters checked too?

**Comment by fireshoes** [comment]
The state based actions all happen at the same time, so after the spell resolves for a brief moment, the Kitchen Finks is on the battlefield with a +1/+1 counter, a -1/-1 counter, and lethal damage. The next moment, it is in the graveyard with no counters at all. Persist has to look back to see how the Finks appeared on the battlefield (Last Known Information). Since when it was last on the battlefield, it had a -1/-1 counter, Persist doesn't trigger.
