### ISSUE TITLE
Zulaport Cutthroat doesn't trigger when it dies.

### ISSUE THREAD

**Issue by Filar** [magefree/mage#1426]
Zulaport's ability doesn't trigger when it dies. I'm not sure if that's always the case, but I've encountered that bug at least several times today.

**Comment by LevelX2** [comment]
I can't reproduce that problem.

Can you describe more in detail what happens before the bug happens?
How did the Zulaport Cutthroat die exactly?

**Comment by Filar** [comment]
[20151220_011920_Two Player Duel_1.txt](https://github.com/magefree/mage/files/67650/20151220_011920_Two.Player.Duel_1.txt) this an example gamelog. I've got two Cutthroats on the battlefield, sac one of them, only one of them triggers (should be two).

**Comment by LevelX2** [comment]
It's reproducable but hard to fix. It's on my list.

**Comment by diogovk** [comment]
It happened to me as well when sacrificing it.

**Comment by diogovk** [comment]
I implemented the faling test at
https://github.com/diogovk/mage/commit/041bd84b5319fddff8d9a72adb2f9560fe0ce713

I'll try to discovery why the ability isn't being triggered in this case.

**Comment by LevelX2** [comment]
Tests are already included in the https://github.com/magefree/mage/blob/121f40c019dcf1b390845b9998f89bb7232a74e8/Mage.Tests/src/test/java/org/mage/test/cards/triggers/dies/BloodArtistTest.java class and set to @ignore.
I already analysed the problem and that is no simple fix, because the handling of zone-change triggers (603.6) is not implemented in all parts correctly. Probably we need an additional way to save some information about LKI of objects to handle this correctly.
