### ISSUE TITLE
Suspend cards should not be castable from graveyard/top of library/exile for {0}

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1510]
Ancestral Vision has no casting cost (this is different to a casting cost of {0}).
Snapcaster Mage, for example, is able to give it flashback whilst it is in the graveyard.

However the controller should not be able to cast Ancestral Visions from the graveyard for {0} mana.  
Have confirmed in the test mode that this is the same for the following:
Restore Balance, Living End,Wheel of Fate, Hypergenesis

This may also be a problem for say Future Sight (even though Ancestral Vision is the top faceup card, it should not be able to be cast for {0} mana).

**Comment by spjspj** [comment]
Sorry, but have confirmed that this is also a problem for Future Sight/Melek, Izzet Paragon/Magus of the Future.

**Comment by LevelX2** [comment]
What's with effects that allow to play cards from exile?

**Comment by spjspj** [comment]
Good point!  I'm guessing Chandra, Pyromaster's +0 ability is broken and will look into it!  Also, I realised that lands get caught in the cardOnTop.getManaCost().isEmpty() clause and so can't be cast with Future Sight et al which is kind of unintended so will resubmit something for that.

**Comment by drmDev** [comment]
A reddit user reported that Ancestral Visions can still be flashed back with flipped Jace:
https://www.reddit.com/r/XMage/comments/4f6dun/bug_with_av_und_lil_jace/

**Comment by spjspj** [comment]
The change that LevelX2 did looked pretty good and I think I tested at the time that you couldn't cast it if you for example used Snapcaster mage to give if flashback.  Jace, Telepath Unbound's -3 doesn't give it flashback :( 

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=398434

−3: You may cast target instant or sorcery card from your graveyard this turn. If that card would be put into your graveyard this turn, exile it instead.

**Comment by drmDev** [comment]
Ah... that is an important difference. Looked up rulings:

"It's a legal target, since Jace's ability only requires an "instant or sorcery card in your graveyard" as its target.

It would, however, be a waste of the ability's use, because you still cannot actually cast Ancestral Vision this way. Jace's ability essentially gives you permission to cast the targeted card from an unusual place (the graveyard) that you normally cannot cast cards from. But since the ability doesn't say anything about not paying the cost for the spell, you still have to pay normally. Paying normally involves paying the mana cost of the card. But since Ancestral Vision does not have a mana cost, you cannot pay it, and the end result is that you cannot cast it, for the same reason that you normally cannot cast it from your hand."
http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/652878-jace-telepath-unbound-ancestral-vision

**Comment by drmDev** [comment]
I know this has been a while, but is this issue still occurring? Difficult to tell from this. Or what specific issue is still occurring here now since I believe some of these are fixed at the very least.

**Comment by spjspj** [comment]
I believe that casting them from exile may still be an issue (but I haven't looked at it for a while!)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

You can often "try" to cast them, and click on the "draw three cards" mode, but it will never actually cast the card.

Tested with:

Jace, Vryn's Prodigy
Chandra, Torch of Defiance
Snapcaster Mage
Future Sight
Covetous Urge
