### ISSUE TITLE
Mycosynth Lattice floating mana is unintuitive to use

### ISSUE THREAD

**Issue by wxyangf** [magefree/mage#1544]
I was trying to activate Sydri, Galvanic Genius with a floating {C} targeting a mountain when I clicked on the <> icon it wouldn't spend the mana.
[20160219_172846_Commander Free For All_1.txt](https://github.com/magefree/mage/files/138863/20160219_172846_Commander.Free.For.All_1.txt)

**Comment by LevelX2** [comment]
I can't reproduce the problem. When in the game log does this problem happen?

How does this {C} mana go to the mana pool?

**Comment by William-Shadowruby** [comment]
Around 00:00 when I start killing lands with Sydri, the floating mana was from a Sol Ring.

**Comment by William-Shadowruby** [comment]
In a similar issue when I was trying to cast Sydri from my command zone with floating mana I was not able to do so.
![xmage float mana glitch](https://cloud.githubusercontent.com/assets/2058629/13509004/662e9dd0-e157-11e5-80bc-1ce8825ffa01.PNG)

**Comment by William-Shadowruby** [comment]
Ok, I figured out what was messing with me, Mycosynth Lattice functions but in an odd way. When you have colorless mana floating you can't click on it to pay colored costs. But if you click on the corresponding symbol for the type of mana you are trying to spend it works. This should probably be changed because its far more intuitive to click on the symbol with floated mana next to it.

**Comment by drmDev** [comment]
The issue here is the floating mana shows up under colorless and you must spend it by clicking on the colored mana symbols you need (which do not have any floating mana number next to them). Perhaps a prompt that indicates you need to click on the colored mana symbols?
