### ISSUE TITLE
Don't consider matches conceded after 1st game as quitting

### ISSUE THREAD

**Issue by guifig** [magefree/mage#1554]
I noticed that, if I concede a match after losing game 1, I still get a "quit" counter. Could you make it so that doesn't happen?

**Comment by LevelX2** [comment]
Why do you concede a match if you lose the first game?
If there is a second game, you are still able to win the match if you have sufficent amount of time.

1) Maybe we should make it dependent from the time left.
2) Or if your opponent agrees to your concede.

Because on the otehr hand it's always a bit frustrating e.g. to do a draft, build the deck and the opponent concedes immediately after having a bad draw or whatever.

**Comment by guifig** [comment]
What I mean is that you might click "concede match" after losing game 1 and having an unwinnable board state (be it either lethal on board, or any other reason).  This would be counted as a quit, even though you played 2 games and lost them.

**Comment by Mike-NetCode** [comment]
Imo just don't do it, press F4 and let your opp do his job to finish you off.
Creating exceptions such as LevelX2 proposed will sooner or later lead to abuses as exceptions like this are abusable. 

I noticed that as XMage gets popular and popular more assholes are popping out regularly quitting the games. Nobody cares about Quit counter so far because 95% of the games allow 100% quit and there is no way to kick anyone from lobby. Also there's no min number of games filter so you can keep creating accounts over and over.

**Comment by drmDev** [comment]
I'm not a fan of the conceding of the final game in a match being part of the quit percentage myself. Like I was playing modern hexproof against some enchantment prison deck. I don't even know what its win condition was, but I was never going to be able to get through a Pithing Needle on my only spell to destroy enchantments plus his board of Pay X to attack for each creature (Ghostly Prison, Sphere of Safety, etc). You're right I could just keep the window open for a few minutes and skip all my turns to let my opponent kill me - but what's the point of that? I am forced to stay in the game longer when I have no chance of winning just to avoid having it come off as a Quit. Plus the current way is just as "abusable" - it just happens to also make it more frustrating for the person who knows they lost the match. I played my games up until the point where I no longer have a chance to win - I should not have this lumped in the same category as someone who drops out of a tournament mid draft, during deck building, or concedes the match at the start of game 1.

**Comment by LevelX2** [comment]
We will add for sure a number of minimum matches a player has to be played to be able to join a table. This can be set from 0-100 for example.

**Comment by Zerrisx** [comment]
Closing this as not having any actionable items that need to be fixed or addressed, and offering no clear justifications for being an enhancement over current behavior.
