### ISSUE TITLE
Can't cast the creature you returned from reflector mage.

### ISSUE THREAD

**Issue by Tommygunzs** [magefree/mage#1673]
If you return a creature an opponent controls from reflector mage and you want cast the same card returned, it wont let you. It should let you cast the creature as reflector mage states the creatures owner can't cast the creature with the same name, not any player can't play the creature with the same name.

**Comment by fireshoes** [comment]
There was an update to Reflector Mage that went live with 1.4.9v3, which was released today. Are you using that version or an older version?

**Comment by Tommygunzs** [comment]
was using the newest client 1.4.9v3, i returned my opponents bygone bishop,
then I had one in my hand, and I could not cast it that turn.

**Comment by drmDev** [comment]
If I'm understanding the issue correctly, Reflector's Mage rule text is: 
"When Reflector Mage enters the battlefield, return target creature an opponent controls to its owner's hand. That creature's owner can't cast spells with the same name as that creature until your next turn." However, what is happening is NO ONE can cast spells with the same name as creature, instead of just the owner of the creature returned to hand. Let me know if I misunderstood @Tommygunzs

**Comment by Tommygunzs** [comment]
correct, I could not cast the creature I returned to my opponents hand.

**Comment by drmDev** [comment]
I believe I have this issue resolved - I want a second look and ideas for more tests on it to confirm:
https://github.com/magefree/mage/pull/2055

**Comment by drmDev** [comment]
fixed with commit 16ce1771434906f0a6bcfdb8a78b64991fb2cdd1
