### ISSUE TITLE
[SOI] Sealed pool generation

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1727]
Reported bug on forums: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=18297&start=120
"Only 5 rares showed up in the 6 SOI sealed pool. Something might be off with pack generation."

Screenshot
http://imgur.com/qyLWxJb

Might just be related to there being some cards still not implemented, but not sure.

**Comment by fireshoes** [comment]
A couple more screen shots from today with too many rares.
![sealed rares](https://cloud.githubusercontent.com/assets/8553747/14215797/e201c4ea-f80a-11e5-8261-c11eee52c2bb.jpg)
![sealed rares 2](https://cloud.githubusercontent.com/assets/8553747/14215802/e6050d4a-f80a-11e5-8907-bd310d5345bb.jpg)

**Comment by LevelX2** [comment]
Seems like it's caused by the Transformable cards. Each booster gets one additional transform card. That can also be rare. But is that correct behaviour?

**Comment by fireshoes** [comment]
Oh yeah, I guess my extra ones were transformable so in that respect the quanity of rares was correct. Not sure on the pool with 5 rares. Some changes for SOI booster generation do need done though, because now you can have 2 Double-Faced Cards in one pack. In most packs, it is one DFC (a common or uncommon DFC replacing a regular common). Every 8th pack will have an additional DFC (a rare or mythic rare replacing a regular common).

**Comment by fireshoes** [comment]
An additional report of missing rare from pack.
http://www.slightlymagic.net/forum/download/file.php?id=25223&t=1

**Comment by LevelX2** [comment]
Hmm still no idea how only 5 rares can be added.

**Comment by fireshoes** [comment]
Maybe duplicate card number?

**Comment by LevelX2** [comment]
Good idea, i'll check that

**Comment by LevelX2** [comment]
Checked the numbers, seems to be all correct

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

Generated six sealed pools and opened 108 packs without any missing rares (though I did get extras due to flip cards).
