### ISSUE TITLE
[SOI] Avacynian missionaries hover text contains java code.

### ISSUE THREAD

**Issue by strigonLeader** [magefree/mage#1731]

**Comment by drmDev** [comment]
![avacynian java text](https://cloud.githubusercontent.com/assets/11060241/14175440/f4aeddaa-f718-11e5-85b5-2ea34e026d36.png)

**Comment by drmDev** [comment]
Card uses `BeginningOfEndStepTriggeredAbility(Zone zone, Effect effect, TargetController targetController, Condition interveningIfClauseCondition, boolean isOptional)` with the likely line in question:
`this.addAbility(new BeginningOfEndStepTriggeredAbility(Zone.BATTLEFIELD, new TransformSourceEffect(true), TargetController.YOU, new EquippedCondition(), false));`

So the issue is somewhere in the EquippedCondition class. Looking into it now.

**Comment by drmDev** [comment]
Not sure what is causing this issue. I must be missing something small.
