### ISSUE TITLE
[SOI] Jace, Unraveler of Secrets goes to the graveyard when it resolves

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#1775]
Hello,

Why is this happening? Whenever I resolve this Jace, it goes immediately to the graveyard.

**Comment by fireshoes** [comment]
drmDev:
Resolved beyond v4. Duplicate #1692

Actually this one should even be resolved in v4 - the xmage.de server is the only one updated to v4. Woogerworks still is not (last I checked at least). That may be the issue here. Either way, tested and this issue is confirmed resolved with the current code.
