### ISSUE TITLE
i cant connect to xmage

### ISSUE THREAD

**Issue by todd1019** [magefree/mage#1788]
my laucher keeps freezing at saying connecting but the console comes up with these errors. any suggestions to fix it?

FATAL 2016-04-05 23:46:06,051 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
FATAL 2016-04-05 23:47:06,249 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
FATAL 2016-04-05 23:48:06,157 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
FATAL 2016-04-05 23:49:06,332 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException

**Comment by spjspj** [comment]
Have you been able to connect since?

**Comment by ianelletson** [comment]
This is happening to me as well, suddenly after having been able to connect and play fine for days.

**Comment by albuzs** [comment]
Happening to me as well ):

**Comment by todd1019** [comment]
its doing the same thing again

**Comment by fireshoes** [comment]
I was disconnected at ~4:30am CET and was unable to reconnect for quite some time. Have been able to reconnect now about 20 minutes later and only 72 users on. Disconnected twice with a couple of minutes though.

**Comment by fireshoes** [comment]
One thing I have persistently noticed, when disconnects happen, the client gets confused about whether it is connected or not. In the image, it is shown asking "Are you sure you want to disconnect?" but the client is not connected (notice the menu option Connect rather than disconnect). Alternatively it could be that it is connected, but does not let you go to the lobby or games.
![confirm disconnect](https://cloud.githubusercontent.com/assets/8553747/14481586/0e4d46b2-00fa-11e6-98e1-8539f3dcddb4.jpg)

**Comment by FastTadpole** [comment]
Ditto. Same issues as fireshoes same NullPointerException as todd1019. GUI hangs at connecting while the NullPointerException is happening. Issue persists on multiple servers.

**Comment by LevelX2** [comment]
True I can confirm this confusion too. 
I'll try to look into it but that network implementation isn't always so straight forward.
