### ISSUE TITLE
Oubliette does not return exiled creature with counters on it

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1842]
Oubliette oracle text:
"When Oubliette enters the battlefield, exile target creature and all Auras attached to it. Note the number and kind of counters that were on that creature.
When Oubliette leaves the battlefield, return that exiled card to the battlefield under its owner's control tapped with the noted number and kind of counters on it. If you do, return the other exiled cards to the battlefield under their owner's control attached to that permanent."

The tooltip text does not reflect the Oracle text either. Looking at the code, all it does is exile a creature and then return the creature if Oubliette leaves the battlefield - so all the parts of Oubliette dealing with exiling Auras attached to it, and returning the creature with the Auras and counters are not doing anything.

Simple test:
Give +1+1 counter to a creature with the spell Battlegrowth
Exile creature with Oubliette
Disenchant the Oubliette
Creature returns without +1+1 counter on it.

**Comment by Marco-Marin** [comment]
Fixed it.
Still going to figure out the counters, but I think I got a solution.
The auras and the tooltip should be fixed tho. With 1 caveat. All the static text is set on the entering the BF ability. The leave the BF ability is added dynamically and no text is set. The user should test and see if this is enough.

Going for counters now.

**Comment by Marco-Marin** [comment]
Fixed. Tho as you'll see, I'm not very comfortable with the solution. Yet, the permanent should still be around while this effect resolves, so the data should still be available. And I do check for null, so no NPE this time (at least not for this reason, lol)
Going for a pull request now.

**Comment by drmDev** [comment]
Have you gotten to try out the manual testing "cheats"? Or taken a look at
automatic testing? You should be confident this is likely to resolve the
issue just by testing the change

**Comment by Marco-Marin** [comment]
I was hoping to get a new card coded as guinea pig to motivate learning about that. Oubliette seemed too urgent (I don't know how long I'm going to take to get to it). Feel free to ignore the request.

**Comment by Marco-Marin** [comment]
hmm.. I have no idea how to "cherry pick" the Oubliette one, since the ATQ commit is under scrutiny (that's ok :)). Maybe you can just check it out in my repo and copy it over, if you feel its urgent enough to call for it? I'm going to try and learn about the testing process.

**Comment by drmDev** [comment]
It's by no means urgent. It won't be able to be released until whenever the
next version is being pushed out. I understand Oubliette will be a
difficult card to complete, so whenever you have some time to devote to it,
go for it. Nonetheless, please do test your cards and fixes.

On Mon, Apr 11, 2016 at 2:10 PM, Marco-Marin <notifications@github.com>
wrote:

> hmm.. I have no idea how to "cherry pick" the Oubliette one, since the ATQ
> commit is under scrutiny (that's ok :)). Maybe you can just check it out in
> my repo and copy it over, if you feel its urgent enough to call for it? I'm
> going to try and learn about the testing process.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/magefree/mage/issues/1842#issuecomment-208481940>
>



-- 
Derek Monturo

**Comment by Marco-Marin** [comment]
Good news. Managed to figure out the testing set up. \o/
Furthermore, thanks to the latest post on the bug thread, which mentions a "debugger", figured out I could as well use it :)

 Discovered that my suspicion was right in that my code isn't able to get the target of oubliette. It seems to not yet be set, even though the game has already asked for it.
Would you give me a hand here? I'm using getFirstTarget() from Ability, iterating through them all, it does get to the triggered one but don't find a target. I inspected inside modes but couldn't find it there either (maybe didn't look thoroughly?), but I'd guess getFirstTarget() should get a target regardless (specially since it doesn't use modes here, well, you know, more than the default)

Should I get the stack instead to get to it?

**Comment by Marco-Marin** [comment]
Yes. got it. :) Sry to 'bug', now things will roll smoother...

**Comment by Marco-Marin** [comment]
I need some help. Exiling works but returning doesn't. I can see it DOES get registered as an Ability in the card but it isn't triggered.

I "copied" the effect from Flickerform and it registered directly on the game object, but I can't do that here because it isn't a "at Phase" trigger but depends on the permanent leaving.

**Comment by kevinwshin** [comment]
I didn't fix this, but I did just test it as part of another issue, and it seems to work just fine.
