### ISSUE TITLE
Yawgmoth Demon not working

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1918]
[Yawgmoth Demon](http://magiccards.info/query?q=%21Yawgmoth+Demon)'s upkeep ability doesn't do anything, at least if you control no artifacts.

**Comment by LevelX2** [comment]
Sorry adidn't check the Assignee .

**Comment by Marco-Marin** [comment]
Thanks LevelX2, but I'm confused by this fix.
the "sacrificed = true" is inside the if where I check where no artifact exists for sacrifice ( <1) or if the player chooses not to (!chooseUse).
How does this work?

**Comment by LevelX2** [comment]
Hmm, the boolean is set to false on init and only set to true, if an artifact was sacrificed.
So it seems very straight to me.
So the effect happens if you can't sacrifice or if you don't liek to sacrifice.

Where do you see a problem?

**Comment by fenhl** [comment]
I have tested this on master and it's still not working. If I control an artifact and answer “yes”, Yawgmoth Demon becomes tapped and deals damage. If I answer “no”, I have to choose an artifact to sacrifice.

**Comment by Marco-Marin** [comment]
> Where do you see a problem?

the if I coded was checking if there were no artifacts (<1), so it wouldn't be possible to sacrifice any (inside the if), but the boolean was inside the if.

Here is how I thought about it originally:

Count how many artifacts, if there isn't any, the IF would be true (short-circuit the choice) and damage would be caused.

Anyways, yours solution plus Fenhl last tweak basically inverted that IF (meaning, you guys coded the "else" clause from before inside the if, and "my" if now is the else clause.. in case you wanna remove the boolean altogether :)).

What I believe was happening was the call to:
 "SacrificeControllerEffect(new FilterArtifactPermanent(), 1, "").apply(game, source))"

.. was always returning false, since the choice was short-circuited by having no artifacts to choose from (so there was nothing to sacrifice or filter).

Then the other IF(where the damage was applied), never got a change to happen.

It seems correct now tho : ) thanks guys.

**Comment by LevelX2** [comment]
Yep, logical change. Sometimes your routine-blinded.
Thanks for fixing it.
