### ISSUE TITLE
Permanents get exiled when controller leaves the game

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1929]
When a player leaves the game, a permanent owned by other players but controlled by the player who left should be returned to the control of the player who previously controlled it, unless it entered the battlefield under the control of the player who left. However, in XMage, it is always exiled. Comprehensive Rules source:

> **800.4a** When a player leaves the game, all objects (see rule 109) owned by that player leave the game and any effects which give that player control of any objects or players end. Then, if that player controlled any objects on the stack not represented by cards, those objects cease to exist. Then, if there are any objects still controlled by that player, those objects are exiled. This is not a state-based action. It happens as soon as the player leaves the game. If the player who left the game had priority at the time he or she left, priority passes to the next player in turn order who’s still in the game.

**Comment by Dilnu** [comment]
I've taken a look at this. It appears that calling `this.getState().getContinuousEffects().apply(this);` in the game.leave method instead of `this.getState().getContinuousEffects().removeInactiveEffects(this);` would fix the problem. I'm not sure if that would cause other problems though.

In effect that would try to reapply all the gains controls effects and players who aren't in the game can't gain control of things. I haven't had a chance to test this. I might try to take a look the consequences tomorrow night.

**Comment by Zerrisx** [comment]
Should be considered when addressing #4472

**Comment by JayDi85** [comment]
All control effects must be fixed by 1e36b394345709ea31cde9c339471e5780de3422
