### ISSUE TITLE
Cards Leaving

### ISSUE THREAD

**Issue by Pixiedogg** [magefree/mage#2089]
do cards get taken out of the program sometimes i have noticed cards leaving decks

**Comment by fireshoes** [comment]
There were some set codes that were changed recently, so cards from those sets are loading from previously saved decklists. If you open the decklist file, you can change the set code there and it will load properly. Otherwise you can add the missing cards back in in the deck editor and save and it will work again.

Affected sets off the top of my head are From the Vaults: Legends (FVL->V11), Dragons (FVD->DRB), Exile (FVE->V09), and Relics (FVR->V10), Duel Decks Anthology: Divine vs Demonic (DD3A->DD3DVD), Elves vs Goblins (DD3B->DD3EVG), Garruk vs Liliana (DD3C->DD3GVL), and Jace vs Chandra (DD3D->DD3JVC), Premium Deck Series: Slivers (PDS->H09), and Nemesis (NMS->NEM).

**Comment by Pixiedogg** [comment]
ahh gotcha thanks alot for the help
