### ISSUE TITLE
Eldritch Moon: Spreading Flames calls wrong function in constructor in this.getSpellAbility().addTarget(...)

### ISSUE THREAD

**Issue by xmageForger** [magefree/mage#2099]
When you cast Spreading Flames, it asks to choose 6 target creatures.  

I believe this is the fix.  

In SpreadingFlames.java, in the constructor

      this.getSpellAbility().addTarget(new TargetCreaturePermanent(0,Integer.MAX_VALUE));

should be replaced with 

       this.getSpellAbility().addTarget(new TargetCreaturePermanentAmount(0, filter));

thought I don't know how to create the filter object.

**Comment by drmDev** [comment]
This should already be fixed in this commit:
910d6eb0480eeba40de7608de752ecba556486e2

Filter would not be right there - filter has nothing to do with the amount of creatures able to be targetted. The original code had "this.getSpellAbility().addTarget(new TargetCreaturePermanent(6));" which just means the minimal amount of targets would be 6. I changed it so it has a minimum of 0 and no maximum ("any number of target creatures").
