### ISSUE TITLE
Complete Turn Skipped

### ISSUE THREAD

**Issue by CodeGorger** [magefree/mage#2142]
Hello,

I was missing my turn and there is no way of avoiding this.

I needed a rollback, got it (to the start of the current turn). Then my opponent didn't get his turn (probably part of the bug), so I made a rollback (to the start of the previous turn). After that he did his turn 20. Turn 21 was also his. Again a rollback (to the start of the previous turn) ended in us playing the turn exactly the same way. He got turn 21 again.

We didn't play any cards manipulating the order of turns, skipping players etc.

Best Regards

**Comment by drmDev** [comment]
Likely related to all sorts of issues we see on rollback, parent issue at the moment: 2072

**Comment by Navyguy330** [comment]
yeah ever since the last 2 -3 updates xmage has went to shit.  first the visual bug where you get the old windows xp screen smearing effect and cannot even play unless your force quit.  happens like 2-5 times per GAME  (not just match) and this turn issue where if you rollback sometimes it just straight skips one of you and they get a free turn no matter how many roll backs you try.

**Comment by goesta** [comment]
I'll close this issue because it seems to be a duplicate.
