### ISSUE TITLE
Change time up behaviour in timed deckbuilding scenarios

### ISSUE THREAD

**Issue by Shantu58** [magefree/mage#2173]
I have been experiencing timer desynchronizations when building decks for draft or sealed games. The game starts when I still have more than a minute left on my timer, which means I have not yet submitted my deck. This wouldn't be a huge problem if the default behaviour wasn't to take **all** cards in your pool and slap a generous amount of lands on top of it. This results in 150+ sized decks which are basically an auto-loss due to mana flood.

The desync is likely caused by a slower laptop on my part. I can accept that and I suspect that would be a nightmare to debug. However, I believe the following would be a much more sensible behaviour when failing to submit a deck on time:
- Check legality (40 cards I guess?)
- If legal, submit that deck for the player
- If illegal, I guess you can always fall back to the current behaviour.

My reasoning is that decks are built incrementally - you dump lands into it, add cards and maybe change your mind on some. But especially as your deckbuilding time is coming to an end, you try to finalize the deck so that you can submit it as soon as you've made those final decisions. But whatever that final decision is, your deck is likely going to be legal already.

In each instance where I was blown out by this behaviour my deck had been legal and working when the timer ran out. This suggestion would, I believe, reduce the likelihood of this happening.

**Comment by fireshoes** [comment]
I've seen this on occasion as well.

**Comment by drmDev** [comment]
I like these ideas as a band-aid for the timer synchronization issues we occasionally hear about.

**Comment by sprangg** [comment]
I was about to report this as a common newbie pitfall, but seems like there's this older issue about this already.

The expected behavior, when running out of deck submitting time, is that the deck will get submitted if it's legal (40+ cards). This would be consistent with how drafting works, where having a pick selected and running out of time drafts you the selected card.

In my first xmage draft a long ago, I fell into this submit trap and just witnessed two newbies do it this week.

**Comment by sprangg** [comment]
This is still causing feelbads when players let their timer go to 0 during deckbuilding and get an unplayable deck. Reverting this commit's changes to TournamentPlayer.java would fix things for the most part https://github.com/magefree/mage/commit/915651335a2d4b8020fea8318100892bdf9f1b02

However, would imo be best if the cards added to the deck automatically if the deck was below 40 cards would be basic lands instead of random cards from sideboard. Preferably basic lands that the deck needs (the auto land adding feature that the lands dialog has could used for this?)

**Comment by xenohedron** [comment]
Can be fixed by #10159
