### ISSUE TITLE
RegenerateAttachedEffect not working on abilities with SacrificeSourceCost

### ISSUE THREAD

**Issue by Derpthemeus** [magefree/mage#2221]
[RegenerateAttachedEffect](https://github.com/magefree/mage/blob/e2a8ddef0f299a94188ff5b3e0f108c2d9969166/Mage/src/main/java/mage/abilities/effects/common/RegenerateAttachedEffect.java) will not regenerate attached creature if used by an ability with SacrificeSourceCost. This seems to caused by the fact that the aura/equipment is no longer a permanent when the ability resolves because it has been sacrificed. Currently affects [Thrull Retainer](https://github.com/magefree/mage/blob/dff8c1ea4044cebf2477985bd885b36a21f6d4b4/Mage.Sets/src/mage/sets/fifthedition/ThrullRetainer.java) and would also affect (currently) unimplemented [Stamina](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=19868) and [Carapace](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=184777).

This issue may also affect other effects that target attached permanents

**Comment by cg5-** [comment]
I think using `getPermanentOrLKIBattlefield` instead of `getPermanent` when looking up the aura should fix it? That way it gets what was attached from the last known information. I searched for `SomethingSomethingAttachedEffect` `OneShotEffects`, most do use the LKI version but some ([AddCountersAttachedEffect](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/effects/common/counter/AddCountersAttachedEffect.java), maybe [SacrificeEquippedEffect](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/effects/common/SacrificeEquippedEffect.java)) does not. It's worth investigating if they're broken in the same way.

**Comment by spjspj** [comment]
Regeneration actually shouldn't work when you sacrifice a creature, unless I am missing something.

**Comment by Derpthemeus** [comment]
@spjspj the aura/equipment is the one being sacrificed

**Comment by JayDi85** [comment]
Fixed via 00411b4a9bddf045f4772c31709d31dbf2930b55
