### ISSUE TITLE
Card rendering - Token images missing

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2275]
![tokenimage](https://cloud.githubusercontent.com/assets/2066790/18551337/35fd3c48-7b58-11e6-9037-bfceb2a651a2.jpg)

The images of tokens are not taken correctly.

**Comment by stravant** [comment]
What did you use to make the thopter / do you have Kaladesh tokens downloaded / from where? The thopters from the card (Pia & Kiran) that I just tried worked fine.

It's also probably not an issue with card rendering specifically because I use the exact same image fetching code that the component based implementation uses, so it's probably broken there too.

**Comment by JayDi85** [comment]
@stravant , it's not broken. It is because http://tokens.mtg.onl haven't newly token's card like kaladesh or ixalan.

**Comment by JayDi85** [comment]
No more actual
