### ISSUE TITLE
'Dubious Challenge' (KLD) not Sequencing Properly

### ISSUE THREAD

**Issue by Frankinator2112** [magefree/mage#2421]
Sorcery
Look at the top ten cards of your library, exile up to two creature cards from among them, then shuffle your library. Target opponent may choose one of the exiled cards and put it onto the battlefield under his or her control. Put the rest onto the battlefield under your control.

XMage is having both creatures ETB simultaneously;
-This is what would occur if the opponent selected neither creature (both ETB under my control)
-When the opponent selects a creature card targeted by Dubious Challenge, said creature would ETB under the opponent's control, Then the other creature would ETB under my control.

The relevant "combo" would be targeting 'Hushwing Gryff' along with 'Eater of Days, Leveler, or Phage the Untouchable' thus ending the game immediately for Phage, on my opponents upkeep for Leveler, and hopefully before my opponent takes another turn for 'Eater of Days.'

I hope this was of help.

Thank you for developing otherwise amazing software.

**Comment by fireshoes** [comment]
From L2 judge on reddit for further info:
As a quick rules lesson for everyone: "trigger" doesn't mean "put onto the stack".

    603.2. Whenever a game event or game state matches a triggered ability's trigger event, that ability automatically triggers. The ability doesn't do anything at this point.

    603.2a. Because they aren't cast or activated, triggered abilities can trigger even when it isn't legal to cast spells and activate abilities. Effects that prevent abilities from being activated don't affect them.

    603.3. Once an ability has triggered, its controller puts it on the stack as an object that's not a card the next time a player would receive priority...The ability becomes the topmost object on the stack. It has the text of the ability that created it, and no other characteristics. It remains on the stack until it's countered, it resolves, a rule causes it to be removed from the stack, or an effect moves it elsewhere.

Because of these rules, an ability "triggers" whenever an event occurs, including during the middle of a spell resolving. The resulting triggered ability isn't added to the stack until the the next time a player receives priority.

In Scenario 1: Hushwing Gryff will be on the board in order to prevent abilities from triggering.
In Scenario 2: Eater of Days will enter, it's ability will trigger, and then the Hushwing Gryff will enter the battlefield. Hushwing Gryff will not prevent that trigger from being added to the stack however, as it's already triggered.
In Scenario 3: Well, the Gatherer rulings tell you all you need to know about that.
