### ISSUE TITLE
Eye of the storm only triggers when spell has been cast from hand.

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2684]
Bug on https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/e/EyeOfTheStorm.java#L104

Oracle text: Whenever a player casts an instant or sorcery card, exile it. Then that player copies each instant or sorcery card exiled with Eye of the Storm. For each copy, the player may cast the copy without paying its mana cost.

It doesn't trigger off a flashed-back instant.

**Comment by spjspj** [comment]
Fixed(?) via 9c6b9073a8167f0d1062c594a21272e3fb2bfdb7

**Comment by JRHerlehy** [comment]
The most edge case I can think of that you'd need to watch for is something like Spawnsire of Ulamog and All is Dust. Would that interact correctly with 'event.getZone() != Zone.OUTSIDE'? Not sure of other effects that are similar.

Maybe checking if the cast spell is an actual spell rather than a copy as Eye of the Storm generates? I don't have the ability to try this for a couple of days at the moment.
