### ISSUE TITLE
Setting basic land subtype.

### ISSUE THREAD

**Issue by ImperatorPrime** [magefree/mage#2957]
@emerald000 in particular, I'm trying to verify that we're doing the right thing for Blood Moon and Spreading Seas.

Changing the subtype to a basic land happens in layer 4, and as a direct result of that, all of the rules text on the card is also removed from the card, and it gains the "Add X to your mana pool" ability in that layer as well. In BloodMoon.java, SpreadingSeas.java, and SongoftheDryads.java, they all reference layer 6 to remove and add abilities to the card. If my understanding is correct (I'm unsure, thus the issue), then none of these cards should have any interaction with layer 6 at all. They should all be removing the abilities of the card and adding the mana ability at layer 4.

Relevant rule for context.

305.7. If an effect sets a land's subtype to one or more of the basic land types, the land no longer has its old land type. It loses all abilities generated from its rules text, its old land types, and any copy effects affecting that land, and it gains the appropriate mana ability for each new basic land type. Note that this doesn't remove any abilities that were granted to the land by other effects. Setting a land's subtype doesn't add or remove any card types (such as creature) or supertypes (such as basic, legendary, and snow) the land may have. If a land gains one or more land types in addition to its own, it keeps its land types and rules text, and it gains the new land types and mana abilities.

**Comment by emerald000** [comment]
Ugh layers.

Technically, abilities are added and removed in layer 6. The issue is that Blood Moon only removes abilities from the rules text, not from other effects. The current layers system implementation in xmage cannot determine where the effects are coming from though. By removing abilities before layer 6, you end up only removing the intrinsic abilities since the added abilities have not been added yet.

Unless there is an issue with some interaction, I wouldn't bother to try fix it correctly. There are bigger issues in the layer system right now, such as the dependencies being hard-coded and not being flexible for anything other than the most basic case.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/6236

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
