### ISSUE TITLE
Tromokratis is impossible to block

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#2995]
Self explanatory. Attempting to block just gives off the message "this creature can't be blocked". Pressing Done just leaves him unblocked.

**Comment by drmDev** [comment]
Do you have a log or more information on what happened here? There are cases where Tromokratis cannot be blocked:

http://gatherer.wizards.com/Pages/Card/Details.aspx?name=tromokratis
Tromokratis can't be blocked unless all creatures defending player controls block it. (If any creature that player controls doesn't block this creature, it can't be blocked.)

The defending player may block Tromokratis with each creature he or she controls. If that player can’t, perhaps because one of those creatures is tapped, or chooses not to, Tromokratis can’t be blocked.

------
I'll create tests for it, but I imagine one of these cases was why it was unable to be blocked ^

**Comment by drmDev** [comment]
Tests added in commit referenced above - unable to duplicate issue. Need game logs or manual testing to possibly duplicate or investigate further.

**Comment by drmDev** [comment]
Unable to duplicate issue with manual or automated tests
