### ISSUE TITLE
Aetherflux Reservoir life bug

### ISSUE THREAD

**Issue by arielcarralbal** [magefree/mage#3046]
Hi!
I detected that life calculation using the card "Aetherflux Reservoir" might be wrong.
Life gained for casting:
1st spell = 1 life
2nd spell = 3 lifes (1+2)
3rd spell = 6 lifes (1+2+3)
4rd spell = 10 lifes (1+2+3+4)

Actually, the game logs shows:
1st spell = 1 life
2nd spell = 2 lifes
3rd spell = 3 lifes 
4rd spell = 4 lifes 

Lifes are gained even if AR cast

Best regards,
AC

**Comment by thechucklingatom** [comment]
The games logs are correct, the card states Whenever you cast a spell, you gain 1 life for each spell you've cast this turn.

So spell one is the first spell you have cast, so you gain one life. The second spell you cast you will gain two since you have only cast two. If Reservoir is the second spell cast and you cast one spell after that you will gain three life since that is the third spell you have cast that turn.

**Comment by stravant** [comment]
Yes, the implementation looks correct to me. As stated above it's supposed to work that way.
