### ISSUE TITLE
Meld cards break Deck Editor and sometimes cause in-game crashes

### ISSUE THREAD

**Issue by YuanRamirez** [magefree/mage#3129]
When I was building a deck with hanweir Garrison in it I found the following issues. I later realized that this happens with all bottom halves of meld cards. So everything you're about to read is also true for cards like Midnight Scavenger or Bruna, the Fading Light.
--------------------

You can search for Hanweir Garrison just fine but it won't show if it is placed into your deck or Sideboard. Putting it into your sideboard also just places it into your mainboard.
![2017-04-17 1](https://cloud.githubusercontent.com/assets/24588007/25091666/9e50138a-238a-11e7-97eb-88cea5b19ddd.png)(Showing that you can search for it)
![2017-04-17 2](https://cloud.githubusercontent.com/assets/24588007/25091742/f57f1070-238a-11e7-97dd-758c93254078.png)(Here I added Hanweir Battlements to my Side- and Mainboard and then added a five Hanweir Garrisons to my main- and five to my sideboard. Creature count went up.)

Additionally, every card you put into your deck after that will also be affected by the same problems.
![2017-04-17 3](https://cloud.githubusercontent.com/assets/24588007/25091875/7cffd304-238b-11e7-9bcb-deb859459fb2.png)
(Here I added 4 copies of Demon of Dark Schemes to my main- and 4 to my sideboard. Creature Count went up by 8)

Hitting the "New" button will remove all but the cards affected by this.
![2017-04-17 4](https://cloud.githubusercontent.com/assets/24588007/25091921/c6c6b066-238b-11e7-8beb-226273728a87.png) (Hit the "New" button. Creature Count is still at 18.)

"Show All" in the context menu doesn't affect these cards at all, so they're not just hidden.

Decklists previously created won't load properly if they contain Hanweir Garrison.
![2017-04-17 5](https://cloud.githubusercontent.com/assets/24588007/25092007/21afb9fa-238c-11e7-96bd-499aeaab1dc7.png) (Tried to load a 60 Card deck with additional 15 cards in the sideboard. The main board contained one copy of Hanweir Garrison)

You can't Sideboard with a deck containing Hanweir Garrison. After the match a "empty rule" pops up and nothing happens until the sideboarding time runs out and the match continues.
![2017-04-17 6](https://cloud.githubusercontent.com/assets/24588007/25092157/b8b1c3c0-238c-11e7-82b8-7ccd8bf69e04.png)

After fiddling around and putting Hanweir Garrison into your deck and then hitting the "new" button all other decklists won't load properly until you "Exit" Deck Editor, re-open it and re-load the decklist (even if they don't contain Hanweir Garrison)
![2017-04-17 7](https://cloud.githubusercontent.com/assets/24588007/25092298/616d27ca-238d-11e7-996d-8793e1d5436b.png)

I restarted both Client and server multiple times and it didn't solve this issue. This only happened with the newly released Amonkhet update (Version 1.4.23V0)

**Comment by YuanRamirez** [comment]
Drawing one of those bottom halves of meld cards also throws an "empty rule" and the match won't continue.

**Comment by drmDev** [comment]
From the forums, a user posted the following as a possible cause:

"Did some troubleshooting with my Hanweir Garrison problem and I'm pretty sure I've found the issue.

The problem is dependent on whether or not "Fall back to plain image based rendering" is checked or not in the preferences. If it is not checked, Garrison will be buggy and can't be added to a deck(and crashes games if it's played). Checked, everything works perfectly."

**Comment by Kerrus** [comment]
Yeah, except I tried checking it and still have the problem.

**Comment by YuanRamirez** [comment]
Weird, because I had to check it and now it works for me

**Comment by drmDev** [comment]
Odd... so as that user on the forum reported - this issue does seem relevant to changing that checkbox possibly?

**Comment by patbou** [comment]
Myself, I have no problems with Garrison. I can add it to any deck, and can play it. Against certain opponents, I can play it normally, and still no problems. But against others, it just crashes the game. Last time I played it, game froze and both players lost priority. My opponent unchecked "Fall back to plain image based rendering", and we were able to rollback (that's something, at least). But then we were in a rollback loop, and it was not possible to rollback until it was ok (as is usually the case).

This bug really is annoying in the current metagame. Humans are really popular with Amonkhet, and many players are playing Garrison. The number of games that the bug ruins is alarming. Can something be done soon?

**Comment by drmDev** [comment]
(all of below is taken from forums):

Hanweir Garrison seems to cause a problem with opponent's interface. Twice this morning, I've played Hanweir Garrison, and passed the turn.
- The first time, opponent was able to put Nissa, Voice of Zendikar on the stack, but he couldn't tap his lands.
- The second time (picture below, RG opponent), I was waiting for opponent to be done with upkeep and draw. But on his side, it looked like it was still end of turn and waiting on me to be done with it.

It's a new bug. I don't know if it's new from this morning, or from last update. I'm pretty sure I played the card this week with no problems. But twice this morning.

If it is any help, here's the game log :
7:39 AM: patbou73 casts Hanweir Garrison [efb]
7:39 AM: patbou73 puts Hanweir Garrison [efb] from stack onto the Battlefield
7:39 AM: Ability triggers: Thalia's Lieutenant [815] - Whenever each other Human you control enters the battlefield, put a +1/+1 counter on Thalia's Lieutenant [815].
7:39 AM: Ability triggers: Thalia's Lieutenant [0e2] - Whenever each other Human you control enters the battlefield, put a +1/+1 counter on Thalia's Lieutenant [0e2].
7:40 AM: patbou73 sacrificed Clue [5fd]
7:40 AM: patbou73 activates: draw a card. from Clue [5fd]
7:40 AM: patbou73 draws a card
7:40 AM: patbou73 attacks with 0 creatures
7:44 AM: Turn 15 josh292929 (14 - 20)

And here's the chat log (edited) :
7:42 AM: patbou73: ok?
7:42 AM: josh292929: ya its says u have priority
7:42 AM: patbou73: ????
7:43 AM: patbou73: nope... it says End Turn - Waiting for josh292929
7:43 AM: josh292929: id say we will have to cut our game short but thank u and ur deck looks sweet
7:44 AM: patbou73: There's a bug
7:45 AM: josh292929: it still says u have priorty

On the screen capture, when I started to log the bug, it was now Upkeep. But opponent still wasn't able to play or click anything.

![garrison](https://cloud.githubusercontent.com/assets/11060241/25461153/5485ce84-2ab5-11e7-93ce-e5e36285d4b3.png)

Also...  I'm 100% sure the bug is new from this morning (April 22, 207). I've played games this week with Hanweir Garrison, and had no problems at all. I even have this screen capture of me AND my opponent having Hanweir Garrison in play (taken yesterday). So I don't know what changed since yesterday, but the bug is new from today.

![garrison2](https://cloud.githubusercontent.com/assets/11060241/25461194/8b6bd72c-2ab5-11e7-8805-cc13f8d5105c.png)

--------------
The bug with Hanweir Garrison is not affecting everyone. I'm not sure what causes it to be buggy for one person but not the other.

------------
The game crashed again, with Hanweir Garrison on the stack. I've sent these instructions to my opponent, and the box in his preferences was already checked. Mine too. So the solution is not there.

It's pretty weird, because I played Hanweir Garrison again this morning against other opponents, and all was fine.

Hanweir Garrison doesn't cause a crash 100% of the time, but 100% of the crashes happen with Garrison in play or on the stack.

I already posted a lot of details on page 4 of this thread. Can a programmer have a look at this?

**Comment by drmDev** [comment]
I have not been able to duplicate this issue at all, which makes troubleshooting this very difficult.

**Comment by drmDev** [comment]
![norepro-garrison](https://cloud.githubusercontent.com/assets/11060241/25463108/d709ed3e-2ac1-11e7-854d-2fd463520302.png)

I tried all sorts of actions involving Hanweir Battlements and swapping on/off "Images > Fall Back to previous rendering" but was never able to produce the issue. If someone is able to find a way to consistently duplicate the issue I can investigate further.

**Comment by drmDev** [comment]
Spoke with other developers in our Gitter chat and a suggestion was given to try based on some users seeing "Empty rule" from these meld cards. See commit referenced above. Still cannot duplicate the issue, but hopefully this will resolve it for others experiencing it.

Will be available upon next release

**Comment by patbou** [comment]
I don't think you can replicate the issue, unless you play games with other users, and happen to play against a user that suffer from the Meld bug (50-65% of the users). When we encouter this bug in games, I now ask my opponent to do these things...
1- Go to Preferences - Images - check or uncheck the first box "Fall back...", and save.
2- Go to Deck Editor, try to add Hanweir Garrison, and tell me what you see.
3- Go back to Preferences - Images - check or uncheck the first box "Fall back...", and save.

Most of the times (pretty sure it's 100%), the game will unbug after one of these steps. I did this 3-4 times yesterday (out of around 7-8 games), with different opponents.

I don't know the exact message my opponent receives, but I can ask the next to post here a screen capture.

Note that I can no longer play Standard, because BFZ and OGW are considered illegals. Please correct this. Thanks.

**Comment by drmDev** [comment]
We'll have the updates for standard up by the next release (up to @LevelX2 availability and discretion as usual on releases).

Regarding this bug, though I'm sure I could duplicate it in game with other players from what I've been told, I won't be able to gain any additional information on what's happening on the code behind it causing the problems unless I run it in a debugging environment (on localhost, where I can do player vs player with my own two clients playing each turn).

Thanks for all the additional details. Good to hear you found a workaround and this issue does seem heavily reliant on what happens with that checkbox being swapped from on/off. I'll ask some of our developers more familiar with the UI portion to take a closer look at this.

**Comment by JayDi85** [comment]
No more actual
