### ISSUE TITLE
Binding Mummy's ability doesn't trigger from Liliana, Death Majesty -3

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3165]
Situation: I have Binding Mummy and Liliana, Death's Majesty, opponent controls a creature, I have Winged Shepherd in my graveyard.
I use Liliana's -3 to bring the Angel back into play, which is now also a Zombie, but Binding Mummy's ability doesn't trigger.

- from forums

**Comment by drmDev** [comment]
will add UT

**Comment by LevelX2** [comment]
The problem is caused by the order the two effects of Liliana's -3 ability are aplied during resolution.
1. The card is moved and the ENTERS_THE_BATTLEFIELD event triggers
2. The continuous effect to add type and color is added to the game effects.
So the subtype Zombie is not added while the triggered ability of Binding Mummy is checked.
I switched the order of the two effects and changed rul text and target handling a bit to get it to work.

But this is a common problem for all kind of abilities that change the zone of an object and add attributes to the object by continuous effects. So best we would implement a more general solution that allows to define dependeny between the effects of an ability and the ability resolutions knows when to switch the order of the effect applying.
