### ISSUE TITLE
Norn's Annex bug ?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3178]
Norn's Annex doesn't seem to work properly.
In a game against AI, the first creature attacking my opponent with that artifact triggered the payment of {w} or 2 life, as expected. On every subsequent attack, I was prompted whether I wanted to pay or not, but I didn't have to actually pay the cost (i.e. lose 2 life since I didn't have white mana).

- from forums

**Comment by SpikesCafe-google** [comment]
I can confirm this bug. I play Norn's Annex against the AI, and it basically does nothing. The computer attacks me without paying life or mana.

**Comment by drmDev** [comment]
There are numerous bugs with the AI specifically. As I've said many times before, I do not recommend any serious play-testing against the AI. For instance, I only use the AI to test new card implementations and bug fixes. I don't ever play an actual game against them.

**Comment by SpikesCafe-google** [comment]
This is not an AI bug. I outlined the steps to reproduce in detail. Once you pay 2 life once, Norn's Annex stops prompting you to pay {W/P} and instead prompts you to pay empty string. If you pay {W} instead of 2 life, Norn's Annex works fine. There's something stateful about the card that remembers the cost has already been paid even though it needs to be paid once per attacker.

Select attackers (Your turn / Declare Attackers)
  - Clicking "all attack" causes undo button to appear, but does not otherwise do anything.
  - Attack with single creature
    - Pay {W/P} to attack? (Norn's Annex [a51])
      - No: Creature untaps, undo button not visible.
      - Yes: Pay 2 life instead of {W}? (Norn's Annex [a51])
        - No: Pay {W} (Norn's Annex [a51])
          - Cancel: Creature untaps, undo button not visible.
          - Pay: Creature attacks, Norn's Annex works as expected.
        - Yes: Creature attacks, but Norn's Annex breaks.

Once 2 life has been paid, Norn's Annex is broken:
Select attackers (Your turn / Declare Attackers)
  - All attack now works.
  - Attack with a single creature
    - Pay to attack? (Norn's Annex [a51])
      - No: creature untaps
      - Yes: not prompted to pay
