### ISSUE TITLE
Duplicant exiling Commander interaction

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3299]
In a commander game, if Duplicant exiles a commander card, it gets the card's power and toughness even if the "exiled" card is in the command zone.

-- from forums

**Comment by Tharkon** [comment]
This bug seems to have resurfaced, even though none of the edited code was touched.
I should note that it is not specific to Commanders.
I tested it in a legacy duel by casting Duplicant targeting Grizzly Bears and then casting Riftsweeper targeting the same Grizzly Bears card. The Duplicant stayed a 2/2, though it should return to being a 2/4.

`battlefield:Player:Chromatic Orrery:1`
`battlefield:Player:Forest:3`
`battlefield:Player:Grizzly Bears:1`
`hand:Player:Duplicant:1`
`hand:Player:Riftsweeper:1`


Line 145 in Duplicant should probably check if the "imprinted" card is still in exile. Or I guess the getImprinted() function should check that.
