### ISSUE TITLE
Cancelling casting flashback Conflagrate doesn't return cards to hand

### ISSUE THREAD

**Issue by xmagethrowaway** [magefree/mage#3337]
Conflagrate asks to discard cards before paying mana costs, and if casting the card is cancelled instead of paying mana costs, the discarded cards incorrectly stay in the graveyard.

Instead, XMage should undo the discard, or perhaps should ask to discard cards after paying mana costs, so that undo is not possible.

**Comment by Himsself1** [comment]
Discarding cards is part of the cost of flashing back. So they should remain in grave if the spell is cancelled

**Comment by emerald000** [comment]
If in the middle of the process of casting a spell or activating an ability you wish to cancel the casting/activating process, you have to undo every cost you paid that is undoable. Costs that are not undoable are "actions that moved cards to a library, moved cards from a library to any zone other than the stack, caused a library to be shuffled, or caused cards from a library to be revealed" (CR 720.1)

Since none of those clauses apply, you should be able to put back the discarded cards into your hand.
