### ISSUE TITLE
Magma Spray + Soul-Scar Mage is not working

### ISSUE THREAD

**Issue by ogier** [magefree/mage#3359]
To reproduce:

1. Cast Soul-Scar Mage.
2. Target a 2-toughness creature with Magma Spray (I have seen this with Aven Initiate).

What I expect: Creature has 2 -1/-1 counters placed on it, Magma Spray goes to graveyard, creature targeted gets exiled.  
What happens: Creature has 2 -1/-1 counters placed on it, Magma Spray goes to graveyard, creature targeted goes to graveyard.

Maybe Magma Spray is coded to only work with "Destruction" events like damage? Or Soul-Scar Mage is replacing the entire effect of Magma Spray instead of just the damage? Either way, once Magma Spray has resolved on the creature it should be exiled if it dies.

**Comment by fireshoes** [comment]
Notably Magma Spray is worded differently than Incendiary Flow, where the creature should die instead of being exiled, so a UT with both may be a good idea.

**Comment by drmDev** [comment]
tests added - Magma Spray issue replicated, that's a bug. Incendiary Flow works as expected - creature died instead of exiled there.

**Comment by drmDev** [comment]
Actually Incendiary Flow also is an issue, I thought the wording suggested it would be handled differently, but it does not:
`The damaged creature will be exiled if it would die for any reason that turn, not just if it dies due to damage from Incendiary Flow.` (gatherer)

Adjusting the test... both will be failing at the moment.

**Comment by Scott-Crawford** [comment]
I think Incendiary Flow is fine. Soul-Scar Mage is a replacement effect, so no damage would be marked on the creature, and is not actually damaged by the spell, so it doesn't get exiled. `If multiple prevention and/or replacement effects are trying to apply to the same damage, the controller of the creature that would be dealt damage chooses the order in which to apply them. As examples, an opponent could choose to apply the effect of Djeru’s Resolve and prevent the damage rather than put -1/-1 counters on it; or an opponent could choose to convert the damage to -1/-1 counters before Insult could double it, and then Insult’s effect won’t apply anymore.` (gatherer) The ruling you quoted above implies that the creature must be damaged by the spell, and any prevention effects wouldn't send it to exile.

Magma Spray, on the other hand, doesn't care if the creature was damaged, just that it was targeted and that it died. ` It applies to the target creature even if Magma Spray deals no damage to it (due to a prevention effect) or Magma Spray deals damage to a different creature (due to a redirection effect).
` (gatherer)

**Comment by drmDev** [comment]
Trying to confirm the ruling with L2+ judges, also searching up people who have discussed this ruling. Found this so far:
http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/775489-incediary-flow-and-soul-scar-mage-issues

`Correct, the Soul-Scar Mage's ability replaces the damage with -1/-1 counters. Since the Doomed Dissenter was not damaged by Incendiary Flow it will not be exiled and would go to the graveyard. `
(confirms my initial understanding of it until reading the gatherer ruling)

**Comment by emerald000** [comment]
L2 here. Here what happens:

**Casting a Magma Spray on a Squire with a Soul-Scar Mage on the battlefield:**
An event trying to deal 2 damage to the Squire is created. Soul-Scar Mage replaces it with an event putting 2 -1/-1 counters on it. SBAs try to create an event to put the Squire in the graveyard. Magma Spray replaces it with putting the Squire in exile. Squire ends up in exile.

**Casting an Incendiary Flow on a Squire with a Soul-Scar Mage on the battlefield:**
An event trying to deal 3 damage to the Squire is created. Soul-Scar Mage replaces it with an event putting 3 -1/-1 counters on it. SBAs try to create an event to put the Squire in the graveyard. Since Incendiary Flow did no damage to the Squire, its replacement effect doesn't apply and Squire ends up in the graveyard.

In general, if two cards do not use the exact same wording, there will be practical differences that will cause them to act differently in some corner-case.

**Comment by drmDev** [comment]
Thanks again for being my fav L2 judge @emerald000  :) you da real MVP! Adjusting the test back to its original state - Incendiary Flow will be working correctly with our current code (creature dies and not exiled). However Magma Spray still is bugged since the creature is not exiled in this scenario when it should be.

**Comment by drmDev** [comment]
fixed with commit 351095a
