### ISSUE TITLE
Historical Type 2 Issues

### ISSUE THREAD

**Issue by c001357** [magefree/mage#3417]
The creation of Type 2 began on January 1995 ([htttps://groups.google.com/forum/#!msg/rec.games.deckmaster/MymOFRYudwU/0FuCZ_bXMnIJ](url)) so the first standard should be 3ED, DRK, and FEM. That being said, I would recommend adding Channel to the banned list. 

Decks from 2000-2001 and 2010 aren't being recognized. Some samples:
[http://mtgtop8.com/event?e=9239&d=253025&f=ST](url)
[http://mtgtop8.com/event?e=9240&d=253046&f=ST](url)
[http://mtgtop8.com/event?e=770&d=207942&f=ST](url)
[http://mtgtop8.com/event?e=457&d=189608&f=ST](url)
Thanks again for the work.

**Comment by marthinwurer** [comment]
The Historical Type 2 format is based off of the [Historic Standard](http://thattournament.website/historic-tournament.php) group. I used their list of standards when creating the deck validation code. It looks like their organizer was asking about previous standard formats in 
[this thread](http://www.mtgsalvation.com/forums/magic-fundamentals/magic-general/514766-question-about-standard-formats-of-past) where they decided to not do formats earlier than 4th. I can definitely add the 3ED, DRK, and FEM format, though. I'll take a look at the deck lists that aren't being recognized and report back in a little bit.

**Comment by marthinwurer** [comment]
Issues with the 2000-2001 decks are due to Nemesis not having the correct set code in the historical standard code. 3 line fix. 

Issues with the 2010 decks seem like issues with the code that takes the dates of the standard rotations that I took from the Standard validation code. It looks like the release dates changed somewhere along the line (or maybe it was the change in core sets). This part will take a little bit to iron out.

It also looks like the 3 block standard format that we just had will have to be hard coded in there. I will need to look into this some more.

**Comment by c001357** [comment]
no worries, take your time

**Comment by marthinwurer** [comment]
Pull request submitted. There was an issue with the release date of Shards of Alara.

**Comment by c001357** [comment]
Hello, some Zendikar - Scars decks are still not valid
for reference: [http://mtgtop8.com/event?e=2013&d=214255&f=ST](url)

thanks again!

**Comment by marthinwurer** [comment]
Finally took a look at it. Zendkar had the wrong release date too. Pull request should be up soon.

**Comment by Zerrisx** [comment]
Looks like all the issues in here have been addressed.
