### ISSUE TITLE
Java not found ?!?

### ISSUE THREAD

**Issue by VictorBaptista99** [magefree/mage#3419]
Been around all day w\ this issue. Had to reinstall Xmage and for the first time it happened to me despite using the program often... dunno why but the java folder has nothing in it. And the Xmage launcher dont let me launch client. only lets me update and check versions. When i click on both just loops again and again to the java not found...

here's the writing on the notepad:

ERROR 2017-05-23 18:02:34,217 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.io.FileNotFoundException: http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-windows-x64.tar.gz?AuthParam=1495562672_d91c8da463ccb6e8f0d1d967c525b07b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:38)
	at com.xmage.launcher.DownloadTask.download(DownloadTask.java:64)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateJava(XMageLauncher.java:735)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:713)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-windows-x64.tar.gz?AuthParam=1495562672_d91c8da463ccb6e8f0d1d967c525b07b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.xmage.launcher.Downloader.connect(Downloader.java:27)
	... 10 more
ERROR 2017-05-23 18:02:34,217 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateJava
java.io.FileNotFoundException: C:\Users\Utlzador\Desktop\xmage.dl (O sistema não conseguiu localizar o ficheiro especificado)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.xmage.launcher.DownloadTask.extract(DownloadTask.java:131)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateJava(XMageLauncher.java:740)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:713)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Anyone w\ same problem? thanks

**Comment by jholutiak216** [comment]
I am having the same problem tired deleting everything, but still won't let me launch client or server, only update and check version.

**Comment by LeoBuenoo** [comment]
I am having the same problem tired deleting everything, but still won't let me launch client or server, only update and check version.²

**Comment by VictorBaptista99** [comment]
So, how to fix this? i clearly have Java up to date

**Comment by kmcculloch** [comment]
Looks like the download from Oracle isn't working. I figured out how to do it by hand on Mac OS X. Probably similar for other systems.

First, run the XMage launcher as usual and pay attention to the file name at the end of the file download link. In my case, it's jre-8u102-macosx-x64.tar.gz:

![screen shot 2017-05-25 at 5 42 37 pm](https://cloud.githubusercontent.com/assets/1548096/26471879/9b707f74-4171-11e7-99c4-c4252de300e0.png)

Also note the "Java version available" string, which is currently 1.8.0_102:

![screen shot 2017-05-25 at 5 45 06 pm](https://cloud.githubusercontent.com/assets/1548096/26471941/e68e6c32-4171-11e7-9732-f6a835d68992.png)

Quit out of the launcher.

So now you're at the point where you've got all the Xmage code and an empty "java" folder. Go to [Oracle's download archive](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html) and find the file that corresponds to the file name you got from the download link. Be sure you get the right one. I had to click the "Accept License" and also log in with an Oracle account to download the file.

Unzip the archive and put the resulting folder (in my case, "jre1.8.0_102.jre") inside your "java" folder.

Finally, edit the installed.properties file to tell the launcher which version of java is there. (Otherwise it will assume that there's no java and will try to download it again.) Find the line that says "java.version=" and add the "Java version available" string from the launcher window. It should now look something like this:

```
#---XMage Properties---
#Thu May 25 17:42:17 EDT 2017
xmage.launcher.version=0.3.8
java.version=1.8.0_102
xmage.client.console=true
xmage.launcher.guisize=21
xmage.client.javaopts=-Xms256m -Xmx512m -XX\:MaxPermSize\=384m -XX\:+UseConcMarkSweepGC -XX\:+CMSClassUnloadingEnabled
xmage.home=http\://xmage.de/xmage
xmage.server.console=true
xmage.version=1.4.23V5 (2017-05-18)
xmage.server.javaopts=-Xms256M -Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.downrate=0
xmage.torrent.uprate=50
xmage.torrent.use=false
```

You should now be able to open the launcher again and launch the client.

Good luck!

**Comment by drmDev** [comment]
Alternatively, in your XMage installation directory, run the startMage batch file instead of using the launcher.

**Comment by jholutiak216** [comment]
@drmDev This is something I also had to do after I get the java files in the folder

**Comment by VictorBaptista99** [comment]
Yes. Worked for me  @kmcculloch .  thanks. Should i need to reinstall the whole thing again will i need to do this back to back? Hope not. Thanks you guys

**Comment by VictorBaptista99** [comment]
@drmDev Yes been using Xmage that way, but feels bad :) also i think you cant change from .DE server from there or maybe was just my problem. Anyway thanks

**Comment by richardhedberg** [comment]
@kmcculloch 

Trying to get the client to work on OSx, followed your steps but launching the client in the launcher just opens the console and it's all blank. If i try to open the client via startClient.command it gives me this error message:
`Last login: Tue Jun  6 14:59:00 on ttys001
username-MacBook-Pro:~ username$ /Users/username/Downloads/xMage/xmage/mage-client/startClient.command ; exit;
-bash: /Users/username/Downloads/xMage/xmage/mage-client/startClient.command: /bin/sh^M: bad interpreter: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

If I change the path in the startClient.command to the full adress instead of using ./ it launches the client but with a ton of error and I can't do anything in the client.
`Last login: Tue Jun  6 15:01:09 on ttys001
username-MacBook-Pro:~ username$ java -Xms256m -Xmx512m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -jar /Users/username/Downloads/xMage/xmage/mage-client/lib/mage-client-1.4.23.jar
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
INFO  2017-06-06 15:07:39,403 Starting MAGE client version 1.4.23V5                                                      =>[main] MageFrame.main 
INFO  2017-06-06 15:07:39,406 Logging level: INFO                                                                        =>[main] MageFrame.main 
ERROR 2017-06-06 15:07:42,727 Couldn't rename mana symbols!                                                              =>[AWT-EventQueue-0] ManaSymbols.renameSymbols 
ERROR 2017-06-06 15:07:42,729 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,729 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,729 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,729 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,729 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,729 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,730 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,730 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,730 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,730 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,731 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,731 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,731 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,732 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,732 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,733 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,733 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,733 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,733 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,733 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,734 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,735 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,735 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,735 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,735 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,736 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,736 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,736 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,736 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,737 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,737 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,737 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,737 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,737 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,738 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,739 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,740 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,741 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,742 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,742 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,742 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,742 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,742 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,743 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,744 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,744 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-06-06 15:07:42,744 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
INFO  2017-06-06 15:07:43,428 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-06-06 15:07:43,471 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-06-06 15:07:44,033 Client start up time: 4 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
FATAL 2017-06-06 15:07:44,034 Config error                                                                               =>[AWT-EventQueue-0] Config.<clinit> 
java.io.FileNotFoundException: config/config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at mage.client.util.Config.<clinit>(Config.java:63)
	at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:105)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:314)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
FATAL 2017-06-06 15:07:44,037 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ExceptionInInitializerError
	at mage.client.dialog.ConnectDialog.showDialog(ConnectDialog.java:105)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:314)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at mage.client.util.Config.<clinit>(Config.java:68)
	... 16 more

`
Any idea of what might be wrong?

**Comment by Murqulator** [comment]
@kmcculloch I downloaded the specific version of Java but can't seem to edit the installed Properties file. Tried with text edit and saved it but when i open the file again it is back to it's original state. How did you edit the file?

**Comment by TheNoLifeKing121** [comment]
having the same issue with linuix

**Comment by drmDev** [comment]
Though does not resolve this issue, the alternative is to circumvent using the launcher altogether. Follow the steps outlined here to do so:
https://www.youtube.com/watch?v=FL89GFJv0_A

**Comment by JayDi85** [comment]
It's can be a java ca certificates problem for linux machines -- you can't download https links (new java version or svg images from scryfall). 

Need to manually update `cacerts` file, setup JAVA_HOME and java options to run with that keystore. Command line to launch mage-client (example to run from `startClient.command` in `mage-client` folder):
`java -Djavax.net.ssl.trustStore=$JAVA_HOME/jre/lib/security/cacerts -Djavax.net.ssl.trustStorePassword="changeit" -Xms256m -Xmx512m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -jar ./lib/mage-client-1.4.26.jar`

You can read/download full instruction [here](https://yadi.sk/i/D_ysbjcy3RAB9o).
