### ISSUE TITLE
Problem going from version 1.4.24V1 to 1.4.24V2 - client

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#3635]
trying to download the update to go from version 1.4.24V1 to 1.4.24V2 but when the update finishes it shows that im still on version 1.4.24V1 and tells me theres an update, tried downloading and restarting multiple times with the same outcome. I get this error message if i try to start xmage with version 1.4.24V1 installed "Error: Could not find or load main class mage.client.MageFrame
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0"

**Comment by LevelX2** [comment]
No need to update the client. There were no releveant client changes since V0.
It's probably caused because the server is stressed by massive download requests.

I chnaged the refered download source to another server. With the previous server some people had problem to download from it also in the past.

**Comment by Yarp504** [comment]
First time poster here so excuse any faux pas. I am having the same problem with same error message. A few hours ago the launcher would begin download of 1.4.24V2 with the same outcome as OP. However, now the launcher will not even begin download of new version.

**Comment by JayDi85** [comment]
Not actual any more.
