### ISSUE TITLE
Doubling Season and Gemstone Mine

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3665]
Yesterday, I managed to land a doubling season then played gemstone mine as my land drop. It entered with 6 mining counters. Decided to ask the judge chat today:

https://snag.gy/adZ4em.jpg

So it should enter with 3?

**Comment by jeffwadsworth** [comment]
The judge may want to check this official ruling out.
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=370387

**Comment by tamaroth** [comment]
This is partially correct. 

Doubling Season applies only to effects. So if you put Gemstone Mine through an effect, like resolved Crop Rotation, it would enter with 6. Same thing applies to Triskellion, planeswalkers, etc. 

Playing a land is not an effect however. To quote from Comprehensive Rules (07.07.2017):

609.1. An effect is something that happens in the game as a result of a spell or ability.

Playing a land is a special action and as such does not create an effect.

This means that Gemstone Mine is put on the battlefield with only 3 counters.

Hope that clears things up a bit more!

Best regards,
tamaroth

**Comment by jeffwadsworth** [comment]
In the case listed above by the OP, he played the land as his drop, so it comes in with 6 counters.

**Comment by tamaroth** [comment]
The difference is:

Triskellion is cast, then resolved and enters the battlefield creating effect that changes the way it enters the battlefield (with counters).

Gemstone Mine is put on the battlefield as a special action, not as a spell or ability. There is NO replacement effect as those can only occur as a result of a spell or an ability.

Doubling Season specifically states that it only replaces another effects and since playing a land does not create an effect, the land will have only 3 counters.

You can look up other lands that come with counters, e.g. vivid lands, and their magic rulings and you will find that lands that come with counters come with exactly that amount of counters despite DS being on the battlefield.

e.g.

http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/528370-vivid-lands-and-doubling-season
http://mtgtutorials.tumblr.com/post/91815600515/why-exactly-does-doubling-season-not-affect-vivid
http://cornerofmagic.blogspot.cz/2014/10/doubling-season-or-is-it.html

Hopefully that helps!

**Comment by JRHerlehy** [comment]
Tabak as supposed to update the rules like three years ago so that DS and lands with counters would work as expected.  Looks like it never did go live thought for who knows what reason.

**Comment by jeffwadsworth** [comment]
@tamaroth You are correct.  We will check it out.

**Comment by spjspj** [comment]
Had confirmation from a Level 3 judge that this should be 3 counters.
