### ISSUE TITLE
Banisher Priest/Grasp of Fate/etc don't return cards when owner leaves game

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4025]
From the forums:

"Exile effects with durations (i.e. Grasp of Fate, Hostage Taker, etc.) don't work properly: 

If the owner of the permanent leaves the game after the artifact/creature is exiled, the artifact/creature will stay exiled."

There was also a mention of them still exiling things if they've left the battlefield before the ability resolves, but that I couldn't confirm and it seems like they should work properly.

**Comment by Zerrisx** [comment]
If it's due to quitting at a weird time, there are other issues for that (specifically, it's likely the permanents aren't leaving the battlefield, which is why the cards don't get returned, see #4472).

For straight up *losing* the game, that's being handled correctly.
![image](https://user-images.githubusercontent.com/59861365/87833761-42af2400-c84e-11ea-94fd-5a2770b0961b.png)

Thus, either cannot reproduce or duplicate.
