### ISSUE TITLE
Flickerwisp bug

### ISSUE THREAD

**Issue by DEVDante** [magefree/mage#4156]
Flickerwisp does not return exiled card if the ability has been triggered during end step.

Easiest way to reproduce this is to exile one Flickerwisp with another one,

**Comment by emerald000** [comment]
It is supposed to return at the next end step. Is it just never returning?

**Comment by Zzooouhh** [comment]
Confirmed that the second Flickerwisp never returns if it's exiled during the end step. Same thing happens if Flickerwisp is cast during the end step with Flash via Vedalken Orrery or similar. I remember encountering a somewhat similar issue with Grinning Totem also, if you'd use it during your upkeep, you wouldn't be able to cast the exiled card at all, as if the "until your next upkeep" duration was checking for the entirety of the upkeep step.

**Comment by theelk801** [comment]
I fixed this.
