### ISSUE TITLE
Problem on interaction with card like Vampire Hexmage.

### ISSUE THREAD

**Issue by spirius44** [magefree/mage#4218]
Hi, When I use "Vampire Hexmage" to remove all counters to a card with counters (for me "Thing in the ice"), counters are removed but I must cast another spell to trigger the transformation.

Thanks!

**Comment by emerald000** [comment]
That is correct. The transform part of Thing in the Ice is tied to the trigger and it will not flip unless you cast another spell.

**Comment by spirius44** [comment]
But the rule is "Then if it has no ice counters on it, transform it." So after use Vampire Hexmage, the card should flip, no..?

**Comment by emerald000** [comment]
It's because it is a single ability. That part of the card text is inside the triggered ability of removing a counter and is only checked during the resolution of the triggered ability.

Compare it to Dark Depths that has a separate ability. That's why Dark Depths works with Vampire Hexmage and Thing in the Ice doesn't.

**Comment by spirius44** [comment]
Oooh... I understand! Thanks a lot to your explication! :)
