### ISSUE TITLE
Dominating Licid BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4494]
when it becomes an enchantment and the creature it enchants dies, the licid stay on the battlefield (obviously if u chose not to change it back into a creature before the creature it enchanted died.) when it should go to the graveyard because it lost its creature permanent type when it became an enchantment.

**Comment by emerald000** [comment]
For whoever wants to tackle this: this is caused due to a flawed implementation of Bestow. Bestow currently checks for creature cards that are non-creature auras and change some rules stuff so you don't sacrifice it if the enchanted permanent isn't on the battlefield anymore. This works fine for Bestow ... not so much for the Licids.

PS: There are a couple of tests that were ignored a while ago about that situation.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
