### ISSUE TITLE
There is an effect or ability that removes the manaCostsToPay from a cards spell ability and prevents the player from ever casting that card in the match.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4600]
There is an effect or ability that removes the manaCostsToPay from a cards spell ability.
You can't cast that card later, because it has no costs to pay and casting is always canceled.

Don't know yet, which card that caused.

**Comment by glitchkuh** [comment]
Had that Problem too in a Game yesterday
Opponent cast a Cyclonic Rift with Overload, after that I couldn't recast Bow of Nylea.
When I tried to, I get the Same pop-up display as when I want to cast Mox Opal (Options are "cast" and "cancel"), but instead of casting it after hit the "cast" option, it did nothing.

**Comment by Zerrisx** [comment]
From all the similar issues, looks like this is/was a bug with cards that let you cast things without paying their mana cost, and that the removal of the mana cost carried over after that card later changed zones - got a lot of cascade being mentioned here.  I'll run some tests and see if this is still reproducible.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
