### ISSUE TITLE
Limit the number of rollback requests a player can make in a game

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4650]
There could/should possibly be a limit on how many rollbacks a single player can request in a given game, settable in the new tournament/new table by the creator of the table.

**Comment by Zerrisx** [comment]
...Why?  This seems like it's trying to solve a problem the wrong way.  Either you don't want the ability to rollback (turn it off), or you do and you want it used in reasonable ways (turn it on, and stop playing with the people who are doing dumb things with it).  It's not a competitive integrity issue, since in a truly competitive game/tournament, you can always set it to no.  What's the realistic use case for this extra setting?

**Comment by JayDi85** [comment]
I think it's not about settings -- it's about dialog abuse. See example with "show hand request" in 9a9b304fd593b16da40e26180fe24e39863ec8de (users can ask your hand once per game, reset it by re-activate button). Some people abuse that dialog to interfere with others.

If no one reports about bad/abuses rollback requests then it can be closed.

**Comment by Zerrisx** [comment]
Right, I get that, I just don't think this is a good way to try to police excessive dialogue requests.

A better method might be a button for "deny all future requests" in a game, which would allow you to stop abuse, without blocking legitimate requests where things break a few times but you aren't bothered.

**Comment by JayDi85** [comment]
I think it's not not actual anymore. Don't see any reports about request dialogs abuse.
