### ISSUE TITLE
Planeswalker Redirection errata

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4799]
This is gonna be a big change, so I'm gonna need some help implementing it. I'm gonna start changing a few manually to get an idea for what can be automated, but if anyone has any ideas please share them. I'll be opening a separate branch for this.

Update: Here's an incomplete list of cards that need changing:
- [x] CurseOfThePiercedHeart
- [ ] QuenchableFire
- [x] TheFallen
- [x] VialSmasherTheFierce

**Comment by jpgunter** [comment]
Where is the code that controls what can be a target for DamageTargetEffect? That would take care of a lot.

**Comment by theelk801** [comment]
The problem is that there are a lot of exceptions, so it's not something that can be changed so easily.

**Comment by jpgunter** [comment]
I think a quick start would be to refactor [TargetCreatureOrPlayer.java](https://github.com/magefree/mage/blob/d3fbd60c68610f4af02913bca0b9725ece432739/Mage/src/main/java/mage/target/common/TargetCreatureOrPlayer.java) to allow the targeting of planeswalkers directly, this should be relatively safe since you really only target creatures or players with damage.

We could create a new TargetPlayerOrPlaneswalker/TargetOpponentOrPlaneswalker to be able to choose planeswalkers and find all of the damage cards that only target player/opponent and update their ability target. 

Finally, remove [PlaneswalkerRedirectionEffect](https://github.com/magefree/mage/blob/e909f5c8011bb07c94264a0841745df5a95b8df8/Mage/src/main/java/mage/abilities/effects/PlaneswalkerRedirectionEffect.java).

**Comment by jpgunter** [comment]
Something like this https://github.com/jpgunter/mage/commit/c5ca246cf785757dcb226b3a7c6b19265cb2376e#diff-d1d3fa79548ea9371c29e7027459142e

**Comment by theelk801** [comment]
So I've refactored the targeting damage functionally, but a lot of the changed cards still need their text fixed. I've also added a list of cards that deal damage to players (and only players) and need to change those, most likely manually.

Remember that if you make changes, post them in the right branch

**Comment by JayDi85** [comment]
@LevelX2 from gitter: "The complete damage redirect changes we have to do with another update"

**Comment by theelk801** [comment]
That's fine, I'm doing it in a separate branch anyway

**Comment by JRHerlehy** [comment]
If they hadn’t done the stupid thing of printing new target creature or player cards this set, the refactor would have been easy. But no, Wizards does stupid thing.

**Comment by jack-the-BOSS** [comment]
@JRHerlehy Yeah, that was a weird decision. Maybe those could be the exception, fixed manually since there are/will be so few.

**Comment by theelk801** [comment]
Alright, all the errata is now done except for Quenchable Fire (screw that one, someone else can fix it)

Now the issue is that a lot of tests are failing. Can someone help with that? I'm not sure how to fix them but a lot of spells are no longer casting where they're supposed to.

**Comment by theelk801** [comment]
It's definitely an issue with the test player, but I'm just not sure how to fix it.

**Comment by JayDi85** [comment]
I'm tested that branch -- most of tests failed by wrong outdated source code like `mage.filter.common.FilterPermanentOrPlayer cannot be cast to mage.filter.FilterPermanent`. 

Need to sync it with master.

**Comment by theelk801** [comment]
Alright, so this is done now. Hooray!
