### ISSUE TITLE
Can't cast Fight with Fire for its kicker cost if there is no creatures.

### ISSUE THREAD

**Issue by zalkador** [magefree/mage#4849]

**Comment by JayDi85** [comment]
I can confirm that bug. Fight With Fire source code uses one `TargetCreaturePermanent` but it's must use different target types (for kicker -- any target, for standard-- creature target).

**Comment by theelk801** [comment]
It already has the alternate targets set up in adjustTargets, I think the issue is that this is the first card that completely changes its targets when kicked. The game checks whether the card has any targets, but only if not kicked. Up to now it hasn't mattered but now it does. I'll look into it further.
