### ISSUE TITLE
Images fail to download from any source

### ISSUE THREAD

**Issue by MildlyMunty** [magefree/mage#489]
It will run through the card downloading process displaying progress and at the end ask to do it again because all it did was add empty folders for the images in the order of when they would be needed (from scratch, if repeated it just does nothing).

The first time I ran the program it seemed to take for ever (which makes sense because my internet sucks and it was actually working). Due to bandwidth decided to cancel, close out and pick up again overnight when the seas of data are calmer. I closed out many times while finding a time when it seemed feasible to download. One of these times the game froze and I had to kill the Java Binary process.

After I got everything seemingly up and running I let it go through without noticing that the speed it "downloads" the images at is faster than my internet should allow on a good day. I ended up with ~1.5k card images and ~14k missing ones that cannot be had no matter which source I use. 

My friend and I were going to start playing this together and I think he might have the same issue, but with only 37 cards (I can ask him to delete his images and retry to confirm as when I attempted to start from scratch it only moved the missing card images number to the maximum rather than helping).

This guy seems to have my problem as well, but the fix recommended did not work and the person who recommended it also closed it due to lack of interest.

https://github.com/magefree/mage/issues/394

I will gladly provide logs of me doing what ever you want just as soon as I figure out what I need to do to get them and what sections are needed.

**Comment by JerellDR** [comment]
I'm new to magic so I could be mistaken, but it looks like this happens when the download site does not have the card in the edition it's trying to download it from. Frenzied Goblin for example was implemented for the Friday Night Magic edition. Searching on magiccards.info only shows this card in 3 editions.  

1. English Duel Decks: Speed vs. Cunning (Uncommon)
2. English Magic 2015 (Uncommon)
3. English Ravnica: City of Guilds (Uncommon)

I've looked at the console logs while running XMage in Intellij and it gives a 404 for the url. 
Below are the relavant error logs when downloading from magiccards.info. Hope this helps.
 ~~~
Image download for Frenzied Goblin(FNMP) failed - responseCode: 404 url: http://magiccards.info/scans/en/fnmp/176.jpg =>[pool-4-thread-3] DownloadPictures$DownloadTask.run 
WARN  2015-01-04 20:33:59,373 Image download for Griselbrand(GPX) failed - responseCode: 404 url: http://magiccards.info/scans/en/gpx/11.jpg =>[pool-4-thread-4] DownloadPictures$DownloadTask.run 
WARN  2015-01-04 20:33:59,375 Image download for Disdainful Stroke(FNMP) failed - responseCode: 404 url: http://magiccards.info/scans/en/fnmp/177.jpg =>[pool-4-thread-2] DownloadPictures$DownloadTask.run 
 ~~~

**Comment by fireshoes** [comment]
The most recently announced or released promo cards are coded, but magiccards.info has not updated for the art yet. When they update their site, the art will download. You can also manually download the images, saving the file as card name.full.jpg in the appropriate set folder (FNMP or GPX) in this case. This link has the three most recent FNM promosL
http://magic.wizards.com/en/articles/archive/arcana/january-through-march-fnm-promo-update-2014-12-31

**Comment by JerellDR** [comment]
Thanks for the clarification.  I guess this one can be closed once the images go up on the site.

**Comment by fireshoes** [comment]
I noticed in my client log that there are about 32 cards images that don't download from any of the three image servers. The log shows that the cards are all from the Starter 2000 set and fail because of a bad URL at magiccards.info. In checking magiccards.info, they do not have the images for much of Starter 2000 on their site.
http://magiccards.info/st2k/en.html

However mtgimage.com does have more Starter 2000 images, but they seem to not download automatically from there when selecting mtgimage from the download menu. Maybe some kind of error in the address script?
http://mtgimage.com/actual/setname/starter%202000/

**Comment by fireshoes** [comment]
I corrected the set code on Jace Beleren in Media Inserts from MPB to MBP since the image wasn't downloading, but after the most recent update, it still did not download automatically. The log file shows it was checking the url with the incorrect MPB in it still. Is there somewhere that the set code for this card needs changed, or is it because I didn't delete db files? Something else?

**Comment by LevelX2** [comment]
I guess you're right that it's caused because it's saved in the db.
But it should be corrected if you update the client or delete the client db.
