### ISSUE TITLE
Muldrotha, the Gravetide Bug

### ISSUE THREAD

**Issue by themistocles333** [magefree/mage#4969]
Xmage doesn't treat new instances of Muldrotha, the Gravetide correctly after you've cast cards from your graveyard with him.

Say I cast Muldrotha from my command zone, then play a Lion's eye diamond from my graveyard as my artifact, sacrifice it for blue mana and cast a phantasmal image to copy Muldrotha and sac the commander to the legend rule, putting him in the graveyard. The image is a new instance of Muldrotha and should allow me to recast LED as per this gatherer ruling:

4/27/2018 If you play a card from your graveyard and then have a new Muldrotha come under your control in the same turn, you may play another card of that type from your graveyard that turn.

As is it wont let me and I am unable to properly test this deck.

any assistance in resolving this bug would be very much appreciated.

**Comment by Ysukai** [comment]
This issue is not fixed and here how it's broken.

Have Muldrotha already cast, cast Lion's eye diamond sac for blue, then phantasmal image sac to legend rule so far so good, with the new Muldrotha, cast Lion's eye diamond sac for black then reanimate dead the original Muldrotha, after that you cant cast anything.

Tested a few times,At one point it broke after the first phantasmal image.

Repeat for infinite mana.
