### ISSUE TITLE
Trying to open Xmage on MacBook

### ISSUE THREAD

**Issue by Renegade1079** [magefree/mage#5031]
When I try to open the startClient.command I get a terminal that opens that has the following:

Last login: Fri Jun 15 17:28:37 on ttys001
Myless-MacBook-Air:~ Myles$ /Applications/xmage/mage-client/startClient.command ; exit;
-bash: /Applications/xmage/mage-client/startClient.command: /bin/sh^M: bad interpreter: No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Not sure how to proceed with fixing this, any help would be greatly appreciated.

**Comment by JayDi85** [comment]
You need to install java first. Then try to run launcher by command line from launcher folder (create `run-launcher.command` file and insert command line to it):
 * `java -jar XMageLauncher-0.3.8.jar`

**Comment by Renegade1079** [comment]
Ok, I am pretty sure that I have java installed. I went back and reinstalled it to make sure, as for the launcher I can get it open by running XMageLauncher-0.3.8. jar. After that I click the run client button and the XMage client console opens with a black screen, also clicking the run server button doesn't do anything. I apologize that I am completely oblivious how to do these things on a mac, PC I have it up and running no problem but this is giving me headaches.

**Comment by JayDi85** [comment]
You need to update xmage client files first. Press update button in launcher window and ensure it was downloaded (check `..\xmage\mage-client\` folder with files). If you can't update then try to move `XMageLauncher-0.3.8. jar` file (you need only launcher to install/update) to new folder and update again.

**Comment by Flowzn** [comment]
I have the same problem with xmage on my MBP. But I have no idea of java or coding in general. That is what happens if i try to run the startClient.command file:

/Applications/xmage/xmage/mage-client/startClient.command ; exit;
floriankeuten@Florians-MBP ~ % /Applications/xmage/xmage/mage-client/startClient.command ; exit;
zsh: /Applications/xmage/xmage/mage-client/startClient.command: bad interpreter: /bin/sh^M: no such file or directory


If I try to start the client by launcher app, a white window (mageframe) opens and the beachball appears.

**Comment by JayDi85** [comment]
@Flowzn you can fix auto-login problem (white screen on startup) by [that instructions](https://github.com/magefree/mage/issues/4461#issuecomment-361108597)
