### ISSUE TITLE
SVG symbols download from scryfall are broken

### ISSUE THREAD

**Issue by Agi2626** [magefree/mage#5135]
Download of Scryfall symbols sourcefrom https://assets.scryfall.com/assets/scryfall.css caused error: java.io.FileNotFoundException: https://scryfall.com/assets/scryfall.css =>[pool-9-thread-7] DownloadJob.setError

what should i do ?

**Comment by JayDi85** [comment]
Scryfall website was changed and broke the links. It's will be fixed with next release. With current version it's ok for you -- xmage will use gif symbols from wizards site on svg errors.

But you can manually download svg symbols from that zip (unzip it to `..\mage-client\plugins\images\symbols\svg` folder and restart xmage):
[svg.zip](https://github.com/magefree/mage/files/2178572/svg.zip)
