### ISSUE TITLE
Conjurer's Closet and Commanders

### ISSUE THREAD

**Issue by propri** [magefree/mage#5151]
When you gain temporary control of an opponents commander, and you exile it with Conjurer's Closet, you should return the commander to the battlefield under your control, even if the owner of the commander chooses to send the creature to the command zone.

At the moment the commander is not returned to the battlefield if the opponent sends its commander to the command zone.

**Comment by propri** [comment]
The same with Nephalia Smuggler.

**Comment by Dilnu** [comment]
Conjurer's Closet is looking for a card in the exile zone. If the commander isn't there it can't be returned. This is correct behavior.

**Comment by propri** [comment]
That is not quite true.

[Conjurer's Closet](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430433)

> At the beginning of your end step, you may exile target creature you control, then return **that card** to the battlefield under your control.

The key part is that it doesn't refer to the exiled card, but to 'that card', which means it can track a commander, even if it goes to the command zone instead of into exile.

Compare with, for example, [Oblivion Ring](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=397760):

> When Oblivion Ring enters the battlefield, exile another target nonland permanent.
> 
> When Oblivion Ring leaves the battlefield, return **the exiled card** to the battlefield under its owner’s control.

Oblivion explicitly refers to the exiled card, and can't track a commander if it goes to the Command Zone instead of into exile.

Nephalia Smuggler also uses the phrasing of 'that card', same as Conjurer's Closet.

https://boardgames.stackexchange.com/questions/11568/can-conjurers-closet-be-used-to-keep-a-stolen-commander

**Comment by Dilnu** [comment]
That seems like a really pedantic ruling but I guess that's what the official judges have decided on.

**Comment by Dilnu** [comment]
Full list of cards that might need updating.
[] Acrobatic Maneuver
[] Angel of Condemnation
[] Astral Slide
[] Cloudshift
[] Conjurer's Closet
[] Essence Flux
[] Felidar Guardian
[] Flickerform
[] Flickerwisp
[] Galepowder Mage
[] Glimmerpoint Stag
[] Kaya, Ghost Assassin
[] Liberate
[] Long Road Home
[] Mistmeadow Witch
[] Nephalia Smuggler
[] Otherworldly Journey
[] Rescue from the Underworld
[] Restoration Angel
[] Roon of the Hidden Realm
[] Sentinel of the Pearl Trident
[] Siren's Ruse
[] Skybind
[] Turn to Mist
[] Vanish into Memory
[] Vizier of Deferment
[] Wispweaver Angel

**Comment by Slightlynobody** [comment]
This is dumb.
So if you Adarkar Valkyrie your comander, and then while the trigger is on the stack flash the commander back in, then somehow shuffle your commander in your library that rule says it will keep track of it and bring it back... So you look through your library and put it back on the battlefield with no shuffle action?

**Comment by Slightlynobody** [comment]
Public zone nevermind. My b.

**Comment by Dilnu** [comment]
@Slightlynobody So to clarify, if we're talking about Otherworldly Journey or another card where there's a delay between exiling the card and returning it if the card moves from the command zone it won't be returned. It will only return if it's still in the command zone. This doesn't apply to Conjurer's Closet because it exiles and returns the card as part of the same spell resolution, there isn't time for any player actions between the two events.

**Comment by JayDi85** [comment]
I checked and fixed most of the cards by 06b6e482a0a8c462846f087e870c460a434157ed (searched by code, not texts -- so some custom cards can be missed potentially). Must be ok now for most cards.

Potentially bugged cards that was fixed by commit:
* N1Starfighter.java
* Flicker.java
* Soulherder.java
* Cloudshift.java
* ConjurersCloset.java
* IllusionistsStratagem.java
* NephaliaSmuggler.java
* RuinGhost.java
* SirensRuse.java
* ThassaDeepDwelling.java
* WispweaverAngel.java
