### ISSUE TITLE
Rosheen Meanderer cannot pay for Flameblast Dragon's Effect

### ISSUE THREAD

**Issue by Woogachaka** [magefree/mage#5206]
[Rosheen Meanderer](https://scryfall.com/card/ima/206/rosheen-meanderer)'s "Tap: add 4 that can only be spent on costs with X in them" does not allow the mana to be spent on [Flameblast Dragon](https://scryfall.com/card/m12/133/flameblast-dragon)'s Triggered ability. This is incorrect.

**Comment by rystan** [comment]
I imagine this is going to be the case for all of the following cards as well:
https://scryfall.com/search?q=o%3A%22you+may+pay+%7Bx%7D%22&unique=cards&as=grid&order=name

My supposition is that the way these conditional costs are built into the individual card effects are not associated with the source in such a way that the Rosheen Meanderer's ability can see it.

Or to put it another way, this line of code:
https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/r/RosheenMeanderer.java#L86
must not find the cost (example: https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage.Sets/src/mage/cards/f/FlameblastDragon.java#L67 ) because it's defined inline and not linked to the ability (such as by AddEffectCost().

Or at least that's my theory.  Not sure how to fix it though.  I imagine, with regards to Flameblast Dragon, the ability would be a whole lot easier to code with DoIfCostPaid and DamageTargetEffect, if it weren't for the X in the conditional cost.

**Comment by JayDi85** [comment]
Fixed via 437861ec20434d5e50bf93a2a7b855f0e07ff657
