### ISSUE TITLE
Grasp of Fate does not return commander cards it exiled if they are in the command zone

### ISSUE THREAD

**Issue by Kerrus** [magefree/mage#5278]
As per the rules, if a card like grasp of fate or journey to nowhere exiles a commander, and its owner chooses to put it in the command zone, and the card *does not specify* which zone it retrieves it from, it will retrieve it from the command zone if it has not been cast since (ie: if it's still the same game object). This is different from cards like Oblivion Ring, which say 'return the exiled card' and thus directly refer to the zone the card is supposed to be in. 

This does not currently occur.

**Comment by JayDi85** [comment]
I checked and fixed most of the cards by 06b6e482a0a8c462846f087e870c460a434157ed (searched by code, not texts -- so some custom cards can be missed potencially). Must be ok now for most cards.

Potentially bugged cards that was fixed by commit:
* N1Starfighter.java
* Flicker.java
* Soulherder.java
* Cloudshift.java
* ConjurersCloset.java
* IllusionistsStratagem.java
* NephaliaSmuggler.java
* RuinGhost.java
* SirensRuse.java
* ThassaDeepDwelling.java
* WispweaverAngel.java
