### ISSUE TITLE
Grenzo, Havoc Raiser's ability doesn't tell which creature triggered it

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#5282]
When I attack with multiple creatures in a multiplayer game and cause combat damage to players while Grenzo, Havoc Raiser is under my control, then I'm being presented a window, asking me if I want to goad a creature or exile the top card of the library. However I have no information which creature triggered it and hence no idea which player it will affect until I'm asked to select a target creature or the ability is put on the stack.

**Comment by jeffwadsworth** [comment]
![examplegoaded](https://user-images.githubusercontent.com/1496996/49238014-259db700-f3c5-11e8-850e-c421ba63311b.jpg)
This is what it will look like once finished.

**Comment by derlhurgoyf** [comment]
Hi Jeff, thanks a lot for looking into this.
What would this look like when you attack two opponents with one creature each and deal combat damage with grenzo on the field? Can you tell which creature caused the current trigger?

**Comment by Zzooouhh** [comment]
Unfortunately I'm certain that this doesn't solve the problem. The problem happens because the very first thing that happens when Grenzo's ability is about to be put on stack is the modal "action window" (the transparent one where you pick a: goad b: exile), and at the moment this window pops up, you have no information about which player the effect relates to.

The least headache-inducing fix I can think of myself would be to make the ability non-modal, and to ask which mode to apply in the ability's init in the form of a player.chooseUse(...) decision dialog that would also relay the defending player's logname.

**Comment by JayDi85** [comment]
@Zzooouhh no, you can show that info. As example:
 * use `checkTrigger` and send `game.InformPlayers` to log info about damaged player (the best one);
 * use `checkTrigger` event to save info (e.g. player name) and show it later on GetRule or change effects texts (it's can be seen on stack);

Test result:
![shot_181130_004311](https://user-images.githubusercontent.com/8344157/49250749-15bfba80-f439-11e8-8bca-73a2cfad9b7f.png)

![shot_181130_004408](https://user-images.githubusercontent.com/8344157/49250752-19534180-f439-11e8-85f9-e53b08d7b457.png)

Source:
![shot_181130_004622](https://user-images.githubusercontent.com/8344157/49250863-6afbcc00-f439-11e8-9ba5-fe02280b4db4.png)

![shot_181130_004634](https://user-images.githubusercontent.com/8344157/49250872-6e8f5300-f439-11e8-848a-3b88d2be9152.png)

![shot_181130_004707](https://user-images.githubusercontent.com/8344157/49250884-7a7b1500-f439-11e8-95fe-b82cdb90ae69.png)

**Comment by JayDi85** [comment]
Fixed via e195bddf09bbc614a51fea2b87b1db13d918c9e5

![shot_190705_153300](https://user-images.githubusercontent.com/8344157/60720126-d90df180-9f3a-11e9-8a54-ab54e8b19a6d.png)
