### ISSUE TITLE
Thieves' Auction Commanders

### ISSUE THREAD

**Issue by HR19** [magefree/mage#5307]
In a 4-player Commander game, 3 commanders were in play.  Thieves' Auction was played, and we were given the choice to put our commanders in the command zone.  At least 2 of us chose that option, but instead our commanders were exiled and part of the Auction.

**Comment by Iwasrunningoutofnamesatthispoint** [comment]
thats how its supposed to be.
going into the command zone is a replacement effekt, thus the auction will get them from the commandzone.

there are multiple cards that work like this - for example guile. its not a bug.

**Comment by HR19** [comment]
We also have to remember that every time something changes zones, it is a new object.  If a creature with Undying gets exiled with its ability on the stack, it doesn't ETB from exile.

**Comment by emerald000** [comment]
Yes, but there are a list of situations where effects can track cards through zones changes. If Thieves' Auction said "each player choose one of those cards" instead, you would be able to get the commanders back from the command zone.

For a list of those situations, visit CR 400.7: https://yawgatog.com/resources/magic-rules/#R4007

**Comment by andrew-todaro** [comment]
Actually the effect _is_ working properly... for the old set of rules. This is the proper implementation for the prior ruleset under which temporary exile effects such as O-Ring could force a commander into the exile zone. The card does need to be updated, but this is _not_ a bug.

In line with this, anyone with a bit of spare time while working on this card may want to use parts of the current implementation in a search query in order to to find any other cards still in need of updating due to the above change.

**Comment by Zerrisx** [comment]
No longer a bug due to https://www.hipstersofthecoast.com/2020/06/rules-change-dies-triggers-will-work-for-commanders/.
