### ISSUE TITLE
Kethis graveyard ability bugged

### ISSUE THREAD

**Issue by jasc7636** [magefree/mage#5950]
Kethis allowes you to play legendary cards from your graveyard even if they are put into the graveyard after the ability was activated

**Comment by TMiguelT** [comment]
Hmm, looks like it's implemented as a `ContinuousEffectImpl`, rather than a `GainAbilityAllEffect`, which is wrong.

 https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/k/KethisTheHiddenHand.java compared to https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/d/DivergentGrowth.java

**Comment by theelk801** [comment]
`GainAbilityAllEffect` wouldn't work, it only applies to things on the battlefield. The issue was that I forgot to use `affectedObjectList`.
