### ISSUE TITLE
Chaos Orb

### ISSUE THREAD

**Issue by gunnim** [magefree/mage#5954]
Related to issue https://github.com/magefree/mage/issues/4870 and the fact that some players are recommending xmage as the solution to play old school online (f.x. [here](https://www.reddit.com/r/oldschoolmtg/comments/9ts28f/best_place_to_play_old_school_magic_online/)), I would like to look into solutions to implementing Chaos Orb.

My suggestions are the following:
 - If old school is selected during game creation, allow the creator to set a fixed percentage accuracy for chaos orb flips.

I assume many players will use video conferencing and perform a physical flip when required during game play. 
 - Therefore, if accuracy is disabled, instead a dialog will be displayed on chaos orbs abilities resolution, allowing the player to confirm or reject the effect based on the physical flip.

If this sounds agreeable I'm considering finding the time to implement it myself.

Edit - suggestions

**Comment by gunnim** [comment]
@jmharmon You don't think my suggestion and use case are reasonable? I saw the list but I assumed it would be up for discussion if a plausible solution would be offered.

**Comment by ketsuban** [comment]
The problem is that Chaos Orb's effect isn't "for each permanent, activate a random number generator and destroy it if the RNG says so" - it requires you to flip the physical card onto the table and destroy anything it touches. That's not something Xmage can even attempt to simulate because there is no notion of card placement on the table. Xmage can do some [pretty goofy things](https://github.com/magefree/mage/pull/5699/files) in order to allow silver-bordered cards to function, but it can't draw a rectangle on the screen and destroy anything that intersects it.

(Frankly, it's irresponsible for Old-School to allow dexterity effects, because it needlessly penalises those with motor problems. Ante at least is merely despised as a mechanic because it involves potentially giving your cards away.)

**Comment by sebastiandine** [comment]
Actually, most Oldschool communities agreed on an [erratered version of Chaos Orb](https://oldschool-mtg.blogspot.com/p/banrestriction.html) that can only hit a single target.

_1, Tap: Choose a nontoken permanent on the battlefield. If Chaos Orb is on the battlefield, flip Chaos Orb onto the battlefield from a height of at least one foot. If Chaos Orb turns over completely at least once during the flip, and touches the chosen permanent, destroy that permanent. Then destroy Chaos Orb._

In that case, the above concerns in terms of implementing a flip that covers multiple cards are obsolete. So in my opinion, this adjusted version of Chaos Orb can be implemented to Xmage with a fixed or configurable certainty.
It would be great to have Chaos Orb and maybe Falling Star (which also got an adjusted ruling) on Xmage as it is a format-defining card. Supporting it would draw many Oldschool players into playing on Xmage.

**Comment by Susucre** [comment]
Do you have actual data on how often the errated Chaos Orb destroy its target?
Any kind of simulation of falling is not happening, but we could errata one step further with a P chance to work on activation.

```
{1}, Tap Chaos Orb: Choose a nontoken permanent on the battlefield. Roll a d100, if the roll is XX or less, destroy the chosen permanent. Then destroy Chaos Orb.
```

**Comment by sebastiandine** [comment]
I like this idea. Actually, some people do a similar thing during webcam games: they roll a d20 and miss on 18+, which would be a 15% chance of missing the flip.

We could also refer to how [Forge implements the flip](https://github.com/Card-Forge/forge/blob/master/forge-game/src/main/java/forge/game/ability/effects/FlipOntoBattlefieldEffect.java
)

There, the flip is divided into two probability values: 85% success rate for the card to flip and 70% success rate for hitting its actual target. I think they chose this approach since their implementation of Chaos Orb is more traditional as it can hit more than one target and also a different card than the one that was actually targeted. But since they also chose 85% for the flip to be successful, which matches with the D20 solution mentioned above, I think a 15% chance of missing the Orb on a potential implementation on Xmage is sufficient.

**Comment by Susucre** [comment]
Alright I'm done to make some percentage version happen (although worded without any interaction with cards that care about dice rolls).

Re-opening the issue.

**Comment by sebastiandine** [comment]
Sweet, thx so much

**Comment by sebastiandine** [comment]
I am adding two common Oldschool'ish interactions that should be considered during testing:

1. When the activated Ability of Chaos Orb is on the stack, the tapped Chaos Orb can be destroyed (e.g. by a Disenchant). In this case, the ability on the stack fizzles as there is no Chaos Orb in play that could be thrown.
2. When Chaos Orbs is indestructible (e.g. via Guardian Beast), it is not destroyed after the throw (only tapped). This means the Chaos Orb can be activated every turn without destroying it.
