### ISSUE TITLE
Choosing a spell to cast automatically puts counter on Empowered Autogenerator

### ISSUE THREAD

**Issue by ashbc** [magefree/mage#5958]
When you control [Empowered Autogenerator](https://scryfall.com/card/c19/54/empowered-autogenerator), going to cast a spell puts a counter on it before targets are chosen and costs paid, allowing you to repeatedly select and cancel a spell to stack up counters on it.

**Comment by ashbc** [comment]
Additionally, activating the mana ability puts two counters on it, and Undoing that removes only one counter.

**Comment by Ozygando** [comment]
I've found that even clicking Done to end a phase adds a counter, and choosing not to pass when prompted due to floating mana adds yet another. So does tapping other permanents, activating activated abilities, paying with floating mana, even just idly clicking on the mana symbols without spending them. These extra counters that seem to be added with every action on the controller's part are affected normally by Doubling Season and Pir, Imaginative Rascal.
