### ISSUE TITLE
Not able to respond to sacrifice effect while in upkeep

### ISSUE THREAD

**Issue by RedStoner** [magefree/mage#6186]
While in my upkeep, an effect that caused me to sacrifice a creature on my upkeep (Sheoldred, Whispering One) caused me to target my only creature, my commander (Heartless Hidetsugu). This select creature to sacrifice triggered the moment I hit the upkeep and the moment the creature was selected, it was sacrificed. The commander has a tap ability which should allow me to respond and trigger before the sacrifice effect triggers off. I have been told by my fried that this has happened to him on several occasions under the same circumstances.

**Comment by JayDi85** [comment]
It's by design. You must activate commander's ability while trigger on stack, not on resolve (while it ask to sacrifice).

Auto-stop on new trigger and time to activate ability:
![shot_200115_040851](https://user-images.githubusercontent.com/8344157/72393807-74cfb400-374d-11ea-9e63-7cd8b6eb86ad.png)

Result:
![shot_200115_040904](https://user-images.githubusercontent.com/8344157/72393806-74cfb400-374d-11ea-88d7-adb27ab3ea0f.png)

**Comment by Zerrisx** [comment]
Not a bug.
