### ISSUE TITLE
Nightmare Shepherd mistriggering

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#6250]
Nightmare Shepherd seems to look back in time to trigger when it shouldn't.

Steps to reproduce:

1. Dryad of the Ilysian Grove (or any three-mana enchantment creature) and Enigmatic Incarnation on the battlefield
2. Sacrifice the Dryad to the Enigmatic Incarnation, and fetch a Nightmare Shepherd.

Expected outcome:
Nightmare Shepherd on the battlefield, no other triggers.

Observed outcome:
Nightmare Shepherd enters the battlefield and triggers off the Dryad dying, prompting me to exile the Dryad and get a Dryad token.

**Comment by jeffwadsworth** [comment]
![confirmed](https://user-images.githubusercontent.com/1496996/73615374-e3759400-45cc-11ea-8a9e-6b5a4baaae0b.png)

**Comment by Dilnu** [comment]
This happens because the two events are handled simultaneously and therefore to the game Nightmare Sheppard is already on the battlefield when the zone change event for the dryad is handled.

I think the correct solution here would be to handleSimultaneousEvents and applyEffects after the sacrifice but before we search up the resulting creature. That seems really hacky though. I'd really prefer another solution if anyone has any ideas.
