### ISSUE TITLE
Dreadful Apathy bug when Flickered during it second ability resolution

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6326]
608.2g. If an effect requires information from the game (such as the number of creatures on the battlefield), the answer is determined only once, when the effect is applied. If the effect requires information from a specific object, including the source of the ability itself, the effect uses the current information of that object if it's in the public zone it was expected to be in; if it's no longer in that zone, or if the effect has moved it from a public zone to a hidden zone, the effect uses the object's last known information. See rule 113.7a. If an ability states that an object does something, it's the object as it exists--or as it most recently existed--that does it, not the ability.

Currently, Dreadful Apathy will exile the last creature it enchants, not the first one.

**Comment by Zerrisx** [comment]
Actually, I think that's correct, per this ruling:

1/24/2020 | The creature that’s exiled is the creature Dreadful Apathy enchants as its last ability **resolves**.

Emphasis mine.

**Comment by emerald000** [comment]
There's 2 slightly different situations:

1- Activate Dreadful Apathy that is on Creature A. In response, cast Flicker of Fate on Dreadful Apathy. Enchant Creature B once it returns. Creature A should get exiled as it is a different Dreadful Apathy since it changed zones and the LKI shows Creature A being enchanted.

2- Activate Dreadful Apathy that is on Creature A. In response, cast Aura Finesse on Dreadful Apathy and move it to Creature B. Creature B should get exiled as it is the same Dreadful Apathy and is the currently enchanted creature.

**Comment by jeffwadsworth** [comment]
![ProofOfBug](https://user-images.githubusercontent.com/1496996/87856057-f281a180-c8e1-11ea-8d34-97dc90e84ebb.jpg)

**Comment by jeffwadsworth** [comment]
![2nd Example works](https://user-images.githubusercontent.com/1496996/87856150-a5ea9600-c8e2-11ea-94bf-01cbeb0c692b.jpg)

**Comment by jeffwadsworth** [comment]
The first example was the one I noticed.  Thus the bug report.

**Comment by xenohedron** [comment]
Reopening this as a tracker for some dev cleanup:
- [ ] Write tests for the two cases listed above, plus #11210 TapEnchantedEffect
- [ ] Use `source.getSourcePermanentOrLKI(game)` instead of the clunky logic from 79592d2
