### ISSUE TITLE
Allow the Launcher to support an already installed JRE (OpenJDK11+ with OpenJFX11+)

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6462]
This is particularly important to finish the migration to OpenJDK 11, as **all** Maven versions for OpenJFX require OpenJDK11+. (Read: OpenJFX8 is **not** on Maven.)

**Comment by allentiak** [comment]
@JayDi85 said:
> Also as JavaFX has been unbundled from the JDK it now needs platform specific binaries
> (https://gluonhq.com/products/javafx/) so that will have to be added to the launcher.

What about supporting an already installed OpenJDK 11+ in the launcher and dropping the bundled Oracle binary?
(Not to mention that even hosting that copy of Oracle's Java 8 outside their website might be illegal by itself...)

**Comment by JayDi85** [comment]
Yes, [launcher](https://github.com/magefree/Launcher) must be updated after migrate to OpenJDK. Current version supports only one java archive to download (so alternative fix: find openjdk+javafx bundle in one zip-file).

**Comment by Craigacp** [comment]
I don't know of a pure OpenJDK 11 binary which includes OpenJFX 11. Oracle's OpenJDK builds don't contain it, nor do AdoptOpenJDK's, or Amazon Corretto. 

You could investigate using jpackage to provide installers and binaries for the client and the server separately. This wouldn't require the users to download Java separately as the required bits of the JDK would be packaged in.

One other thing to consider is that given the launcher already downloads it's own Java, you could make it track the latest upstream Java and OpenJFX releases (i.e. currently 14, with 15 due in September). Once xmage has moved to Java 11 (i.e. past Java 9 with the modularisation of the JDK) each upgrade after that should be minimal or no effort. The libraries I maintain for various Java releases have only required updates to uptake a new Java release if a dependency was messing around with a class loader or reflection in a way it shouldn't have been doing. There have been numerous performance improvements and additional library and language features (e.g. [switch expressions](https://openjdk.java.net/jeps/361)) since Java 11, and things like [pattern matching](https://openjdk.java.net/jeps/375), [records](https://openjdk.java.net/jeps/8242303) and [sealed types](https://openjdk.java.net/jeps/360) are likely to arrive in the next few releases.
