### ISSUE TITLE
Clock misses ticks

### ISSUE THREAD

**Issue by marthinwurer** [magefree/mage#6481]
A game with an time of 30 minutes per player can take longer than an hour. This is problematic when holding tournaments. This was experienced during a long-running midrange grindfest match with lots of triggers. Spectators might have contributed to it too.

Edit: After looking a bit I found the GameController class, which looks like it handles the PAUSE_TIMER events and such. `Mage.Server/src/main/java/mage/server/game/GameController.java`. I'll start looking there.

**Comment by SpeedProg** [comment]
The game is only counting time where it waits for player input, during times where the game is doing things on it's own, like resolving spells, damage etc. and thereby updating the board, this time is not counted. Some of these actions can take significant amounts of time, so what you are seeing there is correct as far as the game implementation goes.

What you seem to want is a completely different kind of timer? It probably should not be too hard to implement this, but the question would really be what rules one would want to use to assign those times to specific players?

**Comment by marthinwurer** [comment]
Figuring out what MTGO does would be a good starting point. Other than that, I think a good heuristic would be to apply processing time to the player whose turn it is, because they're more likely to be the one interacting with the game state and causing the large amounts time spent doing computations.

**Comment by JayDi85** [comment]
XMage timer counts only player's feedback (e.g. waiting time for player's response). I don't think that server's calculations can take so much time.

BUT there are possible bug with wrong active player:
* player one cast spell;
* player two must response for some spell's dialog;
* but... timer counts for player one instead of two. So player two can cheat and wait until player one time off. And player two will win;
* related issue with that bug: #4349

I saw that bug long ago, but don't know -- is it actual or not in current version.

**Comment by JayDi85** [comment]
Related to slow or laggy connection, nothing to do with timers.
