### ISSUE TITLE
Tokens with "*" power and/or toughness don't show in card viewer

### ISSUE THREAD

**Issue by gp66** [magefree/mage#6527]
Tokens with "*" as power and/or toughness do not show in card viewer.
Examples are Dinosaur Beast and Shark from IKO and Elemental from THB. 
Their respective java files are DinosaurBeastToken, SharkToken and PurphorossInterventionToken.

I found the exception that prevents these tokens from being added to the token array but I have
no idea how to resolve the issue.

Mage.Client\src\main\java\mage\client\deckeditor\collection\viewer\MageBook.java
line 578 --> // Swallow exception

IKO exceptions:
`java.lang.NoSuchMethodException: mage.game.permanent.token.DinosaurBeastToken.<init>()
java.lang.NoSuchMethodException: mage.game.permanent.token.SharkToken.<init>()`

**Comment by JayDi85** [comment]
Real reason: some tokens don't have default constructor (without params). So that constructors must be added to it.

There are only 3 tokens with that problem:
* DinosaurBeastToken;
* PurphorossInterventionToken;
* SharkToken;

`VerifyCardDataTest.java` have special tests for tokens: `checkMissingTokenData`. Tokens have many problems, so that test disabled by default. But you can run it to find out constructor problems. Also I updated it in last commit (48049dbfc956f7d984709018eab5e140900081f0) to print all constructor problems at once. Example:
![shot_200507_205413](https://user-images.githubusercontent.com/8344157/81322362-eccb3c80-90a4-11ea-8228-8fbc4fff064b.png)

**Comment by gp66** [comment]
Thanks for the detailed explanation.
