### ISSUE TITLE
Creatures get +1/+1 when we cancel the cast of a spell.

### ISSUE THREAD

**Issue by ThomasArb** [magefree/mage#6618]
Creatures of one player get +1/+1 every time someone cancel the cast of a spell. I attached the logs of the game. The player who get the boost is Shimikado.

[20200608_125831_Commander Free For All_1.txt](https://github.com/magefree/mage/files/4745781/20200608_125831_Commander.Free.For.All_1.txt)

**Comment by 18ths** [comment]
Looks like the repeating effect was Force Of Virtue's static ability, which was earlier exiled and cast using Pako + Haldan. Its either a messed up interaction with those cards or a rollback issue. I'll check it later

**Comment by ThomasArb** [comment]
There was also a Mirrormade cast to copy Force of Virtue. Thank for the reply. I don’t have enough experience with the project to do it by myself :(

**Comment by jeffwadsworth** [comment]
It is related to the Mirrormade effect.

**Comment by 18ths** [comment]
Fortunately the problem has 100% reproduction rate. I found out (more or less) the source of those additional effects. This is probably a problem not only for pump effects but its easier to observe the issue this way - there is suprisingly small amount of enchantments where the effect can accumulate like that. I suspect we would have the same problem with theoretical cards that can grant stackable keywords like prowess or exalted. 

The first loop seems to be correct. Copy Effect seems to be applied only once, and the copied permanent does not have any additional abilities that are granting pump effect. The problem seems to be with this reloading part.

```
        List<ContinuousEffect> layer = filterLayeredEffects(activeLayerEffects, Layer.CopyEffects_1);
        for (ContinuousEffect effect : layer) {
            Set<Ability> abilities = layeredEffects.getAbility(effect.getId());
            for (Ability ability : abilities) { 
                effect.apply(Layer.CopyEffects_1, SubLayer.NA, ability, game);
            }
        }
        //Reload layerEffect if copy effects were applied
        if (!layer.isEmpty()) {
            activeLayerEffects = getLayeredEffects(game, "layer_1");
        }
```

After running this code, activeLayerEffects looks like that: (0 is original effect, 2 is copied effect, 3,4,5 and more are out error effects)

![layereffects](https://user-images.githubusercontent.com/13023067/85221889-dad4fd00-b3b7-11ea-9b97-a336d6de5f26.PNG)

**Comment by LevelX2** [comment]
> Fortunately the problem has 100% reproduction rate.

Can you create a test to reproduce?

**Comment by 18ths** [comment]
I could, probably. Does test framework support cases like that? (casting a spell, then immediately cancelling the cast)

**Comment by JayDi85** [comment]
Test framework allows you to cast spell normal way (put on stack and pay -- or not to pay if it additional pay with options to choose).

I don't think what the reason in cast cancel (with rollback). It can be related to permanent and copy (something try to adding same ability multiple times -- e.g. ability's id changed after every attempt; or miss layer checking in adding code).

In theory unit test can be written too (by `addCustomCardWithAbility` and custom cost with yes/no choose). 

@18ths 
If you report manual test here with step by step then I can help to write that unit test.

**Comment by 18ths** [comment]
Steps are quite simple:
- cast a random creature (to observe P/T changes)
- cast force of virtue (doesnt matter if using it's no mana cost ability)
- cast mirrormade (copy enchantment works too)
- cast a random spell, then cancel the cast. This causes the creature cast in 1 step to be +3/+3 (instead of +2/+2)

**Comment by 18ths** [comment]
Yup. Rollback to start of turn works too. (though only once - you cannot make the creature as big as you want, only grant one additional pump). To sum up:

TURN 1
- cast a random creature
- cast force of virtue (doesnt matter if using it's no mana cost ability)
- cast mirrormade (copy enchantment works too)
TURN 3
- in any step, rollback to the start of turn 3.

I'll post the test soon.

**Comment by 18ths** [comment]
I managed to fix the issue, though it feels a bit workaroundy. There was a problem with clearing temporary effects while rollbacks - probably it has something to do with a lot of deep copying while doing those rollbacks. Ability class seems to lack a proper equals() method, so after deep copy we weren't able to compare an ability saved in temporary effect ability set with an ability from set that we got from effectAbilityMap. 

Someone lately proposed integrating project lombok, maybe generating those enormous equals methods in several places would fix some problems regarding rollbacks?

**Comment by JayDi85** [comment]
You can use IntelliJ code inspection to find equals problem (maybe it have somthing related). Also you can use [Sonar Cloud to find bugs](https://sonarcloud.io/dashboard?id=JayDi85_mage)(I updated report few days ago).

**Comment by ThomasArb** [comment]
Can I close this issue ?

**Comment by JayDi85** [comment]
Yes, it was fixed.
