### ISSUE TITLE
Stoke the Flames and convoke

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#6636]
1.4.44V0-beta11

I can't cast Stoke the Flames via convoke ability. I click on the card but nothing happens

![image](https://user-images.githubusercontent.com/2553458/84580353-9f7d7180-adac-11ea-8632-e149a6454e9c.png)

**Comment by Grath** [comment]
Something broke with alternate mana payment costs; K'rrik no longer allows you to cast spells for life either, which is likely the same bug.

**Comment by jeffwadsworth** [comment]
I assume you are working on a different presentation of the ability.  When I select Stoke the Flames, if I have any colorless cost, I get a "Special" button.  I select this button and then select a creature to tap.  This correctly reduces the cost by 1 colorless mana.  So, it appears to work correctly, albeit a bit cumbersome.

**Comment by JayDi85** [comment]
Current version uses getPlayableAbilities to find all abilities allows to play. It uses available mana and other to calculates to find playable things. In old version getPlayableAbilities uses for card highlights and testing framework, e.g. user can try to activate non playable abilities and put it to stack to play. In most cases that put is useless (no mana to pay), but in rare cases it can work (double pay on tapped, special condition mana or special cost with choose dialog).

So it's possible that some abilities with hardcoded cost/mana can be broken (xmage can't to find it as playable). I don't research it yet, but it possible as one of that problem abilities.

**Comment by JayDi85** [comment]
Fixed via #6670.

Special mana now works fine and cards are visible as playable. It works fine in 99% But there are still bug with gains abilities like [Chief Engineer](https://scryfall.com/card/c16/86/chief-engineer):
* Artifact spells you cast have convoke.

It's like bloodmoon problem -- some gains abilities works with stack objects, so xmage can't look ahead and can't see that some cards on stack will gained Convoke or other abilities (mana or cost reduction). So that card will be unplayable until normal mana available.

If this is a popular problem with unplayable cards then report here or as new issue. There are special param to enable global workaround for that cards (xmage will work as old version -- allows to put card on stack without availebleable mana):
* `HumanPlayer.ALLOW_USERS_TO_PUT_NON_PLAYABLE_SPELLS_ON_STACK_WORKAROUND`
