### ISSUE TITLE
Light Up the Stage isn't free with Fires of Invention

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6671]
If I try to cast _Light Up the Stage_ for free with _Fires of Invention_, it ask me to paid {2}. 
I guess is a problem with the _Spectacle_ code that treat the rest of the cost as a tax or something

**Comment by Alex-Vasile** [comment]
The issue is that spectacle (and emerge, and surge, awaken, and disturb, and escape) all do the following:
https://github.com/magefree/mage/blob/9c85a8f7f34c4da3f4439a5d475680b6eb47c1a6/Mage/src/main/java/mage/abilities/keyword/SpectacleAbility.java#L32-L34

Which for Light up the Stage results in:
```
ManaCosts = "{R}"
ManaCostsToPay = "{2}{R}"
```

Which is a problem since casting a card with Fires of Invention goes through this call to figure out the new costs:
https://github.com/magefree/mage/blob/9c85a8f7f34c4da3f4439a5d475680b6eb47c1a6/Mage/src/main/java/mage/abilities/costs/AlternativeCostSourceAbility.java#L144

This ends up being a problem since `adjustCost` (which gets called by `reduceCost`) "subtracts" the mana in `ManaCosts` from that in `ManaCostsToPay` to calculate the new adjusted cost (plus potentially other adjustments):
https://github.com/magefree/mage/blob/9c85a8f7f34c4da3f4439a5d475680b6eb47c1a6/Mage/src/main/java/mage/util/CardUtil.java#L314-L317

Side note, the docstring for `getManaCosts` says "These returned costs should never be modified as they represent the base costs before any modifications".
Should the initializers for Spectacle and the like be calling .clear() on them then?

**Comment by awjackson** [comment]
You shouldn't be able to cast a spell for its spectacle cost at all with Fires of Invention. Spectacle and Fires are both alternative costs and you can only choose to pay one alternative cost at a time.

**Comment by awjackson** [comment]
Oh never mind, I see what the problem is. The copy constructor for AbilityImpl doesn't copy the field `manaCosts` because it's assumed to be immutable:
```
public AbilityImpl(final AbilityImpl ability) {
        this.id = ability.id;
        this.originalId = ability.originalId;
        this.abilityType = ability.abilityType;
        this.controllerId = ability.controllerId;
        this.sourceId = ability.sourceId;
        this.zone = ability.zone;
        this.name = ability.name;
        this.usesStack = ability.usesStack;
        this.manaCosts = ability.manaCosts;
        this.manaCostsToPay = ability.manaCostsToPay.copy();
```
So all the constructors for the various derived classes of `SpellAbility` that start with `super(card.getSpellAbility())` are actually clobbering the `manaCosts` of the ability they use as a "template".

Good catch!

**Comment by Alex-Vasile** [comment]
If manaCost is assumed to be immutable, and see my comment above about getManaCost(). Should these abilities be reworked to NOT change manaCost?

**Comment by awjackson** [comment]
No, the `manaCosts` of alternate spell abilities definitely need to contain the correct cost of that ability, not of the card's default `SpellAbility`.

We need to do one of two things:

- Copy `manaCosts` in the copy constructor of `AbilityImpl` (this is more foolproof, but has memory usage implications)
- **OR**, add a clean way to replace an ability's mana costs that does not have side effects on other objects, and use it everywhere `getManaCosts().clear()` is currently being used

**Comment by Alex-Vasile** [comment]
I can confirm that the first option fixes the problem.

I am not familiar enough with how the code (for example, what's the difference between manaCostToPay and manaCost, why do both get cleared, but manaCostsToPay not also get set to the spectacleCosts?).

So I don't know how to do option 2, but I also can't think of a way to have an object-varying manaCost that doesn't have the same memory usage implications that doing option 1 has.
