### ISSUE TITLE
Face down cards are rendered with special frames

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#6733]
![grafik](https://user-images.githubusercontent.com/2066790/85907571-3b2dc980-b812-11ea-9d89-9d4c0edc2f4b.png)

Situation before casting Ixidron

![grafik](https://user-images.githubusercontent.com/2066790/85907578-3f59e700-b812-11ea-9891-25b849fd4275.png)

**Comment by Grath** [comment]
+1, face-down cards are also being given special frames that they shouldn't be - gold frame for multicolored cards, and even more egregious is the land frame for a face-down land.
![Names redacted because they're real names](https://user-images.githubusercontent.com/1895280/93404235-a6a69680-f857-11ea-865d-7b4d706bb6d1.png)

**Comment by JayDi85** [comment]
All face down cards must use same frame style to hide the original card details. Nothing to do with it.

All other render artifacts and wrongly shown details fixed in #11873 and related commits
