### ISSUE TITLE
Ashcould Phoenix turned facedown due to ability still counts devotion

### ISSUE THREAD

**Issue by dylan1020** [magefree/mage#684]
I had a situation come up today where I had a Purphoros on the field and 5 devotion with an Eidolon and Phoenix. My opponent killed the Phoenix, but Purphoros still was "turned on".

**Comment by LevelX2** [comment]
Implemented a workaround to fix this problem.

Basic problem is that morphed or manifested face down creatures are not specifc cast as such creatures with relation to their basic card but instead its a cast of the origin card and their origin attributes and abilities are deleted from the dace down permanent by continuous effect.
So it happens that the devotion calculation already has to be done before the attibutes are removed, because the effects are in the same layer (e.g. Purphoros, God of the Forge type changing effect and Morph type changing. This leads to the wrong devotion calculation.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.  If we still have specific other issues with face down creatures, let's write those up separately.
