### ISSUE TITLE
Gruul Ragebeast ETB unclear who is fighting who, doesn't consider order of fights important

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6918]
[Gruul Ragebeast](https://scryfall.com/card/gtc/170/gruul-ragebeast) has an ETB ability:

> Whenever Gruul Ragebeast or another creature enters the battlefield under your control, that creature fights target creature an opponent controls.

Normally, it's pretty obvious what's meant by "that creature". However, if multiple creatures enter the battlefield at the same time (e.g., [Command the Dreadhorde](https://scryfall.com/card/war/82/command-the-dreadhorde), the XMage client does not give you enough information to stack the triggers or choose targets. Which creature is fighting which is very important, and the order the fights happen may also be relevant. However, all of the arrows and object identifiers only refer to Gruul Ragebeast, and the game auto-stacks these triggers as if the order does not matter. I have "Set order for your triggers automatically if all have the same text" enabled, but ideally the "text" wouldn't be the same for these fights.

[I recorded a video](https://youtu.be/XegUOjaAnJk) because it's kind of hard to see with screenshots. I reanimated Gruul Ragebeast and three other creatures. In this case, the order of fights doesn't really matter. But I can't even control it so that my small creatures fight even small creatures and my big creatures fight slightly smaller creatures.

**Comment by acabaca24** [comment]
> and the game auto-stacks these triggers as if the order does not matter

I had the same problem with 2 amulet of vigor and 2 lands entering at the same time. In my case I played a Primeval Titan and got boros garrison and slayer's stronghold, I put the boros garrison trigger to resolve last and it messed up all my tap/untap so I couldn't activate slayer's stronghold twice.
To work around this in my next games, I had to stack two amulet triggers(the ones from slayer's stronghold) at last, then the boros garrison trigger, and then the 2 amulet ones. It shouldn't be like that.

**Comment by JayDi85** [comment]
Gruul Ragebeast impoved by 9c56ff90d3fc557692f8688eaaa2b79a3d1efa34

![shot_201216_194501](https://user-images.githubusercontent.com/8344157/102371959-2ddee400-3fd8-11eb-86ac-ad338e0d6cb2.png)
![shot_201216_194555](https://user-images.githubusercontent.com/8344157/102371981-32a39800-3fd8-11eb-9b38-365a0a11d5ec.png)

**Comment by JayDi85** [comment]
Some triggered abilities uses special code to setup targets for effects (target pointer). As example: Amulet of Vigor uses `UntapTargetEffect` and setups target of that effect to triggered land. XMage don't show that type of targets on battlefield as arrows (that's why Gruul Ragebeast can't show you related objects).

I improved (a0a1dcb39fd1668b88bb32a794fb0403f84156f0) GUI to show additional target pointers and targets that was setup by effects. That's can help to see more related links and details in stack objects. 

Also I added triggered land name to Amulet of Vigor effect's name -- it allows to show triggers order dialog all the time. 

If you have another cards with same problem then report it here or as a new issue. Suspicious behaviour:
* card must able to generate multiple triggers;
* triggers result depends to resolve order, so you want to choose triggers order;
