### ISSUE TITLE
Surly Badgersaur fights up to one creature

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7032]
Surly Badgersaur, its 3rd triggered ability is "Whenever you discard a noncreature, nonland card, Surly Badgersaur fights up to one target creature you don't control."

When it's put on the stack you are asked to pick a target. As it resolves it fights the target creature, the user is not giving the option to not have it fight (or not target a creature to fight) at any stage.

**Comment by acabaca24** [comment]
Went to give it a quick test and this is what happened:

Cycled shark typhoon to trigger Surly Badgersaur:
![image](https://user-images.githubusercontent.com/61804801/91776178-c184d400-ebe4-11ea-85ba-7f50d14dafa4.png)

Clicked "Done" instead of my opponent creature because it's "up to one creature":
![image](https://user-images.githubusercontent.com/61804801/91776350-22aca780-ebe5-11ea-972f-62b317f8c813.png)

Let the ability resolve and neither of them fight:
![image](https://user-images.githubusercontent.com/61804801/91776387-3526e100-ebe5-11ea-8330-db3fe3fe9d1d.png)

So unless I got something wrong, the card works as expected.
Feel free to reply and I'll give it a try!

**Comment by johnmeat** [comment]
yeah sorry i thought the selecting of a creature was needed, Ill close.
