### ISSUE TITLE
Zoetic Cavern - difficulties casting as a morph

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#7160]
I have Kadena, Slinking Sorcerer to give me a free morph to play, I have Zoetic Cavern and Brine Elemental and I haven't played a land this turn, the Zoetic Cavern can be played i.e. is highlighted:
![image](https://user-images.githubusercontent.com/64497504/97778831-d2fd4480-1b71-11eb-9286-d9ad92171417.png)

Playing the Island, the Zoetic Caven is now no longer highlighted and cannot be played as a morph:
![image](https://user-images.githubusercontent.com/64497504/97778866-1eafee00-1b72-11eb-98e5-4f3c916f5e60.png)

Similarly Zoetic Cavern cannot be played as a morph at flash speed, below Vivien is giving flash and on the AIs end step, Brine Elemental can be played as a morph but Zoetic Cavern cannot be played as a morph:
![image](https://user-images.githubusercontent.com/64497504/97778997-199f6e80-1b73-11eb-8fee-5df0aefb78dc.png)

**Comment by weirddan455** [comment]
I wrote a fix to allow Vivien to cast Zoetic Cavern at instant speed.  However, while I was testing things, I came across several other bugs with morph.

1. Lumithread Field (enchantment card with morph ability) is not castable with Vivien at instant speed.
2. Steel Golem does not prevent casting Zoetic Cavern and Lumithread Field face down as morph.
3. Archon of Valor's Reach naming enchantment prevents casting Lumithread field as moprh.

These issues are all related to how morph is implemented.  Morph is implemented as an alternate casting cost so when the card type gets checked, it comes back as land or enchantment.  I was able to code in a workaround to allow morph lands to be cast as instant speed but these other bugs are a bit harder for me.

If I remove the isLand check for the fix I wrote, it lets Vivien cast both sides of Lumithread Field for example.  I'm wondering if the morph ability should be re-worked to work more like a split card or MDFC card so that we can have a morph "creature half" card object that we can use to check against cards like these.
