### ISSUE TITLE
Cards with multiple arts can appear 2+ times in a pack

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#7333]
Some of the older sets have cards that have multiple different arts. These cards can appear more than once in a pack.

Here's an example of a Fallen Empires pack with duplicates of Elvish Hunter and Elvish Scout.
![duplicates](https://user-images.githubusercontent.com/13901691/103785982-8851ea00-5044-11eb-8eb4-140a27da1950.png)

**Comment by sprangg** [comment]
Looks like the reason for this is that the booster creator considers the different art-versions separate cards.

I think the best solution would be that the getCardsByRarity function only returned one of the versions of each card with multiple art. This would make sure that these cards aren't more common in boosters than they should be, and that they can't appear multiple times in a single booster. https://github.com/magefree/mage/blob/577ab1aa9a583d12335e5534da45836e98d13342/Mage/src/main/java/mage/cards/ExpansionSet.java#L584

**Comment by JayDi85** [comment]
Related issue #7043

**Comment by sprangg** [comment]
The cards with multiple art have a tag, NON_FULL_USE_VARIOUS, that could be of aid in filtering them.
https://github.com/magefree/mage/blob/01e16e937fcdf5d9235651080f6d9d21c40efba4/Mage.Sets/src/mage/sets/FallenEmpires.java#L30

**Comment by JayDi85** [comment]
It's ok to have multiple cards with same name in one booster (see [that discussion from mtgsalvation](https://www.mtgsalvation.com/forums/magic-fundamentals/magic-general/554944-do-booster-packs-ever-contain-two-of-the-same-card)). But there were bug with cards ration in booster (multiple variants increase card's ratio) -- it was fixed in e48f024909f715535ad156666ba1558421ca9274.
