### ISSUE TITLE
Esika, God of the tree does not count as a legendary Creature

### ISSUE THREAD

**Issue by Xhael** [magefree/mage#7404]
Currently the tooltip for "Esika, God of the tree" states that she is a normal creature, not a legendary one. Therefore she cannot be chosen as commander for a normal commander game. Moreover, with her as my commander (in a freeform commander game), I was not able to cast either side of her from the command zone (probably related to the non-legendary status of her).

**Comment by weirddan455** [comment]
I reported this in #7370. It appears to affect all legendary MDFCs.

**Comment by alexander-novo** [comment]
The inability to cast Esika as your commander is due to the sources of her cast abilities being the "half" cards that make up the MDFC, while your commander is the MDFC itself, so their IDs do not line up. This also means that commander tax doesn't apply to MDFC cast abilities.

See for instance:

https://github.com/magefree/mage/blob/6e88c745a8096f1309b87ffb256304ee847dc685/Mage/src/main/java/mage/players/PlayerImpl.java#L1609-L1616

(why MDFC's can't be cast from command zone - this is also rather lazily written code that finds EVERY ability that can be activated in the game just to filter it by the object's ID)

https://github.com/magefree/mage/blob/6e88c745a8096f1309b87ffb256304ee847dc685/Mage/src/main/java/mage/abilities/effects/common/cost/CommanderCostModification.java#L43-L47

(why MDFC's don't have their cost modified by commander tax)

@JayDi85 These are the only issues I happened to notice while testing, but this pattern of comparing the source id to an object's id is very common - there are probably many more issues. Off the top of my head it seems like we should make the IDs of the two half cards of MDFC's the same as the MDFC itself, but I don't know if that would cause further issues?

**Comment by JayDi85** [comment]
@alexander-novo assign all mdf issues to me.

> this is also rather lazily written code that finds EVERY ability that can be activated in the game just to filter it by the object's ID

That's correct. You can't find object specific abilities without full game abilities request (reason: some abilities generated by another objects or effects).

> we should make the IDs of the two half cards of MDFC's the same as the MDFC itself

Nope, all cards/parts must be independent. This was done intentionally in order to exploit further mechanics like mutate. So all that bugs can help to find incompatible code (code what can't process a complex objects from multiple cards).

**Comment by weirddan455** [comment]
For what it's worth, I noticed this issue also affects other supertypes (ex. Snow.  A card I was testing that cares about Snow permanents from graveyard could not target MDFCs) so looking at code for commanders is probably not going to be helpful here.  The root of the issue is MDFCs not getting their supertypes assigned correctly.

**Comment by alexander-novo** [comment]
@weirddan455 The supertype issue is an easy fix. The `getSuperType()` function for MDFCs was overridden to never have any supertypes:

https://github.com/magefree/mage/blob/6e88c745a8096f1309b87ffb256304ee847dc685/Mage/src/main/java/mage/cards/ModalDoubleFacesCard.java#L151-L154

The other issues are a much deeper problem.

**Comment by JayDi85** [comment]
Fixed by 50e5809a791bb29944fd772406d8cc3eaa7f0478
