### ISSUE TITLE
Bloodthirsty Blade not attacking control in two player match (bug)

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#7466]
In a two player match Bloodthirsty Blade should attack (in order) controlling player's planewalker and then controlling player per the gatherer.  See 8/23/2019 errata.  

https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=470599

Currently in two player (not sure in EDH/MP as I don't play that) legacy it simply doesn't work .. doesn't "goad" attached creature nor an attack.

**Comment by weirddan455** [comment]
I've got a fix for this.  I asked a judge and goad doesn't force the creature to attack your planeswalker.  Opponent can choose to attack either you or your planeswalker in a 2 player game but it must attack.  I'm not seeing anything on the gatherer page that contradicts this ruling.

**Comment by peter-thoenen** [comment]
I could have worded that better, it doesn't force attack at all lol, neither PW or player

**Comment by weirddan455** [comment]
I see a re-open button right below the comment box.  Maybe you need committer permissions to do that though, not sure.  7da65b38b2ae3546877816941e5d65ed25ac2824 fixed the bug where it wasn't forcing the attack in a 2 player game.  I believe the fix is live now in the new stable release that came out the other day (as well as beta.)

If you're still having problems, you can comment here again and I'll re-open.
