### ISSUE TITLE
Feature Request - Dynamically scaling card objects on cluttered battlefield

### ISSUE THREAD

**Issue by billyg-da-great** [magefree/mage#7542]
I really don't want any new features, actually I think they caused this problem.

When you implemented the new ability icons, you must have removed the ability of card objects on the battlefield from scaling, because I get a scroll box for the opponent's field in every 2 player game now because the objects are all a fixed size.  This makes it so even though I have ability icons turned off, (as they add nothing to gameplay and are redundant information as I have to scroll over them to see what they mean, which shows an enlarged picture of the card, allowing me to read it, thus making them 100% redundant wasted UI space) I now get to scroll all the time just to see battlefield in a 2 player game.

The behaviour before was to have the objects become smaller on the board to accommodate more of them all in one view, without scrollbars ( at least in 2 player games ).  This is really nice for people playing on small laptops ( 1024x768 ) from having to use the mouse all the time to scroll scroll bars.  

In addition, when the window is full size on my screen (1024 x768, small I know) there is no scrollbar for your cards in hand any more.  This was the only scrollbar that was worthwhile in the whole program, as I have to resize my window now, and drag it off screen to see my 7 card hand.

All these things are new problems that had been solved for years, So I guess the feature request I'm asking for is for a toggle button in preferences that lets cards scale on the battlefield again ( maybe this requires ability icons off or something, that's fine they are useless). 

Thanks and sorry I'm an asshole but I'm clinically retarded and I love your program.

**Comment by JayDi85** [comment]
1. Show full screen screenshots with your problems (hand cards without scrolls)
2. Scrollbars on battlefield are not depends on card icons. Its a min and max permanent sizes from preferences -- sizes tab. So change min permanent size to make cards smaller and remove scrolls.

**Comment by billyg-da-great** [comment]
GUI Settings:
![settings_1024x768](https://user-images.githubusercontent.com/78831881/107470431-4410a880-6b20-11eb-9be4-16435cf4f011.png)

![image_settings_1024x768](https://user-images.githubusercontent.com/78831881/107471032-43c4dd00-6b21-11eb-8aef-3d8cf8a527d8.png)


Opening Hand at 100% fullscreen:
notice I have no option to scroll through my 7 card hand, which it used to do before this update
![opening_hand_fullscreen_1024x768](https://user-images.githubusercontent.com/78831881/107470722-b3869800-6b20-11eb-9c20-1d1512107df3.jpg)

Only way I can get a scroll bar to appear is to resize the window and move around the screen:
![resize_window_now_scrollbar_appears](https://user-images.githubusercontent.com/78831881/107471272-bfbf2500-6b21-11eb-8460-d14ea759b8b4.jpg)

In game once any meaningful number of permanents appear :
![great_more_scrolling](https://user-images.githubusercontent.com/78831881/107480772-fa30be00-6b31-11eb-8b85-a88312f50c6c.jpg)

All these permanents use to scale to even smaller sizes or stay on the same line, like chalice and lands.  Now I get a bunch of empty space i have to scroll over to see the battlefield.

Sorry about before I just mad about being bad and changes forcing me to buy a bigger monitor for my laptop.

**Comment by JayDi85** [comment]
1. It's an artifact and you are disabled the option to put it on same raw as creatures. That's why it have three rows (lands, creatures, other). Enable that option back -- you will get two rows. Start new game to apply that settings.
![shot_210210_122059](https://user-images.githubusercontent.com/8344157/107483399-752dbf00-6b9a-11eb-8e52-efde496b20ec.png)
![shot_210210_122120](https://user-images.githubusercontent.com/8344157/107483432-7e1e9080-6b9a-11eb-8882-f69924f96cd0.png)

2. Hand scroll bug related to dialog area size and window height (original bug #5605). As workaround you can make dialog area size much smaller from regedit (see below).
 
3. Card icons do nothing to permanent sizes. XMage logic: game try to show you all cards at the screen starting from maximum size. If it can't show then change card size to smaller and try again. Until it reach the minimum card size. After that it stops to change size and enable scrollbars. That logic works in old versions. Same logic in current version.

4. Follow [that instructions](https://github.com/magefree/mage/issues/4461#issuecomment-361108597) to change regedit values. You need:
* `gui/Card/Battlefield/Max/Size`
* `gui/Card/Battlefield/Min/Size`
* `gui/Feedback/Area/Size`
