### ISSUE TITLE
Long delay between actions

### ISSUE THREAD

**Issue by lehandroz** [magefree/mage#7590]
I was playing against AI to test Tergrid for EDH, then this happened.
Between my "pass priority" phases, the program seems to freeze for about a minute before going to the next trigger, taking a LONG time for a simple turn.

I took a screenshot and this seems to be a Server issue.
Anybody else having this issue?

![xmage freeze](https://user-images.githubusercontent.com/64132092/108051621-11b5fc80-7086-11eb-849d-0ed2de96730b.jpg)

**Comment by Invisible4ever** [comment]
I have the same issue

**Comment by Invisible4ever** [comment]
![xmage bug](https://user-images.githubusercontent.com/8517542/108227562-50a78900-713e-11eb-9f03-3139dd19af41.png)

**Comment by Invisible4ever** [comment]
Look at the Game log bottom left, where it shows that it is supposedly my turn, yet at the bottom middle, it shows the opp's turn ind combat.

**Comment by jeffwadsworth** [comment]
Some card effects are causing loops to occur that slow down the AI response time.

**Comment by Alex-Vasile** [comment]
> ![xmage bug](https://user-images.githubusercontent.com/8517542/108227562-50a78900-713e-11eb-9f03-3139dd19af41.png)

In general AI games are slow on the server because of the current nature of the AI. Some decks are much worse than others, token decks and decks with generate many options specifically.

Given this screenshot specifically, this is a known bug which is getting a fix: #7649.

As currently implemented (and until that bug and related PR are dealt with) Cascading Cataracts is particularly bad at slowing down the game.

**Comment by lehandroz** [comment]
My issue does not involve Cascading Cataracts at all (see screenshot). This is a general observation that AI takes too long between phases and "passing priority" for some unknown reason.

**Comment by Alex-Vasile** [comment]
> My issue does not involve Cascading Cataracts at all (see screenshot). This is a general observation that AI takes too long between phases and "passing priority" for some unknown reason.

The reason it takes so long is because it spends a lot of time testing out as many possible actions as it has time for.
Cascading Cataracts is just particularly bad (at the moment).

If you try playing on a local server (and give it several GB of memory) you should see significantly better performance than on the public servers.

Again some cards are much worse than others. Looking on EDHREC Tergrid seems to have a lot of reanimation and interactions with opponents. All of this will slow down the AI.

If there are any cards that you find especially bad, then those can be looked into. But beyond that there isn't anything actionable here for us to go on. (it's already known that the AI gets slow.)

**Comment by jeffwadsworth** [comment]
If you want to shorten the delay, always set the AI at level 1.  Any higher is a waste.
