### ISSUE TITLE
Draugr Necromancer doesn't work completely with MDFCs and Adventure spells

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7620]
Currently [[Draugr Necromancer]] doesn't allow snow mana with MDFCs and doesn't work at all with Adventure spells (but does work completely with the creature part). I've been working on this and I wrote a test but I'm stuck.

**Comment by weirddan455** [comment]
I got adventures working in 73f594583f24c3b542b236241743db1e229258ea

Needed to use main card ID in the zone check and your test was wrong (after casting "Treats to Share", Curious pair will still show in exile because it's now in the "Adventure Zone" and won't be in the graveyard.)

I did some debugging on the MDFC snow land problem and it's failing the check for counters:

`cardState.getCounters().getCount(CounterType.ICE) > 0`

I think it's an issue with MDFCs and the `CardState` object... just not sure where the counters are supposed to get updated there.

**Comment by JayDi85** [comment]
MDF card return counters from left card all the time: `public Counters getCounters(GameState state`

I think `boolean addCounters(` and `void removeCounters(` need override versions too (see `MeldCard` as example). Cause it needs adding counters direct to MDF card now.

**Comment by JayDi85** [comment]
@weirddan455 

If you want to fix MDF card then add a unit test for broken use case. Or describe it here and I'll add it tests later.

**Comment by weirddan455** [comment]
@JayDi85 There already is a unit test that @theelk801 wrote in f5f7638216bd258df3548e7c578f673237578604

It's just marked to Ignore for now because it's failing.

**Comment by theelk801** [comment]
Yeah, I should have added a TODO to those to make them more clear

**Comment by JayDi85** [comment]
There were many problems, see dda69cd009fbc80ad2c7112a946576385d984c73 for more details and fixes.

1. `Draugr Necromancer` uses card's LKI to find counters info from exile zone in the past (current zone: stack). Card's LKI don't support mdf/split/adventure parts. Fixed now (added LKI support).
2. MDF tests uses multi colored land [[Badlands]] with AsThoughMana combo. Test framework uses AI to auto-payment by default and it uses first multi colored ability (cause AsThoughMana effect applied to the casting object and AI think that it can pay any color by it). Fixed now (improved support of AsThoughMana for AI).

Now all tests and use cases with `Draugr Necromancer` works fine.
