### ISSUE TITLE
[Regression] Trample + Deathtouch not allowing player to assign damage correctly

### ISSUE THREAD

**Issue by Mikeyman88** [magefree/mage#7633]
When Ghalta soulbounded with Nightshade Peddler was blocked it still did whole thoughness of damage in the blocking creature instead of only one. This happened during the entire match, also after Ghalta died and returned on the battlefield.

**Comment by weirddan455** [comment]
It looks like Deathtouch + Trample in general is bugged, not just those specific cards.  When it prompts to assign damage, the lowest it lets you assign is the blocking creature's toughness.  It should let you assign 1 damage to the blocker since any damage with deathtouch is lethal and have the rest trample over to the player but that is not the case.

**Comment by Mikeyman88** [comment]
This worked in the previous version so the issue appeared after the last update.

**Comment by weirddan455** [comment]
OK, I just tested it and it broke in commit 5390963d38e2baa17e16c6e9644fcfa2c5ebec60

@theelk801 Do you know where in this commit might have caused this problem?  It's rather large and I'm not sure where the code that handles this is in the first place.

**Comment by theelk801** [comment]
I’ll look into it
