### ISSUE TITLE
Reflections of Littjara not copying kicker

### ISSUE THREAD

**Issue by Kryos257** [magefree/mage#7655]
Played Thieving Skydiver kicked for X=4, the copy did not allow me to take an artifact on ETB

**Comment by Pacchuu** [comment]
Copies of kicked permanents are not kicked.

The Gatherer rulings of Thieving Skydiver state: "If a card or token enters the battlefield as a copy of a permanent that’s already on the battlefield, the new permanent isn’t kicked, even if the original was."

**Comment by Alex-Vasile** [comment]
So the issue seems stop the effect from here:
https://github.com/magefree/mage/blob/e2f1743c6b75d053e991cec916acc7efa6cb7b80/Mage/src/main/java/mage/abilities/common/EntersBattlefieldTriggeredAbility.java#L42-L48

The kicker cost is properly copied, but this check fails.
For the original Skydiver, `event.getSourceId()` and `event.getTargetId()` are equal and they both point to the Skydiver permanent.
For the copy Skydiver, `event.getSourceId()` and `event.getTargetId()` are *not* equal. `event.getTargetId()` points to the Skydiver permanent token, but `event.getSourceId()` points to the Skydiver CARD.
