### ISSUE TITLE
Too much mana calculations on multiple Cascading Cataracts (game freeze)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7710]
1x [[Cascading Cataracts]] card can slow down the game, 3x cards can freeze it.

Search problem code by `TODO: research too many manas and freeze`  (fbb08ab1a82bac3311cc47b3f74606ad25f17fbb).

Just put the card to battlefield to reproduce game freeze:
```
battlefield:Human:Cascading Cataracts:1
```

Related #7649

**Comment by Alex-Vasile** [comment]
So I looked into this a little more and found the following:

Method (CPU Usage, Memory Usage)

forceManaDeduplication (32.2%, 9.6%)
isExistingManaCombination (10.4%, ~0%)
getPossiblePayCombinations (8.4%, 49.4%)

The high CPU usage for forceManaDeduplication is the double for-loop labelled in https://github.com/magefree/mage/commit/fbb08ab1a82bac3311cc47b3f74606ad25f17fbb. This loop is needed since ManaOptions is using an ArrayList rather than a Set or dictionary (duplicated must be manually found and removed). This might be improved by not adding the duplicates in the first place.

The high memory usage is due entirely to the use of Strings to represent the Mana for most of the internal calculations of subtractCostAddMana. Essentially all of the memory usage goes to creating the StringBuilders.

**Comment by the-red-lily** [comment]
> The high memory usage is due entirely to the use of Strings to represent the Mana for most of the internal calculations of subtractCostAddMana. Essentially all of the memory usage goes to creating the StringBuilders.

Is this part resolved or still an issue?

**Comment by the-red-lily** [comment]
Is it possible to change the calculations to use vectors instead of strings? It seems like that'd be more efficient

**Comment by Alex-Vasile** [comment]
> > The high memory usage is due entirely to the use of Strings to represent the Mana for most of the internal calculations of subtractCostAddMana. Essentially all of the memory usage goes to creating the StringBuilders.
> 
> 
> 
> Is this part resolved or still an issue?

This is still an issue. #9068 fixes the slowdown by for cards that produce any color by using the build-in support for any color mana.

But the actual algorithm is untouched and still has those isues.

**Comment by Alex-Vasile** [comment]
> Is it possible to change the calculations to use vectors instead of strings? It seems like that'd be more efficient

It should be possible. The string comes in here: https://github.com/magefree/mage/blob/5e26066b24227ba4ca8159e9c6f4290656bdbc87/Mage/src/main/java/mage/abilities/mana/ManaOptions.java#L501
