### ISSUE TITLE
"Your deck contains <...>. The creator of the table has requested no <...> cards to be on the table!"

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7771]
I've run into this issue where I create a table and someone tries to join, but it tells them that they can't because some color of card is disabled. But I can't find such a setting in the table creation menu, so I wouldn't even know how to make it do that.

Then, when I tried creating a new table with the same settings that I always do - it happened to me - the table's own creator:

![image](https://user-images.githubusercontent.com/11657716/115967552-15cc2380-a4e8-11eb-88f0-89dbeb66a87e.png)

I tried several things - even restarting the client AND the launcher. But the issue persists, so I cannot create a new table right now (with green cards in my deck).

I can join a game with the same deck, though.

**Comment by Grath** [comment]
This is probably caused by your setting of EDH Power Level in the top right; from what I can see in the code, the EDH power level rating appears heavily arbitrary and the code involved with EDH Power Level is what can cause these error messages about not allowing certain colors. If you set that to 0, it should allow any decks in your table (for better or worse.)
