### ISSUE TITLE
Thassa, Deep-Dwelling doesn't give players the option to move their commander back to the command zone when flickering if the commander isn't owned by Thassa's controller

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7799]
Just played a game where someone stole my commander using [[Treachery]] then flickered it with [[Thassa, Deep-Dwelling]] (and then flickered it several times after), but I was never given the option to return my commander to the command zone.

**Comment by theelk801** [comment]
This is due to a [change in the rules](https://mtgcommander.net/index.php/2020/06/07/june-7-announcement-on-dies-triggers/) regarding how commanders leave the battlefield. If it goes to the graveyard or exile then it won’t replace the event but will instead ask to move it to the command zone when state based actions are carried out.

**Comment by alexander-novo** [comment]
Oh right, I forgot state-bade actions aren't checked in the middle of effects resolving. I was too used to [[Aetherling]]-style effects. Thank you.
