### ISSUE TITLE
Priority issues for the non-active player

### ISSUE THREAD

**Issue by nazimasgarov** [magefree/mage#784]
First of all, thanks to everyone who has made this awesome software possible. Very good work indeed! :)

I don't know if this is relevant at all, but I use XMage on a Mac. 

Now, on to the bugs:

1) When my opponent attacks with any number of creatures which have no triggered abilities, if he doesn't play any spells or abilities during combat, I don't get a chance to play any spells or abilities myself before the end of combat. A few examples:

- I blocked with a Butcher of the Horde and a Soldier token. The token was going to die anyway, so I wanted to sacrifice it to the Butcher, but XMage skipped directly to the second main phase.
- My opponent attacked with a Polukranos and, after attacking, monstrified it to kill my Nymaret to leave me no chance but to block with my Nyx-Fleece Ram. When he monstrified it, I had a chance to play spells and abilities, but didn't. My plan was to block with my Nyx-Fleece Ram, then play Arcbond targeting it to kill all creatures... but couldn't do it because, after blocking, I didn't get a chance to play spells or abilities. No "Done" button, nothing. The poor Ram died to a giant Hydra without being able to have its revenge :(

2) My opponent played a Whisperwood Elemental during his second main phase. I wanted to use priority before the manifest trigger at the end of turn to Utter End the Elemental, but somehow I didn't get priority during the second main phase. The Elemental entered the battlefield and it triggered immediately.

That's it for now. Will keep you posted about any other bugs I find, but rest assured you have a very happy user here! :)

**Comment by emerald000** [comment]
There are two possible causes to that problem.

1- If you use a skip priority button (F4/5/7/9/10 or the buttons on the bottom right of the battlefield), you won't get priority between phases. You will only get priority when an opponent casts/activates something (and not even then for F9). So if you intend to cast something while the stack is empty, you must not use them.

2- You also need to have a stop set during the phase you intend to cast your spell. You will not get priority otherwise (other than Declare Attackers/Blockers/Damage Steps in which you always have). If you click on the phase bar, the options will open and you will be able to choose them. For example, in your second example, you would need a checkbox in second main phase on your opponent's turn.

**Comment by nazimasgarov** [comment]
Thank you for the fast answer! Although I've been a little too trigger happy with the skip priority buttons, I tend not to use them when I have available lands (whether I want to do something, like playing Arcbond, or not). You might be right, though. I'll check and get back to you as soon as I can.

Thanks for your good work again :)

**Comment by LevelX2** [comment]
Probably handling problems, so closed.
