### ISSUE TITLE
[STX] Jadzi's second ability lets you pay 1 instead of all costs rather than just mana cost

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7853]
[[Jadzi, Oracle of Arcavios]] lets you cast cards without paying their additional costs, such as with [[Harrow]] and "As an additional cost to cast this spell, sacrifice a land." Contrast this with cascade, which forces you to sacrifice a land to cast it.

**Comment by jeffwadsworth** [comment]
Just a note here on the one card causing an issue with this "additional cost" implementation.
[[Extus, Oriq Overlord]]
The cost reduction of the right-side sorcery will cause the client to freeze during the pay 1 mana part.
Looking for the root cause of this issue.  It appears to be related to:
controller.setCastSourceIdWithAlternateMana().
This is not handling the cost-reduction of Awaken the Blood Avatar.

**Comment by jeffwadsworth** [comment]
Ok, now that I am using another computer, it works fine.  Dude...okay, disregard the above statement.
