### ISSUE TITLE
Draft packs are being passed right->left->right, table image shows them being passed left->right->left

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#8075]
Since the 1.4.49v1 update drafts packs are being passed backwards, going right->left->right instead of the traditional left->right->left. However, the table image still shows them passing left->right->left.

I believe the bug causing them to be passed in the wrong direction is here...
https://github.com/magefree/mage/blob/06ae494c5b0695d8a5ca8af5bf7b97abfb4fbf85/Mage/src/main/java/mage/game/draft/BoosterDraft.java#L27-L31

... as `((boosterNum + 1) % 2 == 1)` would be false for odd numbered packs.

(That function starts counting boosters from 1, other places seem to count from 0... very confusing!)

**Comment by JayDi85** [comment]
Fixed by 65761b085f9c72187e4b4b7eefe161e23c12cd98

**Comment by JayDi85** [comment]
Report:
> I just passed two Vulshok Sorcerers to my leaderboard finals competitor that I thought I was passing to another guy lol
a persistent little bug
> yes this is screenshot from p1p1. and I got my next pack from Dirty_Mac
![shot_210903_003136](https://user-images.githubusercontent.com/8344157/131912028-4683bbdc-c9ee-4bfe-ac37-4bcc0c557eae.png)

**Comment by sprangg** [comment]
For reference
my picks: https://magic.flooey.org/draft/show?id=Qtu3toKcKUvzsAJi7_6Wfde7eZc
Dirty_Mac's picks: https://www.magicprotools.com/draft/show?id=ikYl4YKVai8icfFRv29apsh_jD4&deck=ahRzfmV1cGhvcmljLWRpb2RlLTYxNnIRCxIEZGVjaxiAgICZ1M6NCQw

**Comment by awjackson** [comment]
#65761b0 reversed the logic for the actual pick order but it *also* reversed the logic for selecting the image file to use, so they're still backwards with respect to each other.

The underlying problem is that the two image files are misnamed! table_left.png depicts arrows pointing counterclockwise and table_right.png depicts arrows pointing clockwise. The names should be the other way around.
