### ISSUE TITLE
Screeching Bat stay's a 5/5 when transformed into flier

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8185]
[[Screeching Bat]] keeps its statline when you transform it back into a flyer.

**Comment by awjackson** [comment]
FWIW Screeching Bat is the only card in xmage that directly calls `permanent.setTransformed`.

The underlying bug is that when permanents transform from day side to night side their base power and toughness automatically get updated to the night side values, but when they transform from night to day they aren't automatically updated. `TransformSourceEffect` works around this for e.g. werewolves by updating power and toughness itself:

```
if (sourcePermanent.isTransformed()) {
                            Card orgCard = game.getCard(source.getSourceId());
                            sourcePermanent.getPower().modifyBaseValue(orgCard.getPower().getValue());
                            sourcePermanent.getToughness().modifyBaseValue(orgCard.getToughness().getValue());
                        }
```

But when a permanent transforms from night to day and it isn't via an ability that goes through `TransformSourceEffect`, it retains the night side base P/T.
