### ISSUE TITLE
Casting Diabolic Revelation for X=0 allows you to search for any number of cards

### ISSUE THREAD

**Issue by adoukimskywalk** [magefree/mage#8533]
If a cast Diabolic Revelation with Bolas's Citadel I can draws my entire deck !!  The cards draws is supposing to be 0.

!ruling 5 Bolas's Citadel
 If you cast Revelation without paying its mana cost, in this case by paying life equal to its mana value instead, X is automatically 0. So you'd search for 0 cards.

good day

**Comment by awjackson** [comment]
This doesn't just happen with cast-without-paying effects, it also happens if you cast [[Diabolic Revelation]] normally from your hand and you choose X=0.

The problem is that in the `TargetImpl` class, a `maxNumberOfTargets` field value 0 is treated as a magic number meaning "any number of targets".

**Comment by jeffwadsworth** [comment]
A workaround similar to this may work for it.

https://github.com/magefree/mage/commit/aa4397dee5b76198c9145a6221a3c5c026e60281
