### ISSUE TITLE
Ghastly Mimicry and Katilda's Rising Dawn bug when cast from the graveyard via Disturb.

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8572]
![image](https://user-images.githubusercontent.com/63882410/150545213-bc5cf072-f638-4655-ba0f-87c6c5f7aaf0.png)

**Comment by dashosa** [comment]
Same is true for Katilda
![image](https://user-images.githubusercontent.com/63882410/150621968-95d8ba66-08d9-4ffb-badf-fed79173c798.png)

**Comment by jeffwadsworth** [comment]
[[Ghastly Mimicry]]

**Comment by jeffwadsworth** [comment]
[[Katilda's Rising Dawn]]

**Comment by Alex-Vasile** [comment]
I think the issue is that the back-side of these cards are Auras. The player is supposed to specify a target when they cast the spell (I guess in this case when they use the Disturb ability.). But the player never does. So as soon as it hits the battlefield the Aura gets moved to the graveyard (which is replaced to the exile by the card's text) by a state based action.

You can confirm by putting a breakpoint here:
https://github.com/magefree/mage/blob/26a2e0a5edf47bbb1a03a650f29f9d712adf7722/Mage/src/main/java/mage/abilities/common/PutIntoGraveFromAnywhereSourceAbility.java#L122

And if you go down the stack you'll find yourself here:
https://github.com/magefree/mage/blob/26a2e0a5edf47bbb1a03a650f29f9d712adf7722/Mage/src/main/java/mage/game/GameImpl.java#L2349
![debug](https://user-images.githubusercontent.com/48962821/150892904-b1352321-897c-4b79-9635-15a5265fd04b.png)

The player needs to choose a target for the aura before it gets put onto the stack.

**Comment by jeffwadsworth** [comment]
This is related to the card being cast from the graveyard and not being recognized as an aura.  By the time it is a permanent, it is too late.  I will check the spell code...it apparently is not picking up the aura type.  Just busy as usual like the rest of us.

**Comment by jeffwadsworth** [comment]
The attached change fixes the issue, but perhaps the Disturb mechanic coder would know of a better solution.  The issue is due to the "transform" taking place too late in the process...when the card is actually put onto the battlefield.  This "fix" sends the correct spellAbility for processing.
![FixExample](https://user-images.githubusercontent.com/1496996/151250919-e0434547-64f6-4106-8ec6-3e28e2e8ee24.png)

**Comment by jeffwadsworth** [comment]
Of course, you will need a null check for the secondface, though I can't recall anything that would fail this check.  Disturb cards always have a secondFace to my knowledge.

**Comment by Alex-Vasile** [comment]
@awjackson you had some comments on the the other, any input on the above proposed solution?

@weirddan455 you worked on the Disturb mechanic previously. And input the proposed solution above?

**Comment by weirddan455** [comment]
I don't think any of my code for Disturb made it in.  You can see history in #8201.  I wrote up some initial code but there was problems with it and theelk and jaydi ended up re-writing nearly all of it.
