### ISSUE TITLE
Combat Calligrapher triggers but token is not created

### ISSUE THREAD

**Issue by Kamikauyami** [magefree/mage#8580]
Three player commander game, person not controlling combat Calligrapher attacks other person not controlling Combat Calligrapher the ability triggers but the token does not get created.

**Comment by Alex-Vasile** [comment]
If however Computer3 has the Calligrapher, then I get your scenario.
![Attack 2](https://user-images.githubusercontent.com/48962821/178749742-ad022e6b-ed89-45b6-a194-c77e1fd0c66d.jpg)

The ability should not create a token for the Human player since they are outside the range of influence of Computer3.

But I am not sure if the ability should trigger *at all* since the Human player is outside the range of influence.

**Comment by Alex-Vasile** [comment]
801.7. A triggered ability doesn’t trigger unless its trigger event happens entirely within the range of influence of its source’s controller.
Example: In a game in which all players have range of influence 1, Alex is seated to the left of Rob. Rob controls two Auras attached to Alex’s Runeclaw Bear: One with the trigger condition “Whenever enchanted creature becomes blocked,” and one with the trigger condition **“Whenever enchanted creature becomes blocked by a creature.”** Alex’s Runeclaw Bear attacks the player to Alex’s left and becomes blocked. The ability of Rob’s first Aura triggers because the entire event (Runeclaw Bear becomes blocked) happens within Rob’s range of influence. **The ability of Rob’s second Aura doesn’t trigger, however, because that event includes the blocking creature, which is out of Rob’s range.**

I think this means that combat calligrapher should not trigger since only the blocker is within Combat Calligrapher's owner's range of influence, the attacker is not.

**Comment by Kamikauyami** [comment]
But if you cannot replicate thats ok and you can closse this issue. It has been a bit.

**Comment by Alex-Vasile** [comment]
> But if you cannot replicate thats ok and you can closse this issue. It has been a bit.

I am able to replicate, see my post above. It happens for sure in that scenario (attacker of influence but defender inside).

I will also test to see what happens if both are inside the range of influence.

**Comment by Alex-Vasile** [comment]
> > 801.7. A triggered ability doesn’t trigger unless its trigger event happens entirely within the range of influence of its source’s controller.
> > Example: In a game in which all players have range of influence 1, Alex is seated to the left of Rob. Rob controls two Auras attached to Alex’s Runeclaw Bear: One with the trigger condition “Whenever enchanted creature becomes blocked,” and one with the trigger condition **“Whenever enchanted creature becomes blocked by a creature.”** Alex’s Runeclaw Bear attacks the player to Alex’s left and becomes blocked. The ability of Rob’s first Aura triggers because the entire event (Runeclaw Bear becomes blocked) happens within Rob’s range of influence. **The ability of Rob’s second Aura doesn’t trigger, however, because that event includes the blocking creature, which is out of Rob’s range.**
> 
> I think this means that combat calligrapher should not trigger since only the blocker is within Combat Calligrapher's owner's range of influence, the attacker is not.

If this interpretation is correct. Then several cards will need to be redone, e.g. [[Jolene, the Plunder Queen]]

**Comment by Kamikauyami** [comment]
I think this interpretation is correct as far as I can tell. I thank you very much for your work!
