### ISSUE TITLE
Vivien, Monster's Advocate takes top of deck Precedence to Bolas Citadel, not allowing for life-paid creature casting

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8584]
Vivien, Monster's Advocate take top of deck Precedence to Bolas CItadel, not allowing for life-paid creature casting

**Comment by Alex-Vasile** [comment]
[[Vivien, Monsters' Advocate]] [[Bolas's Citadel]]

**Comment by Alex-Vasile** [comment]
Was Vivien played after Bola's? If so, isn't Vivien's effect supposed to override Bolas'?

**Comment by emerald000** [comment]
If multiple effects allow you to cast a spell, you have to choose which effect you are using. Therefore with those two cards on the battlefield, you may either cast a creature from the top of your library normally with Vivien, or pay life with Bolas's Citadel.

**Comment by Alex-Vasile** [comment]
Alright, so I think the issue is with `getPlayableFromObjectSingle` or `asThough` (depending on the intent of the code).

`getPlayableFromObjectSingle` is calling `asThough` to find if **anything** is allowing the card to be played.
https://github.com/magefree/mage/blob/13baf726e914c42ccc585b1cc3d8a642f53413fc/Mage/src/main/java/mage/players/PlayerImpl.java#L3839

`asThough` is returning **the first** AsThoughEffect that allows a a given spell to be cast.
https://github.com/magefree/mage/blob/26a2e0a5edf47bbb1a03a650f29f9d712adf7722/Mage/src/main/java/mage/abilities/effects/ContinuousEffects.java#L511

I've tested this, and if you play Bolas first then you can use it's ability, but if you play Vivien first you will only be able to use her's.

It should probably be returning a list of all approving objects and the player picks which ability to use. The choice probably doesn't matter in most cases, so the choice should probably be made automatically if it doesn't matter (but I don't know where to start on figure out "if the choice doesn't matter").

**Comment by Alex-Vasile** [comment]
I think this is the same issue as #2087
