### ISSUE TITLE
There are several functions inside Commander.java which are empty

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8661]
Several functions have an `@Override` but are simply empty:

https://github.com/magefree/mage/blob/5945aaeda467b3407de4e7b13612009318bca273/Mage/src/main/java/mage/game/command/Commander.java#L128-L130

https://github.com/magefree/mage/blob/5945aaeda467b3407de4e7b13612009318bca273/Mage/src/main/java/mage/game/command/Commander.java#L168-L170

https://github.com/magefree/mage/blob/5945aaeda467b3407de4e7b13612009318bca273/Mage/src/main/java/mage/game/command/Commander.java#L272-L282

https://github.com/magefree/mage/blob/5945aaeda467b3407de4e7b13612009318bca273/Mage/src/main/java/mage/game/command/Commander.java#L322-L334

There's no comment indication if this is intentional or not. See for example #8660 which caused issues with Changeling commanders.

**Comment by JayDi85** [comment]
Some commands must never be called for that type of object. It must raise exception, but just empty. Command object is very specific and it replaced by permanent on battlefield. So your code example must be researched for real reason and fixed.

**Comment by Alex-Vasile** [comment]
I don't understand the last sentence.

**Comment by awjackson** [comment]
I'm pretty sure the bugs listed in the linked PR are all related to `IsAllCreatureTypesSourceEffect.apply`:

```
@Override
    public boolean apply(Game game, Ability source) {
        MageObject sourceObject = game.getObject(source.getSourceId());
        if (sourceObject == null) {
            return false;
        }
        sourceObject.setIsAllCreatureTypes(game, true);
        return true;
    }
```

`ChangelingAbility` is implemented as an ability with `IsAllCreatureTypesSourceEffect` that is active in all zones (in fact `ChangelingAbility` is the only thing in xmage that uses `IsAllCreatureTypesSourceEffect`). Because the ability is active in all zones, the object returned by `game.getObject(source.getSourceId())` could be almost any subclass of `MageObject`--e.g. a `Card`, a `Permanent`, a `Spell` or a `Commander`. When `IsAllCreatureTypesSourceEffect.apply` is called for a source object that is a commander card in the command zone, that object's `Commander.setIsAllCreatureTypes` ends up getting called... and that method does nothing.

The only thing that slightly confuses me is that `IsAllCreatureTypesSourceEffect` *does* work for spells on the stack, even though the `Spell` class also has a no-op override of `setIsAllCreatureTypes`. Spells that have changeling do correctly trigger cards like [[Lys Alana Huntmaster]] and correctly are untargetable by [[Faerie Trickery]]. I'm not quite sure why it works for spells on the stack but not for commanders in the command zone.

I believe there are two possible ways to fix the commander changeling bugs:

1) Implement `Commander.setIsAllCreatureTypes(Game game, boolean value)` as a passthrough to `sourceObject` (like how `updateZoneChangeCounter` and `setZoneChangeCounter` are implemented)

2) **OR**, change `IsAllCreatureTypesSourceEffect.apply` so that it doesn't blindly call `setIsAllCreatureTypes` of an unknown `MageObject` (perhaps using a `MageObjectAttribute` for cards that aren't on the battlefield?)

I'm not sure which fix is preferable (but copypasting `MageObject` method implementations into `Commander` is definitely not right!).

**Comment by Alex-Vasile** [comment]
I understand. I missed the sourceObject calls. I updated the PR to include that solution (option 1).

The on-stack behaviour you describe is strange

**Comment by Alex-Vasile** [comment]
Were there comments added for why the above functions should be empty? 

For example, why does `setStartingLoyalty` do nothing versus calling `SourceObject.setStartingLoyalty(startingLoyalty)`? 

Same for all of the others.

**Comment by awjackson** [comment]
At least some of these `MageObject` interface methods (e.g. `adjustCosts`, `adjustTargets`) are relics that shouldn't exist at all anymore--they were refactored some time ago into the `CostAdjuster` and `TargetAdjuster` classes. I'll look at cleaning them up after the next release.
