### ISSUE TITLE
Draft tournament with only AI eliminates the AI

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8814]
Trying to start a tournament with me an 7 other AIs causes the AI to be auto eliminated after I submit my deck.
Settings:
- Tournament Type: Booster Draft Swiss (Cube)
- Draft Cube: Mono Blue Cube
- Players: 10 (me + 9 AI)

**Comment by awjackson** [comment]
There are two different AIs. "Computer - draftbot" is for practicing/testing drafting--it automatically drops from tournaments after the draft. "Computer - mad" is the one that actually plays games.

Also, AI players are typically disabled on public servers because they consume a large amount of server resources. Connect to a localhost server if you want to play against AI.

**Comment by Alex-Vasile** [comment]
Thanks! I had assumed that draftbot is the one I wanted for the draft tournament given it's name.

(This was being done on a local server)
