### ISSUE TITLE
Jegantha, the Wellspring lets you use WUBRG mana for anything

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8844]
[[Jegantha, the Wellspring]] is only supposed to let you use the mana it makes for colored (non-generic) costs. XMage lets you use it for generic costs as well.

**Comment by jeffwadsworth** [comment]
Note that the controller must pay down the generic mana first before using the conditional mana generated by Jegantha.  Closing this for now.

**Comment by ssk97** [comment]
Just some extra details since I spent a bit of time trying to figure this out: The problem with the original implementation is that `produceMana` returns a single `Mana` object. When adding `ConditionalMana` to a `Mana` object, the condition is ignored. Fixing this correctly would likely require a bit of a rework to allow one ability to have multiple `ManaEffect`s. Of particular note is `ManaOptions.addMana`, which treats multiple mana effects as if they were mutually exclusive abilities.
