### ISSUE TITLE
Cheating in a Dual face card can cause GUI to raise a NullPointerException

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8955]
1. Cheat in on a testing server the back side of a dual face card (e.g. [[Reflection of Kiki-Jiki]]).
2. Press the flip card button on it twice.
3. Client will hit a null pointer exception and freeze.

**Comment by awjackson** [comment]
This issue is related to #8859. Permanents should never be "backed" by the back face of a TDFC (i.e. the `card` field of `PermanentCard` should always be a front face, not a back face) or all sorts of invariants involving UUIDs will be violated. The correct way to cheat a back-face TDFC into play is to cheat in the *front* face and then set the permanent to transformed.
