### ISSUE TITLE
The java version bug of the server has not been fixed

### ISSUE THREAD

**Issue by siyiye** [magefree/mage#8956]
The server of java 8.0_333 cannot be registered. There is no problem changing to java 8.0_202.

(The client does not have this problem)

**Comment by Alex-Vasile** [comment]
What version of XMage are you having this issue with?

**Comment by siyiye** [comment]
master branch(head:80f6ceccff24a0aebf17060c6974f6f18971b0fd) build.

**Comment by Alex-Vasile** [comment]
And when you say that it didn't fix the issue, what problem are you seeing?

Also what OS are you building it on?

**Comment by siyiye** [comment]
“there is an error inside server while emailing an auth token”

server：win 2008 r2
user：win10

**Comment by Alex-Vasile** [comment]
Sounds like you have authentication turned on, something the public and beta servers do not seem to be doing, nor the server I run privately.

Can you try applying the patch from #8927 on your local copy and see if that addresses the issue? That bumps the version of the google authentication, the thing doing the OAuth. So that might fix your issue.

**Comment by Alex-Vasile** [comment]
> Sounds like you have authentication turned on, something the public and beta servers do not seem to be doing, nor the server I run privately.
> 
> 
> 
> Can you try applying the patch from #8927 on your local copy and see if that addresses the issue? That bumps the version of the google authentication, the thing doing the OAuth. So that might fix your issue.

@siyiye ?
