### ISSUE TITLE
Flicker Events not firing in the proper order

### ISSUE THREAD

**Issue by gecslam** [magefree/mage#897]
I implemented the card Covetous Dragon which sacrifices when the controlling player has no artifacts in play, and it doesn't seem to trigger with flicker effects which exile the only artifact in play. I stepped through the code, and It looks like the card that gets flickered moves to exile and back to the battlefield before the GameEvent notifying the first zone change gets sent (for some reason, the moveToExile() method in CardImpl delays firing the event notice until later as a "simultaneous event", but fires the event immediately in putOntoTheBattlefield()). So when the first zone change event fires, and my TriggeredAbility implementation checks the battlefield for artifact permanents, the artifact is already back in play.

**Comment by emerald000** [comment]
You should use a StateTriggeredAbility. I'm not sure if it will work better, but it will be more rules compliant.

**Comment by gecslam** [comment]
That's how I did it, and the bug's still there.

**Comment by emerald000** [comment]
Okay, just making sure. Definitely a bug then.

**Comment by LevelX2** [comment]
The simultaneous events are used to restrain event firing for effects that move multiple objects at the same time. Because if the events fire immediately with the movement other objects that should be  moved at the same time are not moved yet and so the check for triggers won't work necessarily correctly. I added this handling for fixing Valakut, the Molten Pinnacle, where it's important.

I added now logic to fire the gathered events after the resolving of each effect. So the flickering effects should now work correctly with Covetous Dragon. Also changed some object move code  to asl use simultaneous events where it was not done yet.

Maybe it's neccessary to rework this handling in the future if we find situations where it don't fit.
I think about adding mass move methods to move multiple objects from zone a to b where the ZONE_MOVE events are not fired until all objects are moved. That could replace in the future the current handling of simultaneous events. 
But this new move methods have then to be used in all cards that move objects at the same time and I guess there are a lot of.
