### ISSUE TITLE
Question about build version

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#907]
Why isn't the current build version 2015-04-14v7 instead of 2015-03-14v7?

**Comment by LevelX2** [comment]
The date represents a stable version where client and server interface isn't changed and all versions with the same date can work together. The server refuses clients with another date.
So I only increase the date if the interface between client and server was changed.
Alternatively It would be possible to use a increasing number instead of a date, like 1.3.12.v7.

**Comment by Greeneye0** [comment]
The month is for last month though. Has the build been in testing for a month and that is why you use the third month?

**Comment by LevelX2** [comment]
Because the first version with this Client  - Server interface was created on 2015-03-14 and isn't changed yet.
2015-03-14v7 is build on 2015-04-11
2015-03-14v5 is build on 2015-03-26
etc.
