### ISSUE TITLE
Casting Desertion on MDFC raises error

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9299]
I cast the back side [[Birgi, God of Storytelling]] and opponent targets it with [[Desertion]]. On resolution we get this error:
![desertion on birgi](https://user-images.githubusercontent.com/48962821/180128168-1a89a098-9ada-4389-a985-43f81c82d3b7.PNG)

**Comment by awjackson** [comment]
As of e40934921fcdb56f582567bd974761d3eb5a2444 this interaction no longer produces an error, but I'm not 100% sure which side of the MDFC is supposed to end up on the battlefield if a back-face spell is countered by Desertion.

>712.9. By default, a resolving double-faced spell that becomes a permanent is put onto the battlefield with the same face up that was face up on the stack. Some abilities may cause a transforming double-faced spell with its front face up on the stack to enter the battlefield transformed.
>
>712.10. A double-faced card put onto the battlefield from a zone other than the stack enters the battlefield with its front face up by default.

712.9 doesn't apply because the double-faced spell isn't "resolving", and 712.10 doesn't apply because the card isn't entering "from a zone other than the stack". I've gotten contradictory answers from judges as to what's supposed to happen, though *most* of the judges I've asked say the card should enter front-face up (currently in xmage it enters back-face up).
