### ISSUE TITLE
Field of the dead slows down the game, even without an AI present

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9317]
[[Field of the Dead]]

I think the issue is the way it counts uniques: https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Sets/src/mage/cards/f/FieldOfTheDead.java#L63-L70

I propose replacing this with the following two parts:
1. A for-loop that terminates earlier
2. Caching the IDs and names of each land of the 7 lands in a dictionary. Upon subsequent calls, it should pull the cache, check if all 7 are still on the board and under the controller’s control land bypass the iteration over all lands.

**Comment by weirddan455** [comment]
Do we have a good way to do performance testing?  I did a quick and dirty microbenchmark of this (and maybe it's flawed) but I'm showing that this function returns very quickly (less than 0.1ms most of the time).

```
    public boolean apply(Game game, Ability source) {
        Player player = game.getPlayer(source.getControllerId());
        if (player == null) {
            return false;
        }
        long start = System.nanoTime();
        boolean ret = game
                .getBattlefield()
                .getAllActivePermanents(StaticFilters.FILTER_LAND, source.getControllerId(), game)
                .stream()
                .map(permanent -> permanent.getName())
                .filter(s -> s.length() > 0)
                .distinct()
                .count() > 6;
        long end = System.nanoTime();
        double duration = (end - start) / 1000000.0;
        System.out.println("Duration: " + duration + "ms");
        return ret;
    }
```
This is with 30 lands on the battlefield and 5 field of the deads.  Additionally, the triggers only took about 1 second total to resolve (just eyeballing it on my system).

I'm guessing the slowdown people are experiencing is due to lots of tokens being present but without some kind of test case it's hard to tell.

**Comment by Alex-Vasile** [comment]
I have tried a similar thing, and couldn't get any sort of slowdown from it. I had like 80 of each lands. I will get some more info from the person.

It could be that it's simply used in a token deck, and it's actually the presence of many tokens that's the slowdown.

**Comment by Alex-Vasile** [comment]
I'm closing this as unreproducable
