### ISSUE TITLE
Some tests fail randomly

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#9391]
# Notes
Some tests may fail randomly, e.g. the Grips of Chaos one mentioned here. To track it down, you can set IntelliJ to keep rerunning a test until failure. This will make it easier to reproduce.

# Original
The build is currently failing.  https://app.travis-ci.com/github/magefree/mage/jobs/580389121

```
[ERROR] Failures: 
[ERROR]   GripOfChaosTest.noValidTargetsTest:58->CardTestPlayerAPIImpl.execute:288->CardTestPlayerAPIImpl.assertAllCommandsUsed:1504->CardTestPlayerAPIImpl.assertChoicesCount:1482 (Choices of PlayerA) Count are not equal (found [Yes]). Some inner choose dialogs can be set up only in strict mode. expected:<0> but was:<1>
```

I'm guessing it broke in 3c0951c350cfdbd4756f68bf38a4f697c11aeea1 or b5016693652deba8307c067f5dc9a39e392915b4

**Comment by weirddan455** [comment]
Those 2 commits have successful tests but it seems like tests are being flaky after those commits.  607f0270d54a4a938853383e90db5dbce0253c79 failed EtherealValkyrieTest (directly after the test changes, this commit did nothing but add a card).

```
[ERROR] Failures: 
[ERROR]   EtherealValkyrieTest.testMDFCCreatureCreature:169->CardTestPlayerAPIImpl.execute:280 Missing CAST/ACTIVATE def for turn 1, step PRECOMBAT_MAIN, PlayerA
Can't find available command - activate:Cast Ethereal Valkyrie (use checkPlayableAbility for "non available" checks)
```

**Comment by Alex-Vasile** [comment]
I am not sure why they are being flaky, the Grips of Chaos test does not even produce any warnings.

**Comment by weirddan455** [comment]
Yea and the latest build passed when all I did was add a card.  Might be tricky to narrow down if it's going to be inconsistent like this.

**Comment by Alex-Vasile** [comment]
It's not "you may" abilities since the Valkyrie ability is not one of those (but the Grips of Chaos is).
It's not the targeting or `setStrictChooseMode(true)` since the Valkyrie error doesn't involve that.

It could be the way in which the AI taps the land for mana is not deterministic and it may be tapping the mana wrong. So that the second Valkyrie cast doesn't have enough {W}.

**Comment by Alex-Vasile** [comment]
Might also be:
https://github.com/magefree/mage/blob/2d56e231481a17b4429284880f523f319b23ac22/Mage.Tests/src/test/java/org/mage/test/player/TestPlayer.java#L623-L625

I will take care of that TODO and see if fixes things

**Comment by Alex-Vasile** [comment]
Let's see if 37f4f40a2c4962ce707521515de9c108bd16c003 fixed it.

The current failure is because of a card verify issue.

**Comment by Alex-Vasile** [comment]
Grips of Chaos was actually fixed later in: 4b9b419f2ee5ccad3059cf5ad051e66338da5c03

From the commit:
> NOTE: Cannot use setStrictChoiseMode(true) with current test setup.
   When both ETB triggers target the same permanent because of Grip of Chaos the second (bottom-most)
   Ability will fizzle.
   This will cause random errors since setStrictChoiseMode(true) will require the player to make an explicit choice
   About whether or not to apply the effect of the ETB trigger.
   HOWEVER, when the second ETB fizzles, the "setChoice(playerA, "Yes")" will error out since it was a choice that did not get used.

**Comment by Alex-Vasile** [comment]
This one is also failing intermittenly, will investigate:
https://github.com/magefree/mage/blob/5e6921b34644584d1dba1385c7b35412e99a3ebd/Mage.Tests/src/test/java/org/mage/test/cards/single/khc/EtherealValkyrieTest.java#L150

**Comment by Alex-Vasile** [comment]
I'm going to close this and link to it with any issues that come up since each one is failing for different reasons.
