### ISSUE TITLE
Beta Server - Astral Cornucopia

### ISSUE THREAD

**Issue by sinsang85** [magefree/mage#9392]
astral cornucopia only adds one mana regardless of the number of charge counters on it.

Utilized Surge Node to add charge counters up to 5, but cornucopia only tapped for one.

**Comment by Alex-Vasile** [comment]
Caused by 19a896df57fce1dda650001052b42363db2bfdda

When returning the new mana object from `produceMana`, the new object does not use `counters` to specify the number of counters to add:
https://github.com/magefree/mage/blob/89466d0f8fcb975df5c9e43c6e64a1c33cb39eef/Mage.Sets/src/mage/cards/a/AstralCornucopia.java#L109-L110
