### ISSUE TITLE
[BETA] trustAnchors exception when downloading images

### ISSUE THREAD

**Issue by Jengamon** [magefree/mage#9401]
So I'm trying to get into XMage, and get all my images downloaded and stuff, but whenever I try to download symbols or images, I get a `java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty` error. It happens every single time, I've tried

- pointing to a trustAnchors store explicitly with javax.net.ssl.trustAnchors and trustStore
- creating a blank trust store and adding some root certs from the sites XMage downloads from to it

and no luck.

**Comment by Alex-Vasile** [comment]
The issue comes from #9266. You can see the path that the certificates are expected to be at, and download a copy of them from that PR.

The issue is that they are not getting packaged properly. (I don't know why, and haven't gotten the chance to figure out how to fix it). If you know how to fix it, it would be much appreciated.

**Comment by Jengamon** [comment]
I got around this and downloaded images by running the client on Temurin 11, but it still can't download symbols.

**Comment by Alex-Vasile** [comment]
> I got around this and downloaded images by running the client on Temurin 11, but it still can't download symbols.

What error are you getting for the symbols?

**Comment by Jengamon** [comment]
`Unable to find valid certification path to requested target`
