### ISSUE TITLE
EntersBattlefieldThisOrAnotherTriggeredAbility not implemented properly?

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9419]
As currently implemented EntersBattlefieldThisOrAnotherTriggeredAbility makes two checks for checking the trigger.
1. It checks if the permeant is the same one which has the ability:
https://github.com/magefree/mage/blob/80e11b20528dfb88a91c3f3be66a354818a0606b/Mage/src/main/java/mage/abilities/common/EntersBattlefieldThisOrAnotherTriggeredAbility.java#L49-L50

3. If 1. does not match, the it will check the permanent entering matches the specified filter:
https://github.com/magefree/mage/blob/80e11b20528dfb88a91c3f3be66a354818a0606b/Mage/src/main/java/mage/abilities/common/EntersBattlefieldThisOrAnotherTriggeredAbility.java#L55

I believe that 1. is wrong. The ability is worded as "Whenever {this} or {that} enters the battlefield" and not "whenever **this** or {that} enters the battlefield". I believe that the trigger should be checking based on the name of the permanent.

Original bug: "making a non-elemental copy of Risen Reef (as with Croaking Counterpart) doesn't result in it triggering on itself entering"

**Comment by awjackson** [comment]
You're right that `EntersBattlefieldThisOrAnotherTriggeredAbility` doesn't work properly, but you're wrong about the reason.

In Magic rules text, the name of a card means "this {object}". It doesn't mean "any {object} with the same name as this one". Abilities that care about card names specifically say "an {object} named {name}". If the rules worked the way you suggest they do, if you controlled a Mulldrifter and then had a second Mulldrifter enter the battlefield, each of them would trigger the other and you'd draw a total of four cards.

The actual reason `EntersBattlefieldThisOrAnotherTriggeredAbility` is bugged is because of the call to `super`:

```
if (!super.checkTrigger(event, game)) {
            return false;
        }
```

This calls `EntersBattlefieldAllTriggeredAbility.checkTrigger`, which itself checks the entering object against the filter. If the object doesn't match the filter (e.g. a Risen Reef that for some reason isn't an Elemental), we end up bailing before we even get to the code that's specific to `EntersBattlefieldThisOrAnotherTriggeredAbility.checkTrigger`.

**Comment by Alex-Vasile** [comment]
> You're right that `EntersBattlefieldThisOrAnotherTriggeredAbility` doesn't work properly with modified-copy effects like Croaking Counterpart, but you're wrong about the reason.
> 
> In Magic rules text, the name of a card means "this {object}". It doesn't mean "any {object} with the same name as this one". Abilities that care about card names specifically say "an {object} named {name}". If the rules worked the way you suggest they do, if you controlled a Mulldrifter and then had a second Mulldrifter enter the battlefield, each of them would trigger the other and you'd draw a total of four cards.
> 
> The actual reason `EntersBattlefieldThisOrAnotherTriggeredAbility` is bugged is because of the call to `super`:
> 
> ```
> if (!super.checkTrigger(event, game)) {
>             return false;
>         }
> ```
> 
> This calls `EntersBattlefieldAllTriggeredAbility.checkTrigger`, which itself checks the entering object against the filter. If the object doesn't match the filter (e.g. a Risen Reef that for some reason isn't an Elemental), we end up bailing before we even get to the code that's specific to `EntersBattlefieldThisOrAnotherTriggeredAbility.checkTrigger`.

Ahh okay. I knew there was a distinction between "this" and "{this}", but I forgot the exact wording. Thanks for clarifying!

**Comment by Alex-Vasile** [comment]
Can you also please add a test for it. I'm surprised it took this long for it to come up.

**Comment by awjackson** [comment]
The `EntersBattlefieldThisOrAnotherTriggeredAbility` class is only used by about 30 cards. Most "when {this} or another {type} enters" cards in Magic are Rally cards from Zendikar sets or Constellation cards from Theros sets, each of which have their own ability-word-specific implementations in xmage that don't share this issue.
