### ISSUE TITLE
Support more deck formats

### ISSUE THREAD

**Issue by AMPBEdu** [magefree/mage#943]
This is the number one flaw I've seen with this program. In cockatrice you can copy and paste text, then it removes all irrelevant text (such as "Creatures:", or x after a number like 4x Cardname) then parses it. It also looks for SB: in front of a sideboard card or Sideboard: <insert list of cards> to put in the sideboard. Creating a parser that accepted multiple file formats would be nice, and as I'm looking to start helping out with development I'll try and make a parser like this Edit: also, how do I mark this as an enhancement?

**Comment by LevelX2** [comment]
I guess the text import does laready a lot of the things you mention. Did you check out?
https://github.com/magefree/mage/blob/2e38bf007a261d81dd82184fad5c6a9ee89aa866/Mage/src/mage/cards/decks/importer/TxtDeckImporter.java
But also a good thing can be improved. Feel free to add more functionality.

**Comment by GHSAndrew** [comment]
Oh I did not see that. Atm i'm most interested in improving parts of the gui to make the client less "clunky", so I'll see what I can do to make that clipboard import

**Comment by gnumast** [comment]
Sorry to revive an old issue but seeing how it's still opened I figured it'd be better than creating a new one for a similar discussion.

@LevelX2 I've look at [`txtDeckImporter`](https://github.com/magefree/mage/blob/2e38bf007a261d81dd82184fad5c6a9ee89aa866/Mage/src/mage/cards/decks/importer/TxtDeckImporter.java) and I'm wondering if there's a reason the sideboard isn't detected after only 1 blank line? From the common format I see around:

- Apprentice (`.dec`) uses "SB: <Card Name>"
- OCTGN2 (`.o8d`) is in XML, not related
- MTGO uses a line that contains "Sideboard" between main and side (which mage supports)

These 3 are probably pretty popular since they can be exported from the MTGSalvation forums ([example](http://www.mtgsalvation.com/forums/the-game/modern/tier-1-modern/219590-affinity?comment=4747)). On mtgtop8 they also have downloads in the Magic Workstation format which unless I'm mistaken is exactly what mage uses. TappedOut has a bunch of options most of them for sharing (ie. markdown/reddit, mtg salvation, printable etc...). Interestingly enough they also offer export a decklist to a list of multiverse id, that's great for importing too since you get exact versions of cards in a format that's very easy to parse (ie. <#> <digits>).

The reason I'm asking is because I personally use MTG Goldfish a lot and they export to a `.txt` file which contains a single blank line to separate the main deck from the sideboard. The one issue on there is with commander/tiny leader where the exported file is a list of 100 cards with no handling for the commander.

Anyways, long winded post to ask a simple question: any reason why the deck importer can't assume the sideboard starts after a single blank line?

Additionally, since it was also mentioned here, I love the "Import from Clipboard" that is available in Forge:
![forgeclipboardimport](https://cloud.githubusercontent.com/assets/175920/15636135/6d4992e0-25c3-11e6-9895-e12e9ab3af12.png)

The automatic card validation on the right side is awesome. If there is still interest for this I might look into implementing it into mage.

Thanks

**Comment by LevelX2** [comment]
> @LevelX2 I've look at txtDeckImporter and I'm wondering if there's a reason the sideboard isn't detected after only 1 blank line?

No, it should be added. It's mostly a problem of missing time to implement improvements.

**Comment by LevelX2** [comment]
> The automatic card validation on the right side is awesome. If there is still interest for this I might look into implementing it into mage.

Sure, everyone improving XMage is very welcome.

**Comment by fireshoes** [comment]
Another popular improvement for importing would be to the ability to set a preference of art/edition of a card. I believe the current implementation always selects the most recent non-supplemental printing. Perhaps a preference tab could be added to choose from original printing, newest printing in an expansion set, or newest printing including promos or supplemental sets. Probably other options too but that's the main ones off the top of my head.

**Comment by JayDi85** [comment]
I'm improved text format in last commits (1efc062f6666d037b2429cdd49800d467e99d846, 5fc0393bc7b794fc8f1e7655404bbf4d02de118b, dce69c18dc86eb147ec78d4bf3c98733179b516e). Will be available in v10 release.

Added new text format from [deckstats.net](http://deckstats.net/) (e.g. support of `//sideboard`, `SB:` and `#comment` tags in text). 

Also added a detailed description on every line error:
![shot_171209_152314](https://user-images.githubusercontent.com/8344157/33967757-3f9ac504-e07e-11e7-9391-40aad0f7376c.png)
