### ISSUE TITLE
Deepglow Skate consistently causes a lot of lag, crashes games

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#9438]
When testing some planeswalker emblem imaging I initially used [[Deepglow Skate]]s to bring their loyalty high enough to ult, but had to stop using them as they would cause such a massive amount of lag and would frequently crash the server. Tried playing a superfriends-style deck today which uses Deepglow Skate, and casting it caused the game to grind to a halt and eventually freeze the entire window before crashing completely. Task manager confirmed that the server was using 90% of my CPU at this time.

**Comment by Alex-Vasile** [comment]
This seems to be AI related. I doubt it will happen in PvP game.

I have not figured out exactly what it is (it's not the triple for loop in the apply() since that happens on resolution and teh slowdown is before the player even picked targets), but my hunch is that the AI is going to try to figure out what our targets are. The issue is that deepglow skate lets you pick any number of targets. So the AI iterates over every possible combinations of 0 to N permanents (number of permanents on the batttlefield), this is an incredibly large number.

I think the optimization here is to not check all of the combinations:
1. Prune out all permanents which don't have a counter (this will miss edge cases, but a good tradeoff)
2. Assume that the player will target all permanents which will improve their position (and therefore hurt the AIs) if they get more counters (i.e. buff their own creatures, put more -1/-1 on the AIs creatures, and do something (which I haven't thought through yet) for any other players permanents)

**Comment by Alex-Vasile** [comment]
What did you board look like when you were having these issues?

**Comment by PurpleCrowbar** [comment]
> What did you board look like when you were having these issues?

Relatively large number of permanents, between 25-30 I’d say. Opponent had around 5 or so. Only one opponent bot remaining (I assume the other bots cease to run any calculations if they’re eliminated). Of the permanents under my control there were maybe 5 or 6 planeswalkers. I was able to select one of them as a target for the skate before the performance really started to drop.

**Comment by Alex-Vasile** [comment]
Combining this into #9528

**Comment by weirddan455** [comment]
> Combining this into #9528

I think you tagged the wrong thing.  That PR doesn't have anything to do with this issue.

**Comment by Alex-Vasile** [comment]
> > Combining this into #9528
> 
> I think you tagged the wrong thing. That PR doesn't have anything to do with this issue.

You're right. Oops. I meant #9539
