### ISSUE TITLE
There has to be a separate refactor for effects that distribute among targets

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9457]
I think this can be merged as is but there probably has to be a separate refactor for effects that distribute among targets

_Originally posted by @theelk801 in https://github.com/magefree/mage/issues/9408#issuecomment-1234966660_

**Comment by xenohedron** [comment]
I don't think I like that approach.

The TargetAmount classes are already a bit unwieldy as it is due to the way filters are structured:
![image](https://github.com/user-attachments/assets/25134c49-2a7d-45ea-a6d0-c251dd2c1eb8)
Adding another parameter by separate classes will not be a good inheritance structure.

It may be better to force devs to define all the relevant constructor parameters, such that the base constructor in TargetAmount has a signature of (DynamicValue amount, int minNumberOfTargets, int maxNumberOfTargets) like standard target classes and all the others chain from that (applying appropriate defaults where params can be safely omitted)

Another point - the amount param should be removed from the effect classes and the text generation can take it from the TargetAmount instead, to reduce duplication. (Makes sense to check instanceof TargetAmount anyway.)

Thoughts?

**Comment by Cguy7777** [comment]
That sounds like a better approach. I'll start with that idea and see how it works.
