### ISSUE TITLE
Big: Surveyor's Scope

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9461]
From Reddit: [[Surveyor's Scope]]
"doesn’t check if my opponent’s have more than 2 lands than I, let me get all my basic lands at once, been playing with bot to test a EDH deck, turn 2 scope I can get up to my 20 basic lands"

**Comment by awjackson** [comment]
This is a common class of bug with search effects where the number of cards to search for is dynamic. Somewhere or another 0 is being treated as a magic number meaning "any number". Since these are by necessity all custom effects (none of the standard classes in `abilities.effects.common.search` have any way to support a DynamicValue) we've just been fixing them one by one as they are found instead of trying to track down the place where 0 is being treated as a magic number. See f07004e27c90cfb7786d4fa418da147f5178d991 for an example.

**Comment by Alex-Vasile** [comment]
> This is a common class of bug with search effects where the number of cards to search for is dynamic. Somewhere or another 0 is being treated as a magic number meaning "any number". Since these are by necessity all custom effects (none of the standard classes in `abilities.effects.common.search` have any way to support a DynamicValue) we've just been fixing them one by one as they are found instead of trying to track down the place where 0 is being treated as a magic number. See f07004e27c90cfb7786d4fa418da147f5178d991 for an example.

What would make sense as a new magic number, negative or null?

Also, is there an issue open for tracking down where this happens?
