### ISSUE TITLE
Losing the game while in control of a goaded creature causes NPE in multiplayer

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9604]
Reported bug from discord.

Opponent casts [[Disrupt decorum]], next turn player attacks another opponent, and the game crashes because of `Auto-restored to T29.CD due game error: null`

Attached is full game log. (change extension from `.txt` to `.html`, GitHub won't let me upload with `.html`).

[20220930_202540_Commander_Free_For_All_1.txt](https://github.com/magefree/mage/files/9689334/20220930_202540_Commander_Free_For_All_1.txt)

**Comment by PurpleCrowbar** [comment]
It is a goad issue. It seems like if a player loses the game whilst having goaded creatures under their control and them losing the game doesn't cause the game to end (i.e., at least two other players are still in the game) then the game crashes due to a NPE. I recall reading about this issue, maybe here or on the Discord server

**Comment by xenohedron** [comment]
Presumably fixed by 22552ed, can reopen if not
