### ISSUE TITLE
Possibility of an Android client

### ISSUE THREAD

**Issue by Malabarba** [magefree/mage#961]
I've been thinking about starting to work on an (open source) Android client for Xmage. By reading the [Developer Notes](https://github.com/magefree/mage/wiki/Developer-Notes), I get the impression that everything is very modular. So it sounds like a feasible task at least.

Before I dive into a discussion or a bunch of questions on the necessary steps, I thought it was better to see how the Xmage devs would feel about that.
Is that something that would be welcome?

Cheers

**Comment by LevelX2** [comment]
Hello Malabarba,

sounds like an enormous task for me, but I'm also not so into the network communincation and handling JBOSS communication with an android clinet, that has no native java.

Maybe it would be easier if the network layer is updated like discussed here (http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=17117). So I recommend to ask your question in this thread because North and BetaSteward can evaluate the practicability a lot better.

Such a feature would be welcome for sure. 
But probably some more touch control improvments have to be done to be satisfying.
Also dealing with the smaller UI and creating a handy solution would be the implementation make more hard.

**Comment by Malabarba** [comment]
> sounds like an enormous task for me, but I'm also not so into the network communincation and handling JBOSS communication with an android clinet, that has no native java.  
> Maybe it would be easier if the network layer is updated like discussed here (http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=17117). So I recommend to ask your question in this thread because North and BetaSteward can evaluate the practicability of such a project a lot better.

Thanks, that's good to know. I'll start by having a look at the current networking code, to see if it seems doable on an android client, and then show up at that thread. 

> But probably some more touch control improvments have to be done to be satisfying.
> Also dealing with the smaller UI and creating a handy solution would be the implementation make more hard.

For sure, but those are interesting challenges I'm happy to face. Less fun challenges I predict are performance issues and sheer size of the APK.

Thanks for the quick reply. I'll do some reading and think about this some more.
