### ISSUE TITLE
Delta updates

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9677]
Instead of having to download the whole server and client every time there's an update, it would be very nice to only have to download three changes.

**Comment by copperfield42** [comment]
that is a good idea, they guys that make the YuGiOh Edopro simulator have it like that, when new cards are available it only download the script for those cards (or in any case the minimum necessary to make those cards work) and you can play wit it almost as soon as it is ready instead of waiting for the next full update that is days, week or months away

**Comment by DreamWaker** [comment]
I've been wondering if there could be a way to do a parity setup for the files.

It could work a lot like this, and would allow for much smaller downloads, that basically "fix" the changes in the files.

**Comment by JayDi85** [comment]
No need nowadays. 100-200 MB is a normal app size for any mobile app (as example).
