### ISSUE TITLE
Cadric , Soul Kindler Does not prevent legends rule

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9691]
![image](https://user-images.githubusercontent.com/63882410/198652859-3ed2d56a-a4d9-49f3-b01f-2d3601ba8954.png)

**Comment by jeffwadsworth** [comment]
[[Cadric , Soul Kindler]]

**Comment by jeffwadsworth** [comment]
Perhaps this rule-modifying effect would be best served with a simple asThoughEffect().  I add that "perhaps" so we don't get rule guru freakouts in case there is a more proper solution.

**Comment by awjackson** [comment]
This card needs @theelk801's refactor #9662 in order to work properly. The way xmage implements turning off the legend rule for a subset of permanents simply doesn't work for subsets other than "all permanents one player controls" or "all permanents with a specific name", and until Cedric those were the only kind that existed.

**Comment by awjackson** [comment]
Should be fixed by 3ed26a2b1f27e3498e028a5adf21e0daedbf6297
