### ISSUE TITLE
Need to restrict usernames to a maximum of say 200 characters

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#9813]
People in beta are messing with really long usernames.

**Comment by billyg-da-great** [comment]
There is no limit on characters in username and it is crashing the server because bad actors are trying to put books (mein kampf specifically) worth of text in their username field before logging in.  This is effectively denial-of-servicing the Beta server. 

Every time this guy logs in he makes everyone download a few 10s of megabytes from the server all at once in the form of his username.  This causes everything to hang.

**Comment by billyg-da-great** [comment]
I see you have a patch already. This maybe is worth making live on the beta immediately because the dude wont stop and nobody can test anything else cause it freezes non-stop

**Comment by JayDi85** [comment]
Fixed in #9815, server will be tomorrow
