### ISSUE TITLE
[BUG] Spells which target spells can target themselves

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9849]
This did not used to be the case - it's something I noticed broke fairly recently. For instance, [[Deflecting Swat]] can target itself. The game won't let you try and cast the spell with no targets already available, though. The comprehensive rules have this to say:

> **115.5.** A spell or ability on the stack is an illegal target for itself.

**Comment by jeffwadsworth** [comment]
I tested this with [[Increasing Vengeance]] and it could not target itself.  I don't play "Commander" so I wasn't able to test this specific scenario.  Perhaps another dev can do that.

**Comment by alexander-novo** [comment]
Going back and trying it with some more spells, it seems like it might not be a case of all spells. Here is an example with Deflecting Swat specifically:

![image](https://user-images.githubusercontent.com/11657716/212743659-93e0f46f-7017-41a5-bd1a-9b7535aca3ac.png)

![image](https://user-images.githubusercontent.com/11657716/212743677-884a980b-446e-4793-9259-774c393c8147.png)

![image](https://user-images.githubusercontent.com/11657716/212743698-f7a18f91-6399-4d8c-87e7-01002adea995.png)

I also tried it with a counterspell, but while the counterspell lit up yellow like the second shot above, it didn't allow me to click it.

**Comment by xenohedron** [comment]
This seems to be a general problem; just noticed it on Lithoform Engine's activated ability to copy target activated ability. In my experience, it's not possible to _actually_ select the source as a target for itself, but it is highlighted in yellow as if it could be, and a single legal target won't be automatically chosen.

I'm guessing it has something to do with
`public boolean canChoose(UUID sourceControllerId, Ability source, Game game)` and
`public boolean canChoose(UUID sourceControllerId, Game game)`,
but I haven't done enough research to understand why those two methods both exist. But if some chain in the target selection logic is using the `canChoose` method with two arguments instead of three, that could be the issue.

**Comment by xenohedron** [comment]
I also wouldn't be surprised if "choose new targets" doesn't work properly with the self-targeting restriction somehow.

**Comment by xenohedron** [comment]
Fixed by 91c1d1d
