### ISSUE TITLE
Prowling Geistcatcher exiles a triggered ability and fails to return creatures to battlefield

### ISSUE THREAD

**Issue by TheKnightOfTheNorth** [magefree/mage#9981]
![Screenshot_20230214_033419](https://user-images.githubusercontent.com/125488103/219092189-82d05486-6096-4c86-9402-db25ac563f56.png)

Prowling Geistcatcher would not return the creatures it exiled to the battlefield after sacrificing it. Additionally, it appears to have exiled the triggered ability of Pawn of Ulamog instead of the card itself.

**Comment by Merlingilb** [comment]
[[Prowling Geistcatcher]]

**Comment by PurpleCrowbar** [comment]
I’m 99% sure the exiling of a triggered ability thing is just a common visual bug on xmage in which cards are sometimes represented with the “triggered ability” format, happens relatively commonly with cards that trigger a lot, like Rhystic Study. So the issue is the creatures not returning to the battlefield
