### ISSUE TITLE
Stangg, Echo Warrior bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9999]
The copy of [[Stangg, Echo Warrior]] has nothing equipped to it   

![image](https://user-images.githubusercontent.com/64045003/219856550-af76add5-10eb-470c-ab20-976cfed72b67.png)

**Comment by Merlingilb** [comment]
I tested this with [[Abzan Runemark]] and [[Basilisk Collar]] and Holy Avenger and none were attached to the Twin Token. Because Abzan Runemark is an Aura it asks you which creature should be enchanted, when it enters the battlefield but you could target any creature here (not sure if that is intended)

**Comment by xenohedron** [comment]
Fixed by e8ffe90
